### ISSUE TITLE
when i open the sidebar the amount of new messages disappear before i can read it

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#1]
When open the sidebar the hubs will show the amount of new messages but the active hub will not or it does but it disappear before i could read it. If i'm lucky i manage to see it. It should stay there until i press the hub name the same way as i change hub. So if i want to check the active hub last i still have the amount of new message there until i activate the hub again. If only the active hub got new messages i only press it and the amount of new messages disappear. It will work as a confirm button that i have read all the messages.
![picpick-2015 11 05-20 06 52](https://cloud.githubusercontent.com/assets/5789283/10979501/307dd104-83fd-11e5-8fb7-416dc1f14660.jpg)

**Comment by maksis** [comment]
A delay could be added there

**Comment by Sopor-** [comment]
I should prefer the way i explained. That will make me choose what hub i want to read first. If i want to do something else first in another hub i first have to check what is new in the active hub because if i don't do that the new message  indicator will disappear. If I then have 60 new messages to read i probably skip it because it will take too long time. At least think about it :)
You could let me test my idea first. I will very soon notice if it was a bad idea or not...

**Comment by maksis** [comment]
I went with the delay as I haven't used any chat application with such confirm button
