### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by infectormp** [airdcpp-web/airdcpp-webclient#101]
Just make a clean install of AirDC++w 0.16.5 and get error on startup

Starting web server[2016-02-29 15:11:01] [info] asio listen error: system:97 (Address family not supported by protocol)
Failed to set up HTTP server on port 15600: Underlying Transport Error (is the port in use by another application?)
[2016-02-29 15:11:01] [info] asio listen error: system:97 (Address family not supported by protocol)
Failed to set up HTTPS server on port 15601: Underlying Transport Error (is the port in use by another application?)

Look like problem in IPv6 that not supported by my system.

**Comment by maksis** [comment]
The relevant question is that what kind of system do you have if it doesn't understand IPv6 at all

**Comment by infectormp** [comment]
Gentoo with kernel compiled without ipv6 support.
29 февр. 2016 г. 6:18 PM пользователь "maksis" <notifications@github.com>
написал:

**Comment by maksis** [comment]
I'll reopen this as IPv6 as some virtual servers may also use a kernel without IPv6 support. Maybe the client could determine that somehow.
