### ISSUE TITLE
Can't connect into hubs from Raspberry Pi

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#103]
First i believed issue #87 did make it impossible to connect into hubs but i manually added TCP and UDP port into DCPlusPlus.xml and now i can see the port numbers in settings but i still only see "Connected"
```
Connecting to adcs://xxxxxxx.xxxxxx.xxx:35241/?kp=SHA256/EVZFGCLJMXVQAJ4REEWGS2LI4XXXXXXHGGSSCWLIVZSP3PER32RA ...
19:32:24
Connected
```
When i connect into other hubs it will show the hubs name and not the hub address as i see now in the WebUI.
If i try to view the user list i can only see Connecting and the spinning busy wheel.
I can't see the user in the user list from another client.
So i'm connected but still not connected at the same time...

Application version
AirDC++w 0.16.4 armv7l / 0.850
Web UI version
0.16.2

**Comment by maksis** [comment]
> When i connect into other hubs it will show the hubs name and not the hub address as i see now in the WebUI.

It's not clear to me that what do you mean with this.

You should run the client with ``--cdm-hub`` option and post the output here.

**Comment by Sopor-** [comment]
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:24163           0.0.0.0:*               LISTEN      30033/airdcppd
tcp        0      0 0.0.0.0:24162           0.0.0.0:*               LISTEN      30033/airdcppd
tcp6       0      0 :::24163                :::*                    LISTEN      30033/airdcppd
tcp6       0      0 :::5601                 :::*                    LISTEN      30033/airdcppd
tcp6       0      0 :::24162                :::*                    LISTEN      30033/airdcppd
```

**Comment by Sopor-** [comment]
This will change to the hub name instead of showing the hub address...
![picpick-2016 02 29-22 38 55](https://cloud.githubusercontent.com/assets/5789283/13409920/5ec7e0a2-df35-11e5-93e9-746bd2bb39a9.jpg)

I will try --cdm-hub

**Comment by Sopor-** [comment]
When i shutdown i will also see this:
[info] asio async_shutdown error: asio.ssl:336130329 (decryption failed or bad record mac)

**Comment by Sopor-** [comment]
Is this what you wanted to see?
`Hub:    [Outgoing][94.xxx.xxx.xxx:35241] H ADBAS0 ADBASE ADTIGR ADUCM0 ADZLIF ADHBRI`

**Comment by maksis** [comment]
Is that the only line you have...? It would be quite useful to try different types of hubs. NMDC hubs, hubs without encryption and so on.

**Comment by maksis** [comment]
Actually the command you posted is incorrect (the first segment should be ``HSUP``, not plain ``H``). This issue is probably inherited from DC++.

**Comment by Sopor-** [comment]
NMDC seems to work

**Comment by Sopor-** [comment]
ADC will not even show Connected and will generate no log at all

**Comment by maksis** [comment]
You could try replacing airdcpp-core/airdcpp/AdcCommand.h with the one from https://github.com/airdcpp/airgit/tree/master/airdcpp/airdcpp

**Comment by Sopor-** [comment]
I replaced the `AdcCommand.h` and did a recompile and now i can connect :)
