### ISSUE TITLE
IPv6 connectivity (manual) is grayed out when Connectivity (auto detected) is set to disable

### ISSUE THREAD

**Issue by Sopor** [airdcpp-web/airdcpp-webclient#105]
When i use "Auto detection", AirDC will find the correct settings for me but when it disable IPv6 it will also gray out the "Let AirDC++ determine the best IPv6 connectivity settings". If i now want to turn off  "Auto detection" i first need to change "Connectivity (auto detected)" to "Active mode" and when i do that, it is suddenly grayed out and now the "Let AirDC++ determine the best IPv6 connectivity settings" is not grayed out anymore. I then Disable "Connectivity (auto detected)" and again the "Let AirDC++ determine the best IPv6 connectivity settings" is grayed out.

The "Let AirDC++ determine the best IPv6 connectivity settings" should not be grayed out so i can turn it off/on if i want to. Same for IPv4 of course.

One more thing, if i do all these steps the "Save changes" will change back to "No unsaved changes" and i can't save it.

Application version: AirDC++w 0.16.4 armv7l / 0.850
Web UI version: 0.16.2
and
Application version: AirDC++w 0.16.5 x86_64 / 0.850
Web UI version: 0.16.2

**Comment by Sopor-** [comment]
As you can see here IPv6 show (auto detected) even when it is disabled:
```
Current auto detection status

IPv4 connectivity
Active mode (manual configuration)
IPv6 connectivity
(auto detected)
```
Application version: AirDC++ 3.10a-364-gff014 x86-64 / 0.850
Web UI version: 1.0.0-beta2

**Comment by maksis** [comment]
"Disabled" will override the auto detect mode, which is because of how the Windows GUI has been implemented (in the Windows GUI auto detection can stay enabled even if you unselect"Enable IPvx connectivity"). Changing the current behavior would require changes in the core and Windows GUI, so I'll rather keep it as it is now.
