### ISSUE TITLE
Web UI not show more than 100 events in counter

### ISSUE THREAD

**Issue by infectormp** [airdcpp-web/airdcpp-webclient#106]
Web UI not show more than 100 events in counter
![events](https://cloud.githubusercontent.com/assets/9958813/13421173/ab6b8f4a-df9d-11e5-85b4-b70b3ae8a0ae.png)

Application version
AirDC++w 0.16.5 x86_64 / 0.850
Web UI version
0.16.2

**Comment by maksis** [comment]
That's because it won't cache more messages. You can change that from Settings -> View -> Histories -> System log (should be renamed to Events really).

**Comment by infectormp** [comment]
ah i see.

**Comment by infectormp** [comment]
maybe show **```100+```** if events more then 100.

**Comment by maksis** [comment]
The number of cached messages is shown so it can't be 100+ (older messages are removed)
