### ISSUE TITLE
Show each hashed file

### ISSUE THREAD

**Issue by infectormp** [airdcpp-web/airdcpp-webclient#108]
I enable **Show each hashed file**, then disable but events still getting info about each hashed file.

Application version
AirDC++w 0.16.5 x86_64 / 0.850
Web UI version
0.16.2

**Comment by infectormp** [comment]
Disabling **Show each hashed file** applied only after restart

**Comment by maksis** [comment]
> Disabling Show each hashed file applied only after restart

I can't see how this could happen

**Comment by infectormp** [comment]
After restart i get events when **Show each hashed** file not set.

**Comment by infectormp** [comment]
hm, **Show each hashed file** show files or folders? In events i see hashed folders.

**Comment by maksis** [comment]
The client shows information about hashed folders (or files, if there is nothing better to report) and there's no option to turn that off. ``Show each hashed files`` will just spam each single file that has been hashed.

**Comment by maksis** [comment]
Any updates on this?

**Comment by infectormp** [comment]
no, i close it
