### ISSUE TITLE
can't use any /commands

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#110]
I was trying to use one of the inbuilt command i get when i do /help but none of them work :(

I can understand why it is not working but it should not be written in main when i start a line with `/`.
We are all used to AirDC and of course we will try to use these commands so it would be much better if it only show `*** Unknown command: help` until i can use these command (if you make them work in the future?).

Application version: AirDC++w 0.16.5 armv7l / 0.850
Web UI version: 0.16.2

**Comment by KipourosV** [comment]
/ does not work, but some hubs I connect to, use ! as the command character and that works fine...

**Comment by Sopor-** [comment]
@KipourosV I'm not talking about the hubs commands. I'm talking about commands built in AirDC...

```
					HELP
------------------------------------------------------------------------------------------------------------------------------------------------------------
/refresh					Refresh share
/optimizedb				Remove unused entries from the hash databases
/verifydb					Optimize and verify the integrity of the hash databases
/stop					Stop SFV check
/sharestats				Show general share statistics (only visible to yourself)
/dbstats					Show techical statistics about the hash database backend (only visible to yourself)
/monitordebug				Show each change notification for monitored directories (only visible to yourself)
------------------------------------------------------------------------------------------------------------------------------------------------------------
/search <string>				Search for...
/whois [IP]				Find info about user from the IP address
------------------------------------------------------------------------------------------------------------------------------------------------------------
/slots # 					Upload slots
/extraslots # 				Set extra slots
/smallfilesize # 				Set smallfile size
/ts 					Show timestamp in mainchat
/connection 				Show connection settings, IP & ports (only visible to yourself)
/showjoins 				Show user joins in mainchat
/shutdown 				System shutdown
------------------------------------------------------------------------------------------------------------------------------------------------------------
/AirDC++ 					Show AirDC++ version in mainchat
------------------------------------------------------------------------------------------------------------------------------------------------------------
/away <msg>				Set away message
/winamp, /w				Shows Winamp spam in mainchat (as public message)
/spotify, /s				Shows Spotify spam in mainchat (as public message)
/itunes					Shows iTunes spam in mainchat (as public message)
/wmp					Shows Windows Media Player spam in mainchat (as public message)
/mpc					Shows Media Player Classic spam in mainchat (as public message)
/clear,/c					Clears chat
/speed					Show download/upload speeds in mainchat (only visible to yourself)
/stats					Show stats in mainchat (as public message)
/clientstats				Show general statistics about the clients in all hubs (only visible to yourself)
/prvstats					View stats (only visible to yourself)
/info					View system info (only visible to yourself)
/log system				Open system log
/log downloads 				Open downloads log
/log uploads				Open uploads log
/df 					Show disk space info (only visible to yourself)
/dfs 					Show disk space info (as public message)
/disks, /di 				Show detailed disk info about all mounted disks (only visible to yourself)
/uptime 					Show uptime info (as public message)
/topic					Show topic
/ctopic					Open link in topic
/ratio, /r					Show ratio in chat (as public message)
/close, /r					Close the current tab

Additional commands for the hub tab: /join <hub-ip>, /ts, /showjoins, /favshowjoins, /close, /userlist, /favorite, /pm <user> [message], /getlist <user>, /removefavorite
```

**Comment by KipourosV** [comment]
Where exactly do you enter those commands?
I mean, I know the existance of this on airdc windows version
But is this implemented here?

Where do you enter /help to get that list?

**Comment by Sopor-** [comment]
I don't know how many of these commands that are possible to use in the Web Client, but until those commands are added into the Web Client it would be nice if the / not get visible in the hubs main chat.
No regular DC client will allow you to start a sentence with a '/' so until those (or some) of the built in commands are added into the Web Client it should show a message that this command is unknown or not allowed.

Right now you can't get any commands from the Web Client, you need to use AirDC in Windows. That was what i did to show you what i meant @KipourosV 

If @maksis add /command tomorrow then this issue will be useless but if he desire to wait (or it will not be added at all) it would be nice to prevent lines that start with a / to be printed in main.

**Comment by Sopor-** [comment]
It would be nice if it was possible to shutdown the client from the WebUI...

AirDC already have this /shutdown command built in so why not add it to the WebUI :)

**Comment by Sopor-** [comment]
Now when i can use `/me` you should prevent the char `/` from getting sent when i only use `/` or if i try some of the other commands. At least some kind of message, Unknown command as i get i AirDC if i enter a / command that is not recognised. If i send `/test` i get this back: `*** Unknown command:  test`
