### ISSUE TITLE
Add name to easy separate the WebUI from each others...

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#111]
It would be nice if it was possible to add a name for my WebUI so i easy can see which WebUI i'm connected to: Kitchen, Living room, My big server or whatever i want... I think you get the point?

I can of course see the address but it is not so easy if i use IP numbers and i can use full screen too and that will make me see no address at all.

There are a lot of space between the AirDC icon and the Home button to place the name.

![picpick-2016 03 03-17 24 40](https://cloud.githubusercontent.com/assets/5789283/13501106/a6fac7b8-e165-11e5-9699-96c977b0c89f.jpg)

**Comment by maksis** [comment]
Maybe hostname/computer name could be shown in the tab header

**Comment by Sopor-** [comment]
Either that or make it possible to manually type whatever i want :)

**Comment by Sopor-** [comment]
This will not make it easier to see what client i'm connected to when you added it there :(
It must be added inside the WebUI.

![picpick-2016 03 17-00 03 03](https://cloud.githubusercontent.com/assets/5789283/13831415/e1cb793c-ebd3-11e5-8328-57d888028c57.jpg)
