### ISSUE TITLE
Can't find alternative sources for files into subdirs.

### ISSUE THREAD

**Issue by YamashitaRen** [airdcpp-web/airdcpp-webclient#112]
If I download a file "myfile", airdcpp will try to find another sources for it.
"myfile" is in a directory "subdir".
If I download the directory "subdir", airdcpp will not find another source for "myfile" (even if one exists).

This bug is annoying when you want to download a huge directory/subdirectory of files which may be individually shared by other peers.

**Comment by maksis** [comment]
> This bug is annoying when you want to download a huge directory/subdirectory of files which may be individually shared by other peers.

Yeah, such cases are problematic when searching for alternates. How big directories are you talking about and why do you consider this to be a bug?

Feature #50 is about allowing more manual control in such cases.

**Comment by YamashitaRen** [comment]
In this case, we're talking about a 2To dir, with many files (videos) shared by other peoples in the hub.

I was surprised by this behavior because in Eiskalt (I ended using it), it automatically finds alternates for theses files.
It can be done in ncdc too, but manually (you have to search for alternates for each file and then add them, whether you're downloading a single file or a file in a dir).

I'm considering it a bug because when I download a dir, I expect airdcpp to find alternates for files in it (and not for the whole dir with its "tree view"). Maybe I shouldn't ~~
The "bigger"/"more complex" the dir, the less likelihood I'll have to find people sharing it as it is. They could have decided to only keep/download a part of it, or to change the internal "tree view"...

Currently it's like "airdcpp will find alternates when you download a file but may fail (and will most likely do to find all of them) when you download a dir". It's a bit disappointing imho...

**Comment by maksis** [comment]
> In this case, we're talking about a 2To dir, with many files (videos) shared by other peoples in the hub.

I'd like to know the file and directory counts (size in bytes doesn't matter in this context) and whether you are using ADC or NMDC hubs. There are already features that would allow more aggressive matching of users' files for complex directory structures but those are disabled by default due to resource usage.

> It can be done in ncdc too, but manually (you have to search for alternates for each file and then add them, whether you're downloading a single file or a file in a dir).

That's feature #50. Manually searches for individual files can't be enabled before the files are listed somewhere. This is still a recent project (API and UI) compared to clients such as Eiskalt and not all features have been implemented.

> I'm considering it a bug because when I download a dir, I expect airdcpp to find alternates for files in it (and not for the whole dir as in its "tree view").

The client performs searches for random individual files, not directories, and tries to pick files from different directories to search for. More information about the search behavior can be found from http://www.airdcpp.net/forum/viewtopic.php?f=4&t=1856

**Comment by YamashitaRen** [comment]
AirDC++ may be young but it's already very good :)
There are 250 directories and 6022 files ! I'm using a NMDC hub.

> Manually searches for individual files can't be enabled before the files are listed somewhere.
I would have guessed that feature https://github.com/airdcpp-web/airdcpp-webclient/issues/50 was about that.

> The client performs searches for random individual files, not directories, and tries to pick files from different directories to search for.
If I understand correctly what you said and how the search behaves, airdcpp is indeed searching for alternates when I download a huge dir ? Oo
So it means that airdcpp is only lacking a mean of showing me that he indeed found alternates ? (which should be feature https://github.com/airdcpp-web/airdcpp-webclient/issues/50)

**Comment by maksis** [comment]
Feature #50 would only allow you to easily search for alternates for individual files. 

If you are downloading a bundle with 250 directories and 6022 files with an unique directory structure, it might be really hard to find sources for all files without performing a huge number of searches. The option that I added in the latest commit should help with that as you can allow the client to match full filelists from users that return hits for any of the searches performed by the client.

**Comment by YamashitaRen** [comment]
Oh, I see...
Can I try it now or should I wait for a release bump ?

**Comment by maksis** [comment]
Actually normal adding of sources on Linux for NMDC directories is broken because of different path separators

**Comment by YamashitaRen** [comment]
So it was indeed a bug...
I'll wait for the fix then.
