### ISSUE TITLE
Speed limiter need a max value

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#113]
The speed limiter values can be set to a very high value. I tried to add nines and suddenly was very high: 1.0000000000000003e+219. It need some kind of limited value.

Max value for AirDC++ is 2147483647 and i do believe that even that is too high.

More then 9999999 are not needed maybe even less is enough?

**Comment by maksis** [comment]
Values like 1.0000000000000003e+219 can't even be saved so that's a limit already. All other numeric fields behave like that as well.

I neither see any issue with setting the limiter to 2147483647 if someone wants to do that.
