### ISSUE TITLE
sfv check does not report missing files

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#114]
I found out I had some folders with missing files.
What I mean is the SFV had 6 files and the directory only had three (which verify correctly).

Shouldn't airdcpp inform of the missing files?

Application version AirDC++w 0.16.5 x86_64 / 0.850
Web UI version 0.16.2
Web UI build date February 8, 2016 11:33 AM

**Comment by maksis** [comment]
Please post all required information as instructed in https://github.com/airdcpp-web/airdcpp-webclient/blob/master/ISSUES.md

**Comment by KipourosV** [comment]
Ok I tried this:

I downloaded a music folder, which SFV checked fine and was added to my share.
Then I remove the bundle from the share, move it out of the incoming folder and into
another shared folder. After deleting half the files in the boundle I initiated a filelist refresh.

airdc reports hashing and verifying the files that exist but doesn't error/warn about the missing files.

**Comment by maksis** [comment]
Scan is performed only for finished bundles

**Comment by KipourosV** [comment]
Is there a way to initiate a full library sfv check which will report missing files and errors?

**Comment by maksis** [comment]
It's not possible at the moment

**Comment by maksis** [comment]
There's going to be an extension for this: https://github.com/maksis/airdcpp-release-validator
