### ISSUE TITLE
Allow user certificates

### ISSUE THREAD

**Issue by sbraz** [airdcpp-web/airdcpp-webclient#115]
The programme shouldn't overwrite user-generated certificates.
I see two ways this can be achieved:
* add a configuration directive to enable/disable certificate generation
* do not regenerate a certificate if the existing one wasn't generated by airdc (I guess the CN and O are special and can be used to detect airdc's own certs)

**Comment by maksis** [comment]
Allowing user to configure a separate certificate for HTTPS might be the best option. I don't see much benefit in using a custom certificate in client-client communication and the client is (possibly) better in keeping the certificate valid. Currently the certificate also contains the client ID which makes reporting of validation errors easier for remote certificates (even though the ID is added only by clients that are based on DC++). Making web server settings configurable from the UI should also be done at some point.....

**Comment by sbraz** [comment]
Containing the ID is also a leak of potentially sensitive information :)
A configuration option would be enough, IMO it's a feature for advanced users who shouldn't be afraid of editing a config file.

**Comment by maksis** [comment]
> Containing the ID is also a leak of potentially sensitive information :)

Sensitive? :p

I'd say that it qualifies well as the common name (as that's what it is).
