### ISSUE TITLE
Bundle names won't fit into the message window

### ISSUE THREAD

**Issue by Sopor** [airdcpp-web/airdcpp-webclient#118]
When a bundle is added to the queue a message will popup in the upper left corner but it will not fit into the window.

![picpick-2016 03 10-21 11 42](https://cloud.githubusercontent.com/assets/5789283/13683135/6adc0058-e705-11e5-9e6b-cd68526a35dc.jpg)

**Comment by maksis** [comment]
The custom popup system should probably be removed in favor of native browser notifications as most major browsers have support for those

**Comment by maksis** [comment]
The custom popup system will stay after all as native notifications can't generally be used without HTTPS (and the inbuilt notifications are actually nice when the UI is not on the background)...
