### ISSUE TITLE
New password (optional)

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#123]
When i edit default user for the webui it will show this window. How can the 'New password' be optional? It sounds really weird for me.

Application version: AirDC++w 1.0.1 x86_64 / 0.850
Web UI version: 1.0.2

![picpick-2016 03 21-17 39 07](https://cloud.githubusercontent.com/assets/5789283/13926500/e4ac78ec-ef8c-11e5-8404-9f78ad074db9.jpg)

**Comment by maksis** [comment]
It means that you can save the dialog without entering a new password. You can also save other dialogs without actually changing anything so I don't see any inconsistencies there.

**Comment by Sopor-** [comment]
Then you need to have "optional" on every line that you don't have to change and as you can see here all other lines are grayed out.
