### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by maksis** [airdcpp-web/airdcpp-webclient#126]
For reference: https://help.github.com/articles/using-keyboard-shortcuts/

Any opinions of what actions should be implemented?

**Comment by Kcchouette** [comment]
You can try to bind control+F with the search page?

Else I don't really use keyboard shortcuts on a website.

**Comment by maksis** [comment]
> You can try to bind control+F with the search page?

That sounds a bit nasty because it would override browser's inbuilt find function. What about Alt+F?

I've also added the following shortcuts for session layouts (not in version 1.3.0):


**Alt + arrow up/down**

Go to previous/next session

**Alt + num (1-9)**

Go to session by index

Shortcuts for opening a new session and closing the current one will be added as well.
