### ISSUE TITLE
Implement Home view

### ISSUE THREAD

**Issue by maksis** [airdcpp-web/airdcpp-webclient#127]
Yeah, the Home view is not meant to stay empty. I've been thinking of making it a summary layout that would possibly have different widgets for commonly used functionality or just for displaying information.

Any suggestions of what should be added there?

**Comment by Sopor-** [comment]
Yeah, that sounds very nice if it was possible to let the user choose from different widgets. Pfsense do have this already and it is a very nice feature.

**Comment by maksis** [comment]
![image](https://cloud.githubusercontent.com/assets/5640804/17705243/62c6579e-63e0-11e6-8861-9e6eac6a2bf0.png)

**Comment by maksis** [comment]
Released in Web UI 1.1.2
