### ISSUE TITLE
Why can't you have context menus in the WebUI?

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#131]
When i'm connected to Google Drive the context menu change so i can copy, move and delete files. Why can't you have the same? Instead of having the web browser original menu it could be like the original AirDC client menus for Windows. Many torrent client have custom context menu so it must be possible to add...

**Comment by Sopor-** [comment]
@maksis Without this, users can't read rules and other functions that you need to have access to. All functions are not always accessible through commands in the main chat.

**Comment by maksis** [comment]
Please comment only the existing report

https://github.com/airdcpp-web/airdcpp-webclient/issues/116
