### ISSUE TITLE
add chat history

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#132]
It would be nice if there was a chat history...

**Comment by maksis** [comment]
Related to resolving of https://bugs.launchpad.net/airdcpp/+bug/1534935

**Comment by sbraz** [comment]
Re-opening the log files is what ncdc does and seems like a reasonable choice :)

**Comment by Kcchouette** [comment]
If you'll implement this enhancement, can you please propose to enable/disable it?

**Comment by maksis** [comment]
@Kcchouette there's an option to set the maximum number of lines to load from log
