### ISSUE TITLE
Can't close a filelist

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#133]
* The user must be offline
* You must to have his filelist open

A message is display: "User offline You will be able to continue browsing when the user comes back online".

But you can't close the filelist.

AirDC++w 0.16.5 x86_64 / 0.850; Web UI:0.16.2

**Comment by infectormp** [comment]
@Kcchouette please update to version 1.0.2 and try reproduce this problem.

**Comment by Kcchouette** [comment]
With AirDC++w 1.0.2 x86_64 / 0.850; Web UI: 1.0.3, it's fixed.
I close this issue. Thanks!
