### ISSUE TITLE
Diacritic symbols

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#137]
I have some files which contain diacritic symbols in their names e.g. _09 - Själ i flamma.flac_ Client can't hash them showing `Error hashing /data/09 - Sjl i flamma.flac: No such file or directory` in events log. Looks like client ignores that symbols and therefore can't hash these files.

**Comment by maksis** [comment]
`The file /home/Downloads/09 - Själ i flamma.flac (3.13 KiB) has finished hashing in 0 second (0 B/s)`

When does your issue happen?

**Comment by maksis** [comment]
And what's the output when you run `locale charmap`

**Comment by acmodeu** [comment]
It happens every time airdcpp rescans the shared folders.
> les@sync:~$ locale charmap
> UTF-8

**Comment by maksis** [comment]
Did you have the client installed also on another computer? Are you able to test it there as well?

**Comment by acmodeu** [comment]
Yeah that's odd. Everything is OK on another pc.

**Comment by acmodeu** [comment]
Ok, I've got some refreshments on my problem:
1. First of all, I was able to compile airdcpp on my problem machine after removing broken dependencies https://github.com/airdcpp-web/airdcpp-webclient/issues/136
2. I made airdcpp running as a daemon via runit supervisor. Here is my run script:

> les@sync:~$ cat /etc/sv/airdcpp/run
> #!/bin/sh
> export USERNAME=les
> export HOME="/home/$USERNAME"
> export AIRDCPP="/usr/local/bin/airdcppd"
> exec 2>&1
> exec chpst -u "$USERNAME" "$AIRDCPP"
3. The problem exists only if i start airdcpp as a daemonized process, then i run it normally files are seen and hashed correctly.

**Comment by maksis** [comment]
Possibly the locale isn't set correctly when running with your script. Related: https://tickets.opscode.com/browse/COOK-4151

**Comment by acmodeu** [comment]
I'm not sure I understand what I should do :)

**Comment by acmodeu** [comment]
Is there other way to daemonize the process?

**Comment by maksis** [comment]
Run `airdcppd -h` to see available options

**Comment by acmodeu** [comment]
Problem gone with moving to Daemon.

**Comment by acmodeu** [comment]
Strange thing though: when daemon is autostarting at boot, the problem with symbols exists but after stopping & starting daemon manually it the problem dissapears.

**Comment by maksis** [comment]
How do you start the daemon?

**Comment by acmodeu** [comment]
I'm not sure I understand the question but I can describe how I managed to set it. I read [this article](http://blog.terminal.com/using-daemon-to-daemonize-your-programs/) and used given daemonize.sh script to create a daemon: `./daemonize.sh airdcpp /usr/local/bin/airdcppd`. Then I inserted some corrections to be able to run daemon as user, set config directory and pid file location. Then I checked with chkconfig that it will be running on startup. That's all.

> les@sync:~$ sudo chkconfig airdcpp
> airdcpp  on

Here is /etc/init.d/airdcpp script:
[airdcpp.zip](https://github.com/airdcpp-web/airdcpp-webclient/files/214530/airdcpp.zip)

Thank you.

**Comment by acmodeu** [comment]
After upgrading to Web UI version 1.0.5 the problem with hashing files with diacritic symbols exists no matter I start airdcpp via daemon or not.

**Comment by maksis** [comment]
Open the file `airdcppd/Client.cpp` and find this line:

```auto webResources = Util::getStartupParam("--web-resources");```

Add the following line before it:

```
LogManager::getInstance()->message("Current system encoding: " + Text::systemCharset, LogMessage::SEV_INFO);
```

Compile and check the encoding from the events page after startup.

**Comment by acmodeu** [comment]
> Current system encoding: ANSI_X3.4-1968

**Comment by maksis** [comment]
And you started the client by running `airdcppd`? Does `locale charmap` still return UTF-8?

**Comment by acmodeu** [comment]
> les@sync:~$ locale charmap
> ANSI_X3.4-1968

After adding
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
to .bashrc and .profile i get 

> les@sync:~$ locale charmap
> UTF-8

And we are back to here: https://github.com/airdcpp-web/airdcpp-webclient/issues/137#issuecomment-208567243
Autostarted airdcppd returnes _Current system encoding: ANSI_X3.4-1968_ in console.

**Comment by maksis** [comment]
Do you have those locales generated when running `dpkg-reconfigure locales` and what's the default locale it gives?

Have you tried to set the locales also from you startup script?

**Comment by acmodeu** [comment]
Sure!
![default](https://cloud.githubusercontent.com/assets/17564574/14847221/1fcf4580-0c70-11e6-9993-a507ce0ec96d.JPG)

That great! I added those 3 lines to the start script and finally made it work correctly. Thanks for the support! :)

**Comment by maksis** [comment]
Did you also check the default locale from the next configuration page?

**Comment by acmodeu** [comment]
Yes, I did.
![default](https://cloud.githubusercontent.com/assets/17564574/14847351/d9b56074-0c70-11e6-9d1c-0b6c61681588.JPG)

**Comment by maksis** [comment]
Ok, so the startup script just didn't use the default locale. 

I'll add a warning anyway that is shown if the locale isn't set.
