### ISSUE TITLE
Question: How do Dupes and Favorites work?

### ISSUE THREAD

**Issue by Dhalkar** [airdcpp-web/airdcpp-webclient#138]
When you click "download to" two of the categories you can choose between are Dupes and Favorites, both says "No paths to display" for me.

First question: What are "Dupes" in this context?

Second question: How do you add paths to the Favorites category?

**Comment by maksis** [comment]
1. Dupes will show matching local paths for shared/queued items (colored ones) to make it easier to queue new content to existing directories (or alternatively just add new sources)
2. You can't add those at the moment
