### ISSUE TITLE
How do i get started with airdc web?

### ISSUE THREAD

**Issue by JamesSawyer** [airdcpp-web/airdcpp-webclient#140]
Hello, i just upgraded to AirDc 3.10 b and saw that you can access it from the web. But how do i get started with that? Can i only do that if im a programmer o a "coder" which i am not. I only wanna manage my client via a web browser if i understand it correctly. But i need help doing this.

What do i need do to access AirDc remotely and therefore managing it?

Didnt no where else do post and ask this...the solution im sure is here but im just not that good to figure it out on my own

**Comment by maksis** [comment]
Go to Settings -> Web server. Add a login account and start the server. After that you can access the client from http://SERVER_IP:5600

Yeah, I should add that information somewhere.

**Comment by maksis** [comment]
I've also updated the [forum post](http://www.airdcpp.net/forum/viewtopic.php?f=4&t=4334&p=8616#p8616) with instructions.

**Comment by JamesSawyer** [comment]
Thx for replying so fast maksis and for making all this possible. Just a quick question, i've followed your instructions but when i try to go to http://SERVER_IP:5600, it says Unable to find SERVER_IPS DNS server address

Am i doing something wrong? i have created a login account and it says that the web server is running

**Comment by maksis** [comment]
Did you replace SERVER_IP with your own IP address? Use http://localhost:5600 when connecting locally.

**Comment by JamesSawyer** [comment]
Yeah, so now its working from the same computer beautifully=)...but im still a little lost if i wanna access it from lets say my mobile, shall i type http://myip:5600 or how do you mean? 

Sorry if im a little slow on this

**Comment by maksis** [comment]
If you are accessing the client within the local network, you can use the name of your computer as IP address or alternatively get the actual IP with [these instructions](http://www.groovypost.com/howto/microsoft/windows-7/find-your-local-ip-address-windows-7-cmd/).

If you want to access the client from internet, you must use your [public IP address](http://www.whatismypublicip.com/) (and if you have a router/firewall, you must ensure that port 5600 is forwarded properly).

**Comment by JamesSawyer** [comment]
Ah,ok thx so much...now im with you=)

Thx for your instructions and for clarifying everything for a rookie like myself...again thx for all your work on this and AirDc and making this possible, kudos and have a nice day maksis because now its working like a charm:)

**Comment by maksis** [comment]
Great!
