### ISSUE TITLE
Crashes when parsing JSON (ARM)

### ISSUE THREAD

**Issue by bondde** [airdcpp-web/airdcpp-webclient#141]
When trying to login, airdcppd crashes and throws exception.
Platform is ODROID C (arm7) running ARCH 3.10.96-3 kernel
Reference: [AirDC++ Forum](http://www.airdcpp.net/forum/viewtopic.php?f=7&t=4345)

GDB log file:
[gdb-airdcppd.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/215611/gdb-airdcppd.txt)

**Comment by maksis** [comment]
The log suggests that you don't have the latest version of JSON. Are you sure that the file was replaced and that the client was compiled again after that (including `make install`)?

ps. the log file contains your login details, if that matters to you

**Comment by bondde** [comment]
That might be possible it is compiled with old json.hpp. When clang failed I did rm -rf airdcpp folder and cloned it from git and propably forgot to download newer version again.

Compiling takes about 5 hours on odroid so I leave it compiling over night and try to post results at morning.

I changed login details on log file so no worries.

**Comment by maksis** [comment]
Here's a quick test:

1. Save the code below as `json_test.cpp` and put https://raw.githubusercontent.com/nlohmann/json/develop/src/json.hpp in the same directory
2. Run `g++ -std=c++11 json_parse.cpp && ./a.out` and see if you get a segmentation fault

````
#include "json.hpp"

int main(void)
{
    const std::string str = "{ \"test\": \"succeeded\" }";
    const auto json = nlohmann::json::parse(str);
    std::cout << json.dump() << std::endl;
    return 0;
}
```

No need to post more crash logs from the client if the test fails

**Comment by bondde** [comment]
`{"test":"succeeded"}`

Here's gdb output with new json.hpp if it helps. 
[gdb-airdcppd.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/216399/gdb-airdcppd.txt)

**Comment by maksis** [comment]
Will this crash?

```
#include "json.hpp"

int main(void)
{
    const std::string str = R"({
        "path": "session/v0/auth",
        "method": "POST",
        "data": {
            "username": "qwerty", 
            "password": "123456",
            "user_session" :true
        }, 
        "callback_id": 1
    })";
    
    const auto json = nlohmann::json::parse(str);
    std::cout << json.dump(true) << std::endl;
    return 0;
}
```

**Comment by bondde** [comment]
No crash

```
$ ./a.out 
{
 "callback_id": 1,
 "data": {
  "password": "123456",
  "user_session": true,
  "username": "qwerty"
 },
 "method": "POST",
 "path": "session/v0/auth"
}

```

**Comment by maksis** [comment]
````
#include "json.hpp"

int main(void)
{
    const std::string str = "{\"path\":\"session/v0/auth\",\"method\":\"POST\",\"data\":{\"username\":\"qwerty\",\"password\":\"123456\",\"user_session\":true},\"callback_id\":1}";
    
    auto json = nlohmann::json::parse(str);
    std::cout << json.dump(true) << std::endl;
    return 0;
}
```

Run with

```
g++ -fPIC  -std=c++0x -pipe -Wformat -Werror=format-security -fpermissive -O2 -g -DNDEBUG -D_REENTRANT json_parse.cpp && ./a.out
```

**Comment by bondde** [comment]
It works
```
$ ./a.out 
{
 "callback_id": 1,
 "data": {
  "password": "123456",
  "user_session": true,
  "username": "qwerty"
 },
 "method": "POST",
 "path": "session/v0/auth"
}
```

**Comment by maksis** [comment]
Did you also use all parameters when compiling?

Not being able to reproduce the issue with a standalone example makes it more difficult to solve (especially when I'm unable test it myself).

You could try compiling the client again with cmake run with extra parameters (that will disable optimizations):

`cmake -DCMAKE_BUILD_TYPE:STRING=Debug .`

If it still crashes, you could try compiling older version:

0.16.4: `git checkout 2d5954f`
0.9: `git checkout 9a546d2`

Those versions have other issues on ARM systems and they will possibly crash after login, but at least you can see if the authentication request is parsed correctly.

**Comment by bondde** [comment]
> Did you also use all parameters when compiling?

Yes, I did use parameters you provided.

Compiled with `cmake -DCMAKE_BUILD_TYPE:STRING=Debug .` & [https://raw.githubusercontent.com/nlohmann/json/develop/src/json.hpp](https://raw.githubusercontent.com/nlohmann/json/develop/src/json.hpp) and client works fine, no crashes anymore.
Just wondering what those `Thrown: No such file or directory` messages are.
```
Thrown: No such file or directory
Starting.
.
Loading Hash database
Loading Download queue
Thrown: No such file or directory
Loading Shared files
Loading Country information
Starting web server.
AirDC++w 1.0.2 running, press ctrl-c to exit...
HTTP port: 5600, HTTPS port: 0
```

**Comment by maksis** [comment]
I haven't seen such message before.

What's your exact GCC version? `gcc -v`

**Comment by bondde** [comment]
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/armv7l-unknown-linux-gnueabihf/5.3.0/lto-wrapper
Target: armv7l-unknown-linux-gnueabihf
Configured with: /build/gcc/src/gcc-5-20160209/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --host=armv7l-unknown-linux-gnueabihf --build=armv7l-unknown-linux-gnueabihf --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16
Thread model: posix
gcc version 5.3.0 (GCC)
```

**Comment by maksis** [comment]
Could you also test with the original JSON from the client repository, just to be sure that it works as well? I'm not going to update the JSON soon as the latest version can't be compiled with GCC 4.8 (that is used by Ubuntu 14.04).

If you still feel like doing more compiling, you could also try it with

`cmake -DCMAKE_BUILD_TYPE:STRING=Release .`

**Comment by maksis** [comment]
> Just wondering what those Thrown: No such file or directory messages are.

Those are actually debug messages that don't exist in normal builds. Running a debug build isn't the best thing to do as the performance can be poor due to extra runtime checks.

I was able to get a bit similar crash when parsing authentication data but only when I compiled a debug build with GCC 5.3. I've done some fixes after testing the application with memory error detector and the crash won't happen anymore (which may also be a coincident). 

You could clone a fresh repository and switch to develop branch by running `git checkout develop` before compiling to get the latest fixes. Compile it normally without any extra options or modifications.

**Comment by bondde** [comment]
Just tested `cmake -DCMAKE_BUILD_TYPE:STRING=Debug .` with "old" json.hpp and it works too.

`cmake -DCMAKE_BUILD_TYPE:STRING=Release .` Did crash server on login.

Will try develop branch next.

**Comment by bondde** [comment]
No luck, development branch throws [exception](https://github.com/airdcpp-web/airdcpp-webclient/files/226700/exception.txt) on login.

**Comment by maksis** [comment]
It's probably best to wait for GCC 6.1 and test a new regular build when it's available. Testing a non-debug build without optimizations might also be interesting but that doesn't seem to be possible without build script modifications.

If someone else is experiencing the same issue, please post a comment.

**Comment by maksis** [comment]
Seems like GCC 6.1 is now available on Arch: https://www.archlinux.org/packages/core/x86_64/gcc/

**Comment by bondde** [comment]
Tested master branch & updated json.hpp with GCC 6.1 and [crashing](https://github.com/airdcpp-web/airdcpp-webclient/files/264032/gdb.txt) still occurs. Debug build works fine as before.

**Comment by maksis** [comment]
Hmm... the actual crash is different though. It must be a memory management issue.

**Comment by maksis** [comment]
Could you install Valgrind and run the program with `valgrind airdcppd`? Crash the app and get the output. Using the develop branch with an unmodified json.hpp is recommended.

**Comment by bondde** [comment]
[Here](https://github.com/airdcpp-web/airdcpp-webclient/files/274871/airdcpdd.txt) you go.

**Comment by maksis** [comment]
Oh, that's not helpful at all because all the reported warnings are from OpenSSL. Did it stop reporting even before you logged in?

Is your system fully up to date?

**Comment by bondde** [comment]
Yes, I normally update packets once a week or something. Last time was just before installing valgrind.

That conditional jump spam starts right away when I hit login button.

**Comment by maksis** [comment]
Did you login via HTTPS?

**Comment by bondde** [comment]
No, HTTPS is disabled.

**Comment by maksis** [comment]
I've done some testing on Raspberry Pi (@NEMO1911) and this really seems to have something to do with [code optimizations](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) done by the compiler. 

GCC seems to crash when it tries to allocate memory:

`AddressSanitizer failed to allocate 0x76f99000 (1996066816) bytes of LargeMmapAllocator (errno: 12)`

Allocating almost 2 gigabytes of memory can't certainly end up very well.

I've also tested the client when compiled with clang and it works a bit better as level 1 optimizations won't cause any crashes. Using the regular level 2 optimizations crashes the client instantly on startup when setting up API endpoints (SIGBUS). Unfortunately the client can't be compiled on Linux using clang without extra hacks due to library/system header conflicts. Clang works fine on operating systems that use it as a default compiler (such as FreeBSD and OS X).

I also did some testing with special optimization options, and noticed that the typical crash doesn't happen if the code is optimized for size. I'll make cmake to use that optimization level by default on ARM systems for now.

**Comment by maksis** [comment]
@bondde: I've commited the change to the develop branch. If this is still relevant to you, please try if it's working for you as well (clean build without using the debug config).

**Comment by bondde** [comment]
Yup, now it's working. Tested dev branch and problem exists no more.

**Comment by bondde** [comment]
Pls add "armv6l" also to exception list. Otherwise older raspberries (I've got RPi 1 B-model) wouldn't be included to this workaround.

**Comment by maksis** [comment]
> Pls add "armv6l" also to exception list. Otherwise older raspberries (I've got RPi 1 B-model) wouldn't be included to this workaround.

Done

**Comment by NEMO1911** [comment]
seams to be working this far, only thing is that i still get the following errors in the terminal when connecting, but that might be related to another topic.

`[error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)`

Great work!!

**Comment by maksis** [comment]
> [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)

Yes, those definitely aren't related to this issue (and it doesn't seem like a client issue at all):

https://github.com/zaphoyd/websocketpp/issues/463
https://github.com/zaphoyd/websocketpp/issues/282

**Comment by NEMO1911** [comment]
I see then i know what it is, thanks!
