### ISSUE TITLE
Browse share does from search results does not open the right folder when share is already open

### ISSUE THREAD

**Issue by sbraz** [airdcpp-web/airdcpp-webclient#143]
When clicking the "Browse share" button on a search result, the user should be taken to the relevant folder from the user share. However, if I'm already browsing this user's share at a different location, I'm not taken to the location of my search results.
Web UI: 1.0.4
Server: 1.0.2
It's a little bit hard to reproduce since this rarely happens.

**Comment by maksis** [comment]
Did you check API communication from the browser console and were there any errors in the transfer view?

**Comment by maksis** [comment]
This should be fixed in the develop branch already

https://github.com/airdcpp/airgit/commit/b7e04b98d4035bc3c856b633e6522e62668ecdf3
