### ISSUE TITLE
Choose users whose share to browse from search results

### ISSUE THREAD

**Issue by sbraz** [airdcpp-web/airdcpp-webclient#146]
At the moment, if I click "browse share" from the search results window, one user will be chosen and I have no control over it. If I want to browse the share of another user who also has the file I'm looking for, it is not possible.
I would like an option to expand the list of users sharing the file so that I can chose whose share to browse.

**Comment by maksis** [comment]
I've added a new dialog for search results. Please try the develop branch and see if there is something to improve.
