### ISSUE TITLE
I can only have one share profile open at the same time in the file list viewer...

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#147]
When i want to browse my own share i can only have one open at the same time. When i select another share profile the previous file list will close. Why have several browse buttons if only one can be open? Then it should be easier with a drop down menu so i can easy switch share profiles instead of open and close windows as i have to do now.
In this picture you can see there is only one share profile in the current sessions even if i have opened the other share profiles right before i opened the default one (the one i have open in the picture).

If i open the file list viewer and it is empty i can choose share `Browse own share...` but if i have another file list open this will go away. It is only visible when all file lists are closed.

It should be possible to easy switch share profile if it isn't possible to have all share profiles opened at the same time (AirDC have a drop down menu in my own share).

![picpick-2016 05 13-17 05 11](https://cloud.githubusercontent.com/assets/5789283/15253248/c960bd0e-1931-11e6-823a-8fe7843efc10.jpg)

Application version: AirDC++ 3.10b2-31-g5c728 x86-64 / 0.850
Web UI version: 1.0.5

**Comment by maksis** [comment]
Clicking on another browse button should update the filelist to use another share profile so you don't have to close old ones. You can always choose to browse your own share by going to "Open new..." as it will also update your current filelist session. I wouldn't want to add more dropdowns there.
