### ISSUE TITLE
Nothing happen when i press Open new...

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#148]
In the file list viewer there is a `Open new` but if no file lists are open this `Open new` have no function.  Shouldn't this be grayed out or something if it have no function?

![picpick-2016 05 13-18 08 15](https://cloud.githubusercontent.com/assets/5789283/15254285/4e4e19a4-1936-11e6-8c8e-4b4054de82e2.jpg)

**Comment by maksis** [comment]
Applications are full of menu items that have no effect if they are active already
