### ISSUE TITLE
airdcppd hangs nothing is updating in the webui

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#149]
Application version: AirDC++w 1.0.2-24-g9216 x86_64 / 0.850
Web UI version: 1.0.5
Web UI build date: April 19, 2016 8:44 AM

When clicking around in the webui nothing is updating, "Loading form data" is visible.

When exiting airdcppd was not able to stop as normal with Ctrl+C had to do kill -9 <pid>
Before that i did a <(gdb) thread apply all bt full> visible below

^C[2016-05-14 07:11:18] [info] Error getting remote endpoint: system:9 (Bad file descriptor)
[2016-05-14 07:11:18] [fail] WebSocket Connection Unknown - "" - 0 websocketpp:26 Operation canceled
[2016-05-14 07:11:18] [info] asio async_shutdown error: system:9 (Bad file descriptor)
[2016-05-14 07:11:18] [info] handle_accept error: Operation canceled
[2016-05-14 07:11:18] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
[2016-05-14 07:11:18] [info] Error getting remote endpoint: system:9 (Bad file descriptor)
[2016-05-14 07:11:18] [fail] WebSocket Connection Unknown - "" - 0 websocketpp:26 Operation canceled
[2016-05-14 07:11:18] [info] handle_accept error: Operation canceled
[2016-05-14 07:11:18] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
[2016-05-14 07:11:18] [info] asio async_shutdown error: asio.ssl:336462100 (uninitialized)
[2016-05-14 07:11:18] [info] handle_read_frame error: websocketpp.transport:10 (A transport action was requested after shutdown)
[2016-05-14 07:11:18] [disconnect] Disconnect close local:[1006,A transport action was requested after shutdown] remote:[1001,Shutting down]

(gdb) thread apply all bt full

Thread 21 (Thread 0x7fb560215700 (LWP 72)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007fb565c1087d in dcpp::Semaphore::wait (this=0x6d74b8) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/Semaphore.h:62
No locals.
#2  dcpp::DispatcherQueue::run (this=0x6d7448) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/DispatcherQueue.h:73
No locals.
#3  0x00007fb565ce76ba in dcpp::Thread::starter (p=<optimized out>) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/Thread.h:125
        t = <optimized out>
#4  0x00007fb5658666aa in start_thread (arg=0x7fb560215700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb560215700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140416978605824, 378655272230269850, 0, 140726513971471, 140416978606528, 0, -420100628038208614, -420088234148154470}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007fb564744eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 20 (Thread 0x7fb55fa14700 (LWP 73)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007fb565c1087d in dcpp::Semaphore::wait (this=0x6dab00) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/Semaphore.h:62
No locals.
#2  dcpp::DispatcherQueue::run (this=0x6daa90) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/DispatcherQueue.h:73
No locals.
#3  0x00007fb565ce76ba in dcpp::Thread::starter (p=<optimized out>) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/Thread.h:125
        t = <optimized out>
#4  0x00007fb5658666aa in start_thread (arg=0x7fb55fa14700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb55fa14700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140416970213120, 378655272230269850, 0, 140726513971519, 140416970213824, 6846960, -419960988450868326, -420088234148154470}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007fb564744eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 19 (Thread 0x7fb55f213700 (LWP 74)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007fb565c1087d in dcpp::Semaphore::wait (this=0x6e05e8) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/Semaphore.h:62
No locals.
#2  dcpp::DispatcherQueue::run (this=0x6e0578) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/DispatcherQueue.h:73
No locals.
#3  0x00007fb565ce76ba in dcpp::Thread::starter (p=<optimized out>) at /home/airdc/airdcpp-webclient/airdcpp-core/airdcpp/Thread.h:125
        t = <optimized out>
#4  0x00007fb5658666aa in start_thread (arg=0x7fb55f213700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb55f213700
---Type <return> to continue, or q <return> to quit---q
Quit

**Comment by maksis** [comment]
The gdb log can't be used because you quit instead of listing all the threads. You are also using an old version so it's likely that this hang is fixed in version 1.0.3 already.
