### ISSUE TITLE
apache proxy webUI

### ISSUE THREAD

**Issue by mzuenni** [airdcpp-web/airdcpp-webclient#150]
hello i tried apache to proxy the web ui from port 5601 to /secure/airdcpp
i am using this command in my apache site conf to do so:
`ProxyRequests Off
 ProxyPreserveHost on
 ProxyPass /secure/airdcpp http://localhost:5601/
 ProxyPassReverse /secure/airdcpp http://localhost:5601/`
but all i get is a blank page... 
the reason seems to be the getBasePath method in index.html if i change the method to just
return "/secure/airdcpp/" the login form is displayed correct but if i try to use it it says could not connect to server
is there something else i need to edit or something i need to change in my apache conf?

**Comment by maksis** [comment]
Yeah, the current version of getBasePath won't detect nested directories.

Did you check the [nginx example](https://airdcpp-web.github.io/docs/advanced/nginx-setup.html)? Most likely you'll need additional configuration for proxying websockets. Maybe this one will help: https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

**Comment by mzuenni** [comment]
hey yes i have read it an seen the magic nginx things 
`with proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";`
but i dont know how to do exactly that with apache...

i already have enabled the proxy_wstunnel modul but i dont know what i need to proxy for the websocket connection
does the webUI connects the websocket to a special adress?
(the example says it should be something like that :
`ProxyPass <dir you web sockets connect to>  ws://localhost:5601`)

**Comment by maksis** [comment]
Web UI will connect to the base URL: https://github.com/airdcpp-web/airdcpp-webui/blob/master/src/services/SocketService.js#L5

**Comment by mzuenni** [comment]
hm thats a problem...
i cant just write
`ProxyPass /secure/airdcpp http://localhost:5601/
 ProxyPassReverse /secure/airdcpp http://localhost:5601/
 ProxyPass /secure/airdcpp ws://localhost:5601/
 ProxyPassReverse /secure/airdcpp ws://localhost:5601/`
because they are obviously conflicting...

**Comment by maksis** [comment]
Are you able to find another solution?

http://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel

**Comment by mzuenni** [comment]
yes the last location seems to work :D
in sites-avaible:
`			<Proxy *>
  				Order deny,allow
  				Allow from all
			</Proxy>
			ProxyVia on
			ProxyRequests Off
			ProxyPreserveHost on
			<LocationMatch /secure/airdcpp/>
				<ifmodule mod_rewrite.c>
					RewriteEngine On
					RewriteCond %{HTTP:Upgrade} =websocket
					RewriteRule /secure/airdcpp/(.*)           ws://localhost:5601/$1 [P,L]
					RewriteCond %{HTTP:Upgrade} !=websocket
					RewriteRule /secure/airdcpp/(.*)           http://localhost:5601/$1 [P,L]
					ProxyPassReverse http://localhost:5601/
				</ifmodule>
			</LocationMatch>`
and my modification in index.html:
`function getBasePath(data) {
	return "my sub dir";
 }`

thanks for the quick help :)
