### ISSUE TITLE
Message seen will be triggered without activating the PM window

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#153]
If connected with CCPM the `Message seen` will be sent to the other client if the PM window is opened in the Web Client. You don't even need to activate the Window as you have to do in AirDC.

The Web Client will not show `Message seen` or when the other client is typing or when the user have closed the window.

**Comment by maksis** [comment]
Fixed by https://github.com/airdcpp/airgit/commit/0c475662542dc003e1f0af3da37e2ccd52c51b10
