### ISSUE TITLE
Restrict download locations per user

### ISSUE THREAD

**Issue by larsvanderplank** [airdcpp-web/airdcpp-webclient#157]
Would be nice to be able to restrict the download folder(s) a web user can download to.

**Comment by maksis** [comment]
What's your use case and how do you want to restrict them? Do you want to select specific shared directories that the user can use as a download target or something else?

**Comment by larsvanderplank** [comment]
I'd like to give a restricted account to a friend so he can only search and download. But I only want him to download to his own personal (shared) folder. When downloading completes he can fetch the files using FTP or whatever.

**Comment by maksis** [comment]
Do you just want to prevent the user from accidentally choosing a wrong download directory? If there is no need to have actual restrictions, support for user-specific default download directory could be implemented instead.

**Comment by larsvanderplank** [comment]
A user specific default download location is nice. Perhaps under Permissions the Download checkbox can be replaced by two checkboxes: Download to default folder / Download to all available folders. Or something similar. 
I don't want users browsing my entire PC (they can using Download To --> Browse), so I think the need for an actual restriction is there.

**Comment by maksis** [comment]
So the user must also be able to browse the filesystem instead of downloading everything under the default directory?

**Comment by larsvanderplank** [comment]
No, the opposite. I want to be able to create a user who can only download to one location, the User default download folder. I don't want him to have any option to download to another folder.

**Comment by maksis** [comment]
> I don't want users browsing my entire PC (they can using Download To --> Browse), so I think the need for an actual restriction is there.

> I want to be able to create a user who can only download to one location, the User default download folder. I don't want him to have any option to download to another folder.

There's a separate permission for browsing the local filesystem. Does the user need that permission at all or can he download everything directly under the default directory without even using the "Download to..." option?

Letting users to choose from a list of custom locations without browsing the filesystem would also be possible with favorite download directories but there is no support for adding those yet.

**Comment by larsvanderplank** [comment]
He should download everything under the default directory, there should be no "Download to..." option available at all for this user.

btw: Sorry, I didn't see the Permission "Local filesystem: Browse" at first, thanks for pointing that out.

**Comment by maksis** [comment]
The easiest solution to implement would be to allow setting a global default download location similar to `/home/%[username]/Downloads/` where `%[username]` would be replaced with the name of the web user who initiates the download.

**Comment by larsvanderplank** [comment]
Sounds great. That in combination with the ability to remove the "Download to..." option would fulfill this feature request.

**Comment by maksis** [comment]
> with the ability to remove the "Download to..." option

Is this really needed if the user doesn't have the permission to browse the local filesystem? I don't want to have too many permission options.

**Comment by larsvanderplank** [comment]
Would be nice because you could keep track of the files that this user downloads.

**Comment by maksis** [comment]
Version 1.1.0 will support `%[username]` in target paths.

I don't see much point in having users intentionally choosing random download locations if they have been advised to use the default download option so I'm not planning to implements checks for that unless issues arise.
