### ISSUE TITLE
404 not found - Nginx conf

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#160]
Hello
I've tried to do https://airdcpp-web.github.io/docs/advanced/nginx-setup.html but I have a 
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
for https://URL/js/main.entry.js

My url for airdcpp is https://URL/dcc/; so I don't really understand why it tries URL/js instead of URL/dcc/js (which seems to work!)

**My conf:**
Application version AirDC++w 1.0.3 x86_64 / 0.850
Web UI version 1.0.6

Thanks

**Comment by maksis** [comment]
From the example config file:

```
	# You may change the location path but it must always start with "airdcpp".
	# This is because the UI uses URLs for routing so it must be able to determine
	# the base directory from the URL.
```

The location you are using is `dcc`, which doesn't start with `airdcpp`, right?

**Comment by Kcchouette** [comment]
Indeed, sorry, closing the issue.
Thank you very much.
