### ISSUE TITLE
Download and upload column should change place

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#162]
When you type your speed you always write your download speed first and then your upload speed like this 250/100, so it would be more logical if the download column was before the upload column.

**Comment by Kcchouette** [comment]
@maksis this issue is resolve, isn't it?
![screenshot_2018-05-17 - airdc web client](https://user-images.githubusercontent.com/3000936/40165165-97f79306-59bb-11e8-87b3-22720da5db64.png)
