### ISSUE TITLE
The speed limiter will not be visible in the description...

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#163]
When changing the upload speed (speed limiter) in AirDC++ this will be announced in the description. If i limit the upload speed in the Web Client it will not be announced in the description.

**Comment by maksis** [comment]
The current behavior is actually consistent with other clients (AirDC++ 3.10 included). If have further comments regarding this, please use the forum as there's a discussion thread about the bandwidth limiter already.
