### ISSUE TITLE
Auto search

### ISSUE THREAD

**Issue by jahrock** [airdcpp-web/airdcpp-webclient#164]
Under Windows i made usage of the "auto search" functionality very often.
So far this tab didn't made it into the WebClient.

I wish to see this feature included in future versions of the WebClient.
Further it would be nice to see an "add to auto search" button on the search result page in case there was no exact match...

**Comment by maksis** [comment]
I'm not currently planning to implement that feature in the web client. I don't need the feature myself and I don't consider it to be one of the core client features either.

I've written an example script demonstrating similar functionality though: https://github.com/airdcpp-web/airdcpp-apisocket-js/blob/master/examples/AutoDownloader.js

**Comment by vestingz** [comment]
How do i deploy this script with AirDC++w?

**Comment by whispy** [comment]
I just spent a good 15 minutes looking around the web client for the autosearch functionality. It's too bad that it is inaccessible from the web UI, as it is useful for users who share files on a regular schedule.

@maksis, your AutoDownloader.js link 404s. Do you have an updated version of that file? Perhaps one that works with the recent extension functionality in the web UI?

**Comment by maksis** [comment]
Yeah, the example script is now an extension. 

Examples: https://github.com/airdcpp-web/airdcpp-extension-js/tree/master/examples
Instructions: https://github.com/airdcpp-web/airdcpp-extension-js#running-the-examples

**Comment by piratthefan** [comment]
Hi Maksis or somebody that can help me.
First iam new at this so i can be slow sometimes 
I was trying to install extensions but i run in to some trouble.
1. npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

2.  nodejs run_example.js airdcpp-chat-filter.js
module.js:472
    throw err;
    ^

Error: Cannot find module '/home/pirat/sources/airdcpp-extension-js/examples/run_example.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

So what did i do wrong ;) 
And i changed settings.js username, password and the port to 5601
But can the extension(s) run on 5601?
Thx in advance

**Comment by maksis** [comment]
> nodejs run_example.js airdcpp-chat-filter.js

That doesn't look correct.

> 5. Run the wanted example with `node run_example.js example_name_without_file_extension` (such as `node run_example.js airdcpp-chat-filter`). Debian/Ubuntu users may have to use the command `nodejs` instead of `node`.

**Comment by maksis** [comment]
... and the run_example.js file is located in the repository root, not inside the examples folder

For further questions about the example scripts, please use the issue tracker at https://github.com/airdcpp-web/airdcpp-extension-js/issues

**Comment by piratthefan** [comment]
Thx i will do that ;)
