### ISSUE TITLE
Program stall???

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#165]
Every so often I notice this, airdcppd gets stuck using 100% 
of one core and the web ui is unresponsive... (see attached image)

There is no specific time or action that initiates this behaviour
and there is no specific time or action that ends it...

Regards
Billy

![image](https://cloud.githubusercontent.com/assets/16351880/16367317/6221c8e0-3c22-11e6-987c-c6bfd9614802.png)

**Comment by maksis** [comment]
Which version are you using? You could follow the instructions for client freezes: https://airdcpp-web.github.io/docs/general/reporting-issues.html

**Comment by KipourosV** [comment]
Application version
AirDC++w 1.0.4 x86_64 / 0.851
Web UI version
1.0.6

**Comment by KipourosV** [comment]
Will try the instructions and let you know...

**Comment by maksis** [comment]
How often does this happen? I was planning to make a new release.

**Comment by KipourosV** [comment]
Really often... at least once in an hour, and I also think it has to do with hashing...
Will look into it more and let you know... (didn't have time to follow the freeze instructions)

**Comment by maksis** [comment]
Hmm, so does the UI become totally inaccessible? And is the client restored to a normal state after all? It's totally normal that the client consumes 100% of the CPU while hashing, especially if you have a slow CPU.

**Comment by maksis** [comment]
Note that you may also limit the maximum hashing speed from Settings -> Sharing -> Hashing

**Comment by KipourosV** [comment]
The UI is not fully unresponsive, it just wont refresh properly...
The menus on top work, but the content won't refresh until after some time
Also this happens while not hashing... (like right now)
It uses 100% of 1 core. Normally, hashing or not, it uses some percentage from all cores...


This is just now... it was stuck, now it's working again normally (not hashing):
![image](https://cloud.githubusercontent.com/assets/16351880/16382302/90e15638-3c80-11e6-913b-8d6c0e3281b7.png)


And this after I press refresh on the shares (notice that last peak):
![image](https://cloud.githubusercontent.com/assets/16351880/16382379/d24ba9d4-3c80-11e6-87bb-10dd6f3591e3.png)

**Comment by KipourosV** [comment]
I'll wait for the "stall" to happen again, and I'll try the gdb instructions...

**Comment by KipourosV** [comment]
root@tank:~# cat ~/.airdc++/airdcppd.pid
6root@tank:~# gdb
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) attach 6
Attaching to process 6
ptrace: No such process.
(gdb)

**Comment by KipourosV** [comment]
![image](https://cloud.githubusercontent.com/assets/16351880/16383289/cd27279a-3c84-11e6-9cb4-801cdc0b9a1b.png)

**Comment by maksis** [comment]
Are you able to confirm the process ID by using other tools?

**Comment by maksis** [comment]
And are you running the client as root...?

**Comment by KipourosV** [comment]
root@tank:/# ps -ef | grep airdcpp
root     26740 26711  0 Jun26 ?        00:00:00 /bin/sh -c airdcppd
root     26756 26740 80 Jun26 ?        23:48:40 airdcppd
root     31849 22160  0 17:43 pts/0    00:00:00 grep airdcpp


Running as root in a docker container...

**Comment by KipourosV** [comment]
root@tank:/# ps aux | grep airdcpp
root      1708  0.0  0.0   7852  1952 pts/0    R+   17:45   0:00 grep airdcpp
root     26740  0.0  0.0   4476    12 ?        Ss   Jun26   0:00 /bin/sh -c airdcppd
root     26756 80.8  9.2 3021908 754088 ?      Sl   Jun26 1430:38 airdcppd

**Comment by KipourosV** [comment]
![image](https://cloud.githubusercontent.com/assets/16351880/16383778/c4191d64-3c86-11e6-89a0-d693f49a953f.png)

**Comment by maksis** [comment]
Does it work with the correct PID? Could you also validate the content of ~/.airdc++/airdcppd.pid so that the number wasn't just cut?

**Comment by maksis** [comment]
Hmm, and are you using a custom config directory?

**Comment by KipourosV** [comment]
I checked the pid file... says 6...
Which PID should I use, there are two 26756 and 28054

**Comment by maksis** [comment]
You seem to be running two different instances? They can't share the same config directory. Pick the process that is at 100%.

**Comment by KipourosV** [comment]
(gdb) attach 26756
Attaching to process 26756
/usr/local/bin/airdcppd: No such file or directory.

Because of docker....

How am I running two different instances??? That's too weird... Isn't the second process the hasher?

**Comment by KipourosV** [comment]
Back to normal just now...

![image](https://cloud.githubusercontent.com/assets/16351880/16384022/c5b24adc-3c87-11e6-82ab-d65d2022153c.png)

**Comment by KipourosV** [comment]
and this is htop when running normally

![image](https://cloud.githubusercontent.com/assets/16351880/16384070/f17d0d8c-3c87-11e6-80a7-80bfabf7c38d.png)

**Comment by maksis** [comment]
Uhm ok, it seems to list each application thread individually (you should choose the main process).

Are you able to figure out how to make it work with docket?

http://stackoverflow.com/questions/21395106/how-can-i-gdb-attach-to-a-process-running-in-a-docker-container

**Comment by KipourosV** [comment]
I need to install gdb inside the container...
Which means I have to rebuild my container image with the modified dockerfile...
I do that everytime you have a new version out...
Let me give it a try and I'll let you know... (thanx for all the help so far!!!)

**Comment by KipourosV** [comment]
No need to rebuild the image and recompile... can install gdb as is...
Give me 20 minutes...

**Comment by KipourosV** [comment]
Damn!

(gdb) attach 6
Attaching to process 6
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
(gdb) quit

**Comment by KipourosV** [comment]
Currently going through this...

https://blog.wnohang.net/index.php/2015/05/05/debugging-docker-containers-with-gdb-and-nsenter/

**Comment by KipourosV** [comment]
Damn... Now that I found the way for gdb to work, I can't get the system to stall...

Although I'm almost sure it has to do with big bundles and filelists  (I'm downloading folders containing 1-2Tera of mp3's)

**Comment by KipourosV** [comment]
After this:
thread apply all bt full

How do I "Save the full output to a file ..."???

**Comment by maksis** [comment]
The application is paused when it's attached to gdb. Copying the text is one option, possibly there are better ones as well (I never have to save it).

**Comment by KipourosV** [comment]
isn't there a gdb command to save to file? the output is huge... do I have to manually copy each screen?

**Comment by maksis** [comment]
I read the output directly from the console window when I debug the application so I'm not familiar with different options (I'm unable to study those right now)

**Comment by maksis** [comment]
Another solution: check the thread PID that's using 100% of the CPU by using htop. Instead of attaching gdb to the main process PID, use the thread PID. Then `thread apply all bt full` will output the stack from that thread only.

**Comment by maksis** [comment]
... unless Docker prevents using that method

**Comment by KipourosV** [comment]
[dbg.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/335731/dbg.txt)

**Comment by maksis** [comment]
Ok, that's lots of data to make sense of. You probably want to delete that file now.

**Comment by maksis** [comment]
What are the largest file and folder counts inside your bundles?

**Comment by KipourosV** [comment]
![image](https://cloud.githubusercontent.com/assets/16351880/16396164/bb30c35a-3cbd-11e6-86e6-90d0afd2c26b.png)

![image](https://cloud.githubusercontent.com/assets/16351880/16396186/d5c09998-3cbd-11e6-8099-95845efc9279.png)

**Comment by maksis** [comment]
The issue happens when searching a large bundle for alternates

**Comment by maksis** [comment]
This should be fixed by https://github.com/airdcpp/airgit/commit/09795f81f23ea18726c32aaea3a4cdfb4be67c9b

You can try the develop branch to confirm this.

**Comment by KipourosV** [comment]
Great! Thanx a lot for all the support!!!

How do I try the develop branch???

**Comment by maksis** [comment]
https://airdcpp-web.github.io/docs/installation/compiling.html#installing-a-development-version

**Comment by KipourosV** [comment]
Trying now...

**Comment by KipourosV** [comment]
Do I run the git checkout develop
after the git pull?

**Comment by maksis** [comment]
Yeah, or before that. The order won't really matter.

**Comment by KipourosV** [comment]
Works great!!! Thanx!!!
