### ISSUE TITLE
Can't change username/password

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#168]
### Current UI and client versions:

 * Application version: AirDC++w 1.0.4 x86_64 / 0.851
 * Web UI version: 1.0.7

### Steps to reproduce the issue:

1. Connect to a favorite hub with a username + password
2. Disconnect you and edit with an other account (username + password) on the same server

For me, it is writing "Invalid password" even if it is good!

**Comment by Kcchouette** [comment]
To bypass that, I remove the .airdc++/ folder

**Comment by maksis** [comment]
Did you copy the password from somewhere? Are you sure that there weren't any extra whitespaces?

**Comment by Kcchouette** [comment]
Yes, no extra whitespaces.
I try the same thing on a fresh install, it works!

But when a account is already added, it's not the case.

**Comment by maksis** [comment]
So are you saying that the issue can also be reproduced with a fresh install?

**Comment by Kcchouette** [comment]
Yes, if an account is already here.

For example you install airdcpp with user1, password1. I can connect to the hub.
I change to user2, password2. The hub return "Invalid password".

I delete .airdc++, I install and configure airdcpp with user2, password2: it can connect.
I try to change to user1, password1. The hub return "Invalid password".

**Comment by maksis** [comment]
Did you close the hub before you tried to connect with the new account?

**Comment by maksis** [comment]
And which hubsoft is that hub running on?

**Comment by Kcchouette** [comment]
For the hubsoft, I'll ask to the owner when he'll be connected.

Else I retry:

1. I disconnect manually the hub
1. I change at the favorite the username and change the password
1. I click on the green arrow to connect (in the favorite tab)
1. the hub displays:
```
Connected
22:36:12
Stored password sent...
22:36:12
Invalid password
22:36:12
Invalid password
```

**Comment by maksis** [comment]
Some ADC hubsofts may use the client ID instead of just nick to determine the registered account. If you have two different accounts in the hub, the hub may choose a wrong one (unless you delete the settings when the client ID gets reset as well).

**Comment by Kcchouette** [comment]
Our adc hubsoft is adch++… Has it the effect you said?

**Comment by maksis** [comment]
Yes, it seems to prefer CID over nick: https://sourceforge.net/p/adchpp/code/ci/default/tree/plugins/Script/examples/access.lua#l522

**Comment by Kcchouette** [comment]
Yes, this soft use a combination (software key) + account to connect to the hub. It's not an issue from airdcpp-web. Thank you!
