### ISSUE TITLE
when adding new directories to share the size won't update

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#17]
When i add a new directory to the share the size won't change until i change to another page and back again.

Application version: AirDC++w 0.3 x86_64 / 0.850
Web UI version: 0.3.7

![picpick-2015 12 02-16 55 40](https://cloud.githubusercontent.com/assets/5789283/11535901/442dd3ce-9916-11e5-9358-a7cf5bd7ffc6.jpg)

**Comment by maksis** [comment]
I wouldn't really want to update the size after each hashed file so I'm not totally sure that how to fix this
