### ISSUE TITLE
Connection closed. Attempting to re-establish connection...

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#170]
### Current UI and client versions:

Application version
AirDC++w 1.0.5 x86_64
Web UI version
1.0.7

### Steps to reproduce the issue:

Can't reproduce, happens every 2 to 10 minutes after startup...

Time: 10:16:21 PM
OS version: Linux 4.4.1-amd64 (x86_64)
Client version: AirDC++w 1.0.5

airdcppd in function cow::StackTrace::generate_frames() in file /airdcpp-webclie                                                                                                             nt/airdcppd/stacktrace.cpp:44 [0x423d0a]
airdcppd in function std::ostream_iterator<cow::StackFrame, char, std::char_trai                                                                                                             ts<char> > std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<cow::StackFra                                                                                                             me*, std::vector<cow::StackFrame, std::allocator<cow::StackFrame> > >, std::ostr                                                                                                             eam_iterator<cow::StackFrame, char, std::char_traits<char> > >(__gnu_cxx::__norm                                                                                                             al_iterator<cow::StackFrame*, std::vector<cow::StackFrame, std::allocator<cow::S                                                                                                             tackFrame> > >, __gnu_cxx::__normal_iterator<cow::StackFrame*, std::vector<cow::                                                                                                             StackFrame, std::allocator<cow::StackFrame> > >, std:ostream_iterator<cow::Stack                                                                                                             Frame, char, std::char_traits<char> >) in file /usr/include/c++/5/bits/stl_algob                                                                                                             ase.h:438 [0x42259b]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fab048b9250]
/usr/local/lib/libairdcpp.so.1.0.5 in function dcpp::pickSearchItem(std::vector<                                                                                                             boost::intrusive_ptr<dcpp::QueueItem>, std::allocator<boost::intrusive_ptr<dcpp:                                                                                                             :QueueItem> > > const&) [0x7fab05e752ae]
/usr/local/lib/libairdcpp.so.1.0.5 in function dcpp::BundleQueue::getSearchItems                                                                                                             (boost::intrusive_ptr<dcpp::Bundle> const&) const [0x7fab05e77335]
/usr/local/lib/libairdcpp.so.1.0.5 in function dcpp::QueueManager::searchBundleA                                                                                                             lternates(boost::intrusive_ptr<dcpp::Bundle>&, bool, unsigned long) [0x7fab05f5d                                                                                                             312]
/usr/local/lib/libairdcpp.so.1.0.5 in function dcpp::QueueManager::searchAlterna                                                                                                             tes(unsigned long) [0x7fab05f5e535]
/usr/local/lib/libairdcpp.so.1.0.5 in function [unknown] [0x7fab05f5e6dc]
/usr/local/lib/libairdcpp.so.1.0.5 in function dcpp::DispatcherQueue::run() [0x7                                                                                                             fab05ebcaf4]
/usr/local/lib/libairdcpp.so.1.0.5 in function dcpp::Thread::starter(void*) [0x7                                                                                                             fab05fd7faa]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7fab05aae6aa]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fab0498b13d]

**Comment by maksis** [comment]
Could you test the develop branch and confirm that it has been fixed?

**Comment by maksis** [comment]
Released as 1.0.6
