### ISSUE TITLE
RegEx filtering

### ISSUE THREAD

**Issue by vestingz** [airdcpp-web/airdcpp-webclient#172]
While browsing file lists, i used the advanced filtering options quite often and found them very handy, especially the regex function to quickly sieve out results. Would love to see the regex option on the new client. Thank you!
![bildschirmfoto vom 2016-06-30 01-40-29](https://cloud.githubusercontent.com/assets/19933361/16472350/aa2b81b0-3e63-11e6-85c1-6480ccaeb613.png)

**Comment by maksis** [comment]
The support for regex filtering exists in the core and list view API so this just needs an UI implementation. 

Availability of horizontal space is currently an issue in mobile devices. Possibly filters should be removed from the mobile layout altogether.

**Comment by maksis** [comment]
@vestingz do you want the UI to persist the filtering method on some basis or is it fine to reset it back to partial matching after navigating to other views?
