### ISSUE TITLE
Error while building around 22% (PortMapping)

### ISSUE THREAD

**Issue by S3rus** [airdcpp-web/airdcpp-webclient#174]
Hey everyone,

unfortunately I cannot install the program, because I get an Error around 22% while building it. 
I am currently on Debian 7 Wheezy.

You can find the Error down below.
Thank you in advance.

/home/Tobi/airdcpp-webclient/airdcpp-core/airdcpp/Mapper_MiniUPnPc.cpp: In member function ‘virtual bool dcpp::Mapper_MiniUPnPc::init()’:
/home/Tobi/airdcpp-webclient/airdcpp-core/airdcpp/Mapper_MiniUPnPc.cpp:101:96: error: too many arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int)’
  UPNPDev* devices = upnpDiscover(2000, localIp.empty() ? nullptr : localIp.c_str(), 0, 0, v6, 0);
                                                                                                ^
In file included from /home/Tobi/airdcpp-webclient/airdcpp-core/airdcpp/Mapper_MiniUPnPc.cpp:30:0:
/usr/include/miniupnpc/miniupnpc.h:45:26: note: declared here
 LIBSPEC struct UPNPDev * upnpDiscover(int delay, const char * multicastif,
                          ^
/home/Tobi/airdcpp-webclient/airdcpp-core/airdcpp/Mapper_MiniUPnPc.cpp: In member function ‘virtual bool dcpp::Mapper_MiniUPnPc::add(const string&, dcpp::Mapper::Protocol, const string&)’:
/home/Tobi/airdcpp-webclient/airdcpp-core/airdcpp/Mapper_MiniUPnPc.cpp:164:66: error: too many arguments to function ‘int UPNP_AddPortMapping(const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*)’
   localIp.c_str(), description.c_str(), protocols[protocol], 0, 0) == UPNPCOMMAND_SUCCESS;
                                                                  ^
In file included from /home/Tobi/airdcpp-webclient/airdcpp-core/airdcpp/Mapper_MiniUPnPc.cpp:31:0:
/usr/include/miniupnpc/upnpcommands.h:123:1: note: declared here
 UPNP_AddPortMapping(const char * controlURL, const char * servicetype,
 ^
make[2]: *** [airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/Mapper_MiniUPnPc.cpp.o] Fehler 1
make[2]: *** Warte auf noch nicht beendete Prozesse...
make[1]: *** [airdcpp-core/CMakeFiles/airdcpp.dir/all] Fehler 2
make: *** [all] Fehler 2

**Comment by maksis** [comment]
Which operating system are you using?

**Comment by S3rus** [comment]
Debian 7 Wheezy.

**Comment by maksis** [comment]
The client is supported only on Debian 8

**Comment by maksis** [comment]
The minimum version of miniupnpc is now also mentioned at https://github.com/airdcpp-web/airdcpp-web.github.io/blob/master/_docs/installation/dependencies.md
