### ISSUE TITLE
airdcppd died

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#176]
Application version: AirDC++w 1.0.6 x86_64
Web UI version: 1.0.7
Web UI build date: June 24, 2016 9:53 AM

airdcppd died i'm not sure why, it just stopped responding.

[airdcppd_exeption.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/366139/airdcppd_exeption.txt)

**Comment by maksis** [comment]
The log suggests that you did something with the UI when it crashed. Otherwise I can't really make any conclusions from it.

**Comment by bissa** [comment]
I got an pm that i noticed from the popup window, a minute or something i activated the correct tab in firefox it died. I think it died before or after i clicked on "messages" in aircdc it lost connection and when i did a refresh nothing was responding.

**Comment by maksis** [comment]
Better see if it happens again

**Comment by maksis** [comment]
Closing as seems like it hasn't happened again
