### ISSUE TITLE
Widget - won't remember size and position

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#179]
When using the new widgets the size won't get saved. When i press Home they all are back tp a default position and size.

Application version
AirDC++w 1.1.0 armv7l
Web UI version
1.1.2-beta3
and
Application version
AirDC++ 3.22-3-g4638e x64
Web UI version
1.1.2-beta3

**Comment by maksis** [comment]
Please read https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md for bug reporting instructions

**Comment by Sopor-** [comment]
Let the bugs be there if you don't want to fix them

**Comment by maksis** [comment]
I don't understand that why do you think so. I tested this on my laptop and everything was saved correctly. I'm able to reproduce the issue on my desktop PC though and I'll investigate it later. Following the instructions certainly won't do any harm.
