### ISSUE TITLE
Allow persistent login

### ISSUE THREAD

**Issue by sbraz** [airdcpp-web/airdcpp-webclient#186]
Hi,
It'd be nice if there were a way to save sessions so I wouldn't have to log back in every time I re-open the Web UI.

**Comment by maksis** [comment]
Also related to #151

**Comment by GieltjE** [comment]
How many upvotes would it need for it to be queued for creation?

**Comment by maksis** [comment]
It's not only about the number of upvotes, as the actual requested feature matters as well. 

I'm not totally sure that how this feature could be easily implemented. I also have the credentials auto filled by the browser so I don't consider the login page to be an issue (and I use it a lot).

**Comment by GieltjE** [comment]
Some people (including me) use a reverse proxy (apache/nginx) to provide an extra layer of security and provide a simple single-sign-on for all services on the server. In these cases it's just a hassle to create/update every user twice.

**Comment by sbraz** [comment]
Well the newest version supports the `Authorization` HTTP header so that would probably help :)

**Comment by GieltjE** [comment]
@sbraz Doesn't function with apache and digest auth, if that would work it might help for some people

**Comment by maksis** [comment]
>In these cases it's just a hassle to create/update every user twice (especially with non tech savvy people who don't get why they have to login twice).

Do you have multiple users accessing the app or what is your actual use case? What kind of permissions do they have in airdcpp?

**Comment by GieltjE** [comment]
It's a server that at home is used by my partner and on lan-parties by mostly everyone within our group. This reduces the need for everybody running downloads and causing congestions (also performs centralized music and storage).

**Comment by maksis** [comment]
Are you aware of similar applications that have solved this issue?

**Comment by GieltjE** [comment]
Ampache, spotweb both can be used with or without accounts, don't know if that helps.

**Comment by maksis** [comment]
So... the "easiest" generic solution would be to add support for IP range whitelists? There should also be a binding to a local application account in that case and logging in with different credentials should still be possible in case the binding is made for a non-admin account and the user wants to access admin features.

**Comment by GieltjE** [comment]
Sounds like a solid plan, that would also enable everyone who isn't using a reverse proxy to "auto-login" from their local network but require a login from the internet thus covering far more use cases.

**Comment by maksis** [comment]
This will be added in the next version (I'm not sure about IP whitelists yet)

**Comment by StudioEtrange** [comment]
I am in the situation where i use a reverse proxy (traefik here) which manages security acces to all my webapp
I need to 
* either fully disable auth on airdcpp webui
* have an auto loggin mechanism through http header to the webui

Until now, nothing really possible.
