### ISSUE TITLE
Support for magnet links (UI)

### ISSUE THREAD

**Issue by maksis** [airdcpp-web/airdcpp-webclient#187]
Detect magnet links from chat messages (https://github.com/tasti/react-linkify/issues/24 would help with this), format them in a user-friendly way and show a download/view menu.

Note that magnet links can currently be handled by copying the TTH part from the link and putting it in search.

**Comment by maksis** [comment]
@Kcchouette do you mind sharing why you don't want this feature to be implemented? I'd prefer not downvoting features just because they don't fit someone's use case.

This feature is a prerequisite for implementing support for sharing files with drag-and-drop in chat windows that is supported by the Windows version already.

**Comment by Kcchouette** [comment]
@maksis only because I don't use it :)
