### ISSUE TITLE
Long folder names preventing going up a level in the filetree (Browse menu)

### ISSUE THREAD

**Issue by plasmus** [airdcpp-web/airdcpp-webclient#188]
### Current UI and client versions:
Application version: AirDC++w 1.2.0 x86_64
Web UI version: 1.2.0

### Steps to reproduce the issue:
This happens when you "Download To..." a folder in which the length fills up the top portion, and actually download a file into that folder.
Makes it so you can not get out of that folder.
Now when you select "Download to..." and go to "Browse" that is the default folder that it looks at, and you are stuck again.

Happened after I manually downloaded a missing file into a folder.
I am currently stuck with a folder length of 80 characters.

### Ideas
- Button to go up a level
- Reset saved location (setting)
- Truncate the name if longer than a certain length

**Comment by maksis** [comment]
You can work it around by making the browser window so narrow that the mobile layout is being enabled

**Comment by plasmus** [comment]
Thanks for the workaround. Never thought of doing that.

**Comment by maksis** [comment]
I had implemented width limits for narrow window sizes already. For some reason I hadn't tested it with normal windows widths and that long directory names.
