### ISSUE TITLE
Please make hubchat wider

### ISSUE THREAD

**Issue by perlaxe** [airdcpp-web/airdcpp-webclient#189]
Hi, please make hubchat window wider/resizabe or add a settings for it, it is so weird to have half of the screen empty on widescreen.
thx

**Comment by maksis** [comment]
https://github.com/airdcpp-web/airdcpp-webclient/issues/30

**Comment by maksis** [comment]
Note that you should upvote issues that you want to get implemented

**Comment by maksis** [comment]
Sidebar will be resizable in the next version
