### ISSUE TITLE
Show messages date.

### ISSUE THREAD

**Issue by YamashitaRen** [airdcpp-web/airdcpp-webclient#191]
Currently, I don't think there is a mean to know the date of messages you receive/send.
Maybe airdcpp could print a message every day "day has changed" or something like that...

**Comment by maksis** [comment]
I just implemented this on yesterday and it's available in the latest beta UI (https://github.com/airdcpp-web/airdcpp-webclient/issues/154).

Feature is also demonstrated at http://webdemo.airdcpp.net

**Comment by YamashitaRen** [comment]
Ahah sometimes it's nice to be too late. Guess I should have looked at the closes issues too...
Thanks for the hard work anyway :)
