### ISSUE TITLE
WebUI Not Displayed On Firefox

### ISSUE THREAD

**Issue by Cmdrd** [airdcpp-web/airdcpp-webclient#192]
### Current UI and client versions:

**Application version**
AirDC++ 3.23 x64
**Web UI version**
1.3.1
**Firefox version**
49.0.1

### Steps to reproduce the issue:

Attempting to connect to the WebUI presents the following page: http://i.imgur.com/ivwKHPz.jpg.

Works in both Chrome and Edge.

**Comment by maksis** [comment]
Does Firefox report any [console errors](https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md)? Have you tried to clear browser's cache?

**Comment by Cmdrd** [comment]
I have the following CSS errors: http://pastebin.com/NuHZzWH7. I can post those here instead of on pastebin if it would help to retain them, but there are quite a few.

**Comment by maksis** [comment]
Those are normal. What about the other question?

**Comment by Cmdrd** [comment]
Yes, I have cleared the browser cache as well and closed all instances of the browser.

**Comment by maksis** [comment]
Oh, that's complicated if there is no error. I test the UI on Firefox regularly and it's working fine. Are you trying to access the UI from a remote computer or why was the URL blurred? Are you trying to access the root URL?

**Comment by maksis** [comment]
You could test it in private browsing mode as well...

**Comment by Cmdrd** [comment]
I guess I probably didn't need to blur it, it's a system on my LAN. The elements are definitely all there. When I move my mouse over where the fields to enter the login information are, the icon changes to the typical text input mouse icon. Where the username input field is I also get the dropdown with other usernames, so everything is definitely there. I am browsing to the root URL, in this case https://192.168.2.100:5601 or http://192.168.2.100:5600. Private browsing is giving the same screen.

**Comment by maksis** [comment]
So are you saying that the content exists but you can't just see it? Are you familiar with using the developer tools (especially the element inspector)?

**Comment by Cmdrd** [comment]
Yes, the content exists but just isn't being displayed. I should have clarified that earlier. I've been digging through the CSS elements to see what may be causing this. If I find anything, I'll post it here. If you have any suggestions of anything in particular to look for, let me know.

**Comment by maksis** [comment]
I've never seen that happening and it's strange why it only happens to you and with a single browser (unless there are browser extensions interfering with the UI)

**Comment by Cmdrd** [comment]
I do have uBlock Origin, but I disabled that add-on as soon as I had this issue and still nothing. That's the only one that I have installed. Ya, I'm definitely finding it odd too, figured there was no way that Firefox would be unsupported for whatever reason. Anyway, I'll keep digging around, see if I can find anything.

**Comment by Cmdrd** [comment]
Alright, it's definitely something going on with this one, single installation. I tried it on another system with a clean install of Firefox, no issue. I can close this as it appears to purely be purely a single instance issue.

**Comment by maksis** [comment]
Hmm, sure. Please post an update if something new comes up later.
