### ISSUE TITLE
Skip folders

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#193]
Is it possible to add option to skip folders from share?

**Comment by maksis** [comment]
Do you mean specific paths? Share skiplist will match folder names as well.

**Comment by acmodeu** [comment]
Yes, could you please help me out with that? For example the structure of the share is this:
```
Folder to be excluded
  file_1 in Folder to be excluded.extension1
  file_2 in Folder to be excluded.extension2 
  file_3.extension3
```

I add `.Folder\sto\sbe\sexcluded.` pattern to skiplist and after refreshing share it does hide files but the folder and file_3.extension3 still exist.

**Comment by maksis** [comment]
Why are there dots in your pattern? Have you tested it with any regex tester (such as https://regex101.com) to confirm that the pattern is correct?

**Comment by acmodeu** [comment]
`.*Folder\sto\sbe\sexcluded.*` - that one worked fine.

**Comment by acmodeu** [comment]
In that case the option I was asking for is not so necessary at all. Thanks anyway.

**Comment by maksis** [comment]
Are you sure? Share skiplist isn't really designed for blocking individual directories. AirDC++ core has support for excluding specific paths already but I've been waiting for someone to request it first.

**Comment by acmodeu** [comment]
Personally I believe I can live with this functionality but may be someone needs this option. Let's see what others will say. I think it is a useful feature but not a priority one.

**Comment by maksis** [comment]
I've implemented this feature since it has received a few upvotes already

**Comment by awsms** [comment]
Mh.. I'm trying to exclude a specific folder (which is in a shared folder), and I'm having an error "Code 400: Path is not inside a shared directory"

**Comment by maksis** [comment]
> Mh.. I'm trying to exclude a specific folder (which is in a shared folder), and I'm having an error "Code 400: Path is not inside a shared directory"
> 
> Main shared folder -> Another folder -> The folder I'm trying to exclude.

It seems to be working for me. Please post a new issue with the steps to reproduce the issue (with the exact shared root path and the path that you are trying to exclude).
