### ISSUE TITLE
make[2]: *** No rule to make target

### ISSUE THREAD

**Issue by pappabetalar** [airdcpp-web/airdcpp-webclient#194]
Hi

I need some help getting airdcppd to run again after an Ubuntu Upgrade from LTS to normal.

cmake .
Seems to end successfully;
```
-- Installing Web UI
Installing Web UI (~1.3.0)
/home/OMGUSER/airdcpp-webclient
└── airdcpp-webui@1.3.1

Web UI was installed successfully
-- Configuring done
-- Generating done
-- Build files have been written to: /home/OMGUSER/airdcpp-webclient
```
make -j4
gives me:

```
Scanning dependencies of target airdcpp
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libboost_regex.so', needed by 'airdcpp-core/libairdcpp.so.1.3.0'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/version.cpp.o
CMakeFiles/Makefile2:117: recipe for target 'airdcpp-core/CMakeFiles/airdcpp.dir/all' failed
make[1]: *** [airdcpp-core/CMakeFiles/airdcpp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Does anyone know how i can fix this?

**Comment by maksis** [comment]
You could first try resetting all previous build files with ``rm -rf airdcpp-core/CMakeFiles/ && rm -rf airdcpp-webapi/CMakeFiles/ && rm -rf CMakeFiles/ && rm CMakeCache.txt`` and try compiling it again.

If that doesn't help, I need to see the full cmake output.

**Comment by pappabetalar** [comment]
[CMakeError.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/529471/CMakeError.txt)
[CMakeOutput.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/529480/CMakeOutput.txt)

Same as before, i am attaching both files here.

**Comment by maksis** [comment]
Could you post the console output?

**Comment by pappabetalar** [comment]
I might have made matters worse by deleting the whole "airdcpp-webclient" folder and starting fresh.
![airdcppd](https://cloud.githubusercontent.com/assets/11709536/19388280/09b52942-921f-11e6-9890-a4d9e39212c5.PNG)

**Comment by maksis** [comment]
It looks more clear to me now. I also didn't realize that Ubuntu 16.10 has been released already. 

You could try installing the missing packages with:

`sudo apt-get install libboost-regex1.6* libboost-thread1.6* libboost-system1.6*`

**Comment by pappabetalar** [comment]
Thank you, that was it! i'll just have to figure out a way around this. :)

```
The following packages have unmet dependencies:
 libboost-regex1.60-dev : Depends: libboost1.60-dev (= 1.60.0+dfsg-6) but it is not going to be installed
 libboost-regex1.61-dev : Conflicts: libboost-regex1.60-dev but 1.60.0+dfsg-6 is to be installed
 libboost-system1.60-dev : Depends: libboost1.60-dev (= 1.60.0+dfsg-6) but it is not going to be installed
 libboost-system1.61-dev : Conflicts: libboost-system1.60-dev but 1.60.0+dfsg-6 is to be installed
 libboost-thread1.60-dev : Depends: libboost1.60-dev (= 1.60.0+dfsg-6) but it is not going to be installed
                           Depends: libboost-atomic1.60-dev (= 1.60.0+dfsg-6) but it is not going to be installed
                           Depends: libboost-chrono1.60-dev (= 1.60.0+dfsg-6) but it is not going to be installed
                           Depends: libboost-date-time1.60-dev (= 1.60.0+dfsg-6) but it is not going to be installed
 libboost-thread1.61-dev : Conflicts: libboost-thread1.60-dev but 1.60.0+dfsg-6 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by maksis** [comment]
Thanks, I updated the docs for Ubuntu 16.10
