### ISSUE TITLE
Can browse own share

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#197]
Just compiled from scratch. Can't browse own share. File list - > browse own share -> default (322 GB) and nothing happens.
Application version AirDC++w 1.3.1 x86_64
Web UI version 1.3.2

Same thing with the development version.

**Comment by acmodeu** [comment]
Any luck with the fix?

**Comment by maksis** [comment]
This has been fixed in Web UI 1.3.3
