### ISSUE TITLE
Startup Error in libc.so.6

### ISSUE THREAD

**Issue by mzuenni** [airdcpp-web/airdcpp-webclient#198]
Hello i dont know what i changed to make the programm not start anymore but this is the error log:

> Time: 12:37:20 AM
> OS version: Linux 3.16.0-4-amd64 (x86_64)
> Client version: AirDC++w 1.0.3
> 
> /usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() [0x433f4b]
> /usr/local/bin/airdcppd in function handleCrash(int) in file main.cpp:0 [0x44b11a]
> /lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f05ec7ab0e0]
> /usr/local/lib/libairdcpp.so.1.0.3 in function dcpp::SettingsManager::get(dcpp::SettingsManager::BoolSetting, bool) const [0x7f05ef3041e3]
> /usr/local/lib/libairdcpp.so.1.0.3 in function dcpp::LogManager::message(std::string const&, dcpp::LogMessage::Severity) [0x7f05ef464271]
> /usr/local/lib/libairdcpp-webapi.so.1.0.3 in function webserver::WebServerManager::load() [0x7f05ee373ab6]
> /usr/local/bin/airdcppd in function airdcppd::Client::startup() [0x441465]
> /usr/local/bin/airdcppd in function airdcppd::Client::run() [0x4412e7]
> /usr/local/bin/airdcppd in function runConsole(std::string const&) in file main.cpp:0 [0x44bbef]
> /usr/local/bin/airdcppd in function main [0x44ceb4]
> /lib/x86_64-linux-gnu/libc.so.6 in function __libc_start_main [0x7f05ec797b45]
> /usr/local/bin/airdcppd in function _start [0x433de9]

any idea why this happens?

**Comment by maksis** [comment]
You are using a really old version. That crash shouldn't happen with the latest one so you should upgrade.
