### ISSUE TITLE
Hard reset problem?

### ISSUE THREAD

**Issue by plasmus** [airdcpp-web/airdcpp-webclient#199]
Seems something went wrong after a hard reset.

Any ideas what would need to be reset for it to read the xml correctly?
I did run 'airdcppd --configure' again to make sure that is correct. (file seems to be fine)

When I run airdcppd i just get
```
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files

FATAL: Can't start AirDC++ Web Client: Invalid XML file, missing or multiple root tags
```

Somehow AirDC++ can't see the XML file?

### Current UI and client versions:

Should be the most recent. airdcpp-webui@1.3.3 when running 'cmake .'
After a 'sudo make install'
...
```
-- Installing: /usr/local/lib/libairdcpp.so.1.3.1
-- Set runtime path of "/usr/local/lib/libairdcpp.so.1.3.1" to "/usr/local/lib"
-- Installing: /usr/local/lib/libairdcpp-webapi.so.1.3.1
-- Set runtime path of "/usr/local/lib/libairdcpp-webapi.so.1.3.1" to "/usr/local/lib"
-- Installing: /usr/local/bin/airdcppd
-- Set runtime path of "/usr/local/bin/airdcppd" to "/usr/local/lib"
```

### Steps to reproduce the issue:

This happened after a hard reset of the system when everything was frozen. ('sudo shutdown -h now' didn't even work through SSH)

### Summary of things I have tried

-Uninstalling, reinstalling
-Making sure the RUNNING file is gone in .airdc++ folder
-renewing the XML file (removing then remaking by 'airdcppd --configure')

**Comment by maksis** [comment]
Could you try removing the config file ``RSS.xml`` and the ``RSS`` directory?

**Comment by plasmus** [comment]
That worked, they were both empty.(file was blank and directory was empty)
I guess the hard reset cleared them out.

Thanks, would have never thought it was because of the RSS.
I'll let you close it, if it is a bug or not.

**Comment by maksis** [comment]
It's a bug because the client should be able to recover from empty XML files.

cc @night-z

**Comment by maksis** [comment]
https://github.com/airdcpp/airgit/commit/00bdc9d2fbd190665d697433f1f9f6e86b7b5bd8 should fix this
