### ISSUE TITLE
Smiley in a URL

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#200]
### Current UI and client versions:

Application version: AirDC++w 1.3.0 x86_64
Web UI version: 1.3.2-beta5

### Steps to reproduce the issue:
Paste a link.
You'll see it like that:
![screenshot](https://cloud.githubusercontent.com/assets/3000936/20039672/0565398c-a448-11e6-8915-b1433dfee303.png)
And the url for this will be: https://www.youtube.com/watch?v

**Comment by maksis** [comment]
https://github.com/airdcpp-web/airdcpp-webclient/issues/3
