### ISSUE TITLE
Nothing but 404 on access

### ISSUE THREAD

**Issue by NiQ1** [airdcpp-web/airdcpp-webclient#202]
I'm trying to compile and install AirDC++ on a QNAP NAS.
After a lot of struggling I've managed to get it to compile. --configure also works.
The problem is when I actually attempt to access the UI on port 5600 all I get is a 404 error (response content: "no such file or directory"). A 404 is also logged on the console screen.

Please help, what am I doing wrong?

**Comment by maksis** [comment]
Was the application compiled on the same system? Where were the UI files installed when you ran `make install`? You could also try specifying a custom web resource directory when starting the application as described in https://airdcpp-web.github.io/docs/usage/command-line-options.html

**Comment by NiQ1** [comment]
Got it! It installed them to /usr/local/share but on QNAP /usr/local is a tmpfs that gets overwritten on every reboot. Modified CMake files to change it to /opt/local/share, now it works :)

**Comment by maksis** [comment]
You may also change the directory without any file modifications: #38

ps. an official package for QNAP would be welcome 😉

**Comment by NiQ1** [comment]
I kinda want it to work "out of the box" and since using /usr/local on QNAP is impossible, I've decided to recompile.

Creating an official QNAP package would not be possible since it uses Boost and other libraries normally not available on QTS so it has to depend on Entware-ng, which has its own package manager (it actually uses OpenWRT's buildroot). If anyone has knowledge on how to create an ipk from a binary I'll be glad to try.

**Comment by NiQ1** [comment]
Well now I have another issue, will open a separate ticket.
