### ISSUE TITLE
Unknown error -2 on connect

### ISSUE THREAD

**Issue by NiQ1** [airdcpp-web/airdcpp-webclient#203]
For some reason it's impossible to connect to any hubs. I get a message "unknown error -2". The message is displayed immediately no matter whether the hub name is valid or not.
The same error appears in the event log when AirDC++ attempts to check for updates.

### Current UI and client versions:

Application version: AirDC++w 1.3.1 x86_64
Web UI Version: 1.3.3

Self compiled, running on QNAP NAS.

### Steps to reproduce the issue:

Just start up and try to connect anywhere.

**Comment by maksis** [comment]
Have you tested it with different types of hubs (ADC, ADCS, NMDC)? Have you tried it both with domain names and plain IP addresses? Was the application able to update GeoIP databases when you started it for the first time? What is the model of your system and the OS version?

**Comment by NiQ1** [comment]
OK, you're right, the problem has to do with DNS. Connecting directly to IP address works (in which case I have a problem of the peer list not showing up but let's take it one step at a time...)

**Comment by maksis** [comment]
With what kind of address did you get that error? Does it have a v6 (AAAA) record? At least the version URL has both A and AAAA records. Do you have IPv6 connectivity?

**Comment by NiQ1** [comment]
Any DNS address, no matter what. No AAAA record. The QNAP has no IPv6 stack whatsoever.

**Comment by maksis** [comment]
Hmm. Socket error -2 seems to refer to `Name or service not known` (EAI_NONAME ). I'm not sure that why it won't be translated to a correct error message. I assume that the system is able to resolve those addresses when using other tools? What is the OS version and have you tried to restart it? (so are you sure that it's a client issue)

**Comment by NiQ1** [comment]
Yes no general problem with DNS. The OS kernel is Linux 3.12.6 x86_64. Restarting the daemon has no effect.

**Comment by maksis** [comment]
I would first try [changing the data that is passed to getaddrinfo]( https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/Socket.cpp#L811-L819) (such as not passing the port at all and testing different hints). Confirming that it really throws in that function might also be useful.

Your startup issue was probably similar to #101?

**Comment by maksis** [comment]
You could also try mapping the hostname from your system's `hosts` file and see if it makes any difference. And do you get the same error if you try to connect to `localhost`?

**Comment by NiQ1** [comment]
Confirmed to be an OS problem. Seems like QNAP's amd64 DNS resolver is completely broken (always returns NETDB_INTERNAL). Recompiling as i686 and grunting :/

**Comment by NiQ1** [comment]
While I'm at it - while compiling against a new libc (from entware), apparently it does not include the __atomic functions, which cause a linker error. These functions are in a separate library called libatomic. A Google search shows that this may be common practice. Could you please modify CMakeList to search for this library and link it if found?

**Comment by NiQ1** [comment]
Recompiled, problem fixed. There's still the GUI problem I've mentioned but it's a separate issue so I'll open a separate thread.

**Comment by maksis** [comment]
Could you post a separate issue for the atomic errors (including the actual errors showing the application libraries with which it happened)?
