### ISSUE TITLE
Text encoding conversion issues (QNAP)

### ISSUE THREAD

**Issue by NiQ1** [airdcpp-web/airdcpp-webclient#204]
After many attempts I've managed to get AirDC++ Webclient compiled and running on QNAP NAS.

The main issue so far is that many elements in the GUI are broken -

- No user list when connected to hub (even though the number of users is correctly displayed at the bottom).

- If the user signs out of the web interface and then signs back in, the hub list is gone too, the only option is to add a new hub, however if you attempt to add the same hub again it says that it already exists (a netstat confirms that airdcppd is indeed still connected to the hub).

- Impossible to disconnect from a connected hub (no such option)

- When searching files the result list is empty although it reports hits on the bottom (actually in the top row several columns are not completely empty but say NaN instead).

### Current UI and client versions:

Application version: AirDC++w 1.3.1 i686
Web UI Version: 1.3.3

Self compiled, running on QNAP NAS (Linux 3.12.6).

The issue has been tested and reproduces using the latest versions of Firefox, Chrome and Edge.

### Steps to reproduce the issue:

- Connect to the main interface

- Add a hub and connect

- Click the "user list" switch at the bottom. An empty list will show up.

- Click search at the top bar

- Search for anything. You will see the number of hits but the actual list is empty, save for a couple of NaNs.

- Close the browser, open again and connect to the web interface again

- Click on hubs. No hubs show up even though the hub you've previously added is still connected (use netstat to confirm).

**Comment by maksis** [comment]
> Impossible to disconnect from a connected hub (no such option)

Is this a separate feature request for adding an option to disconnect a session without closing the tab or are you missing the close option for sessions?

Regarding the other issues: I'd really like to see API communication from browser's console (see [CONTRIBUTING.md](https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md) for more information). 

Lists views should push visible items to the UI right after they have been initialized. The list of current hub sessions is fetched after logging in so I wonder if there is any API response to that request. NaN rows may also suggest that your system/build config causes issues with JSON serialization.

**Comment by maksis** [comment]
Oh, and an obvious question: did the 64 bit build work without such issues?

**Comment by NiQ1** [comment]
OK, I was wrong about the disconnect thing, but the other issues persist.

Here a line I consider to be relevant -
72 POST hubs/v0/session/1/hub_user_view/settings Object { sort_property: "nick", sort_ascending: true }
72 SUCCEED **(no data)**

**Comment by NiQ1** [comment]
Search results are empty except for size (NaN kB), relevance (NaN), connection (NaN Kbit/s) and last modified (invalid date).

There's also an error logged multiple times
No properties were sent for a new view item _<number-varies>_

**Comment by NiQ1** [comment]
Another error - when attempting to reopen the hubs tab it hangs at "loading session" and the following errors are logged:
TypeError: e.flags is undefined
TypeError: e.users is undefined
TypeError: e is undefined

**Comment by maksis** [comment]
That line is not relevant. You should see lines starting with `search_view_updated` containing the visible list items. Since you see items in the list, those must be shown in the console as well.

What about the 64 bit build?

**Comment by NiQ1** [comment]
I see these items -
hub_user_view_updated - containing 3 elements only: matching_items: 10 (that's indeed the number of users in the hub), total_items: 10 and __proto__. No other members.
search_view_updated - items - Array[11], each sub-element is an object containing id (varying number) and __proto__. Nothing else. Then I get the "no properties were send" error.
The 64-bit version had the same symptoms (unfortunately had to delete the amd64 libraries to install the i686 ones so I can no longer test it).

**Comment by maksis** [comment]
Not receiving any properties would explain the issue since the UI isn't prepared to handle that. Were you able to find out anything about the missing hubs since it must be something different? That would be response to `"GET" "hubs/v0/sessions" "(no data)"`.

**Comment by NiQ1** [comment]
Wait, I do get the hub list back if I return to the home tab and then click the hubs list. The problem only happens if I click on hubs when I'm at the search results.
Would you be kind to assist regarding the missing properties?

**Comment by NiQ1** [comment]
Oh, one other thing - Seems that the hub list is never saved to the configuration. Whenever airdcppd is retstarted I need to input the hub addresses again.

**Comment by maksis** [comment]
If you connect to a hub from the Hubs page, there won't be any autoconnect. You need to add the hub in favorite hubs instead (there's a menu item for that). Have you been previously using ncdc?

Errors leave the UI into an inconsistent state and issues that you will find after that moment aren't usually that relevant. If an error happens, it's better to go to a page that doesn't produce any errors and reload the whole page. That's why I'm also interested in knowing where things go wrong for the first time.

Since you seem to be the first one having an issue like this, I still want to get a better picture of what's happening in the application. The console log is generally very helpful in explaining that.

You could do the following:

1. Open a new browser window, log in to the index page and clear the console (you may see a <rect> related error there but that's not an issue)
2. Go to the search page and perform your search
3. Save the console output to a file (there's a context menu item in Google Chrome for this)
4. Post the file here

After that you could also go to web server settings, change the number of server threads to 1, save the changes and restart the server. Open a new window and see if the problem remains.

**Comment by NiQ1** [comment]
I don't have Chrome on my personal computer, sending you a Firebug report (it should look better if you have the Firebug extension installed but is readable in any case). Rename to HTML before opening.
[firebug-console.html.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/589573/firebug-console.html.txt)


How do I change the number of server threads? Add the Threads attribute to Server and TLSServer in WebServer.xml? If so then it doesn't change anything and also the attribute is overwritten as soon as I stop the daemon.

**Comment by maksis** [comment]
> How do I change the number of server threads?

Settings -> System -> Web server

**Comment by NiQ1** [comment]
The problem still occurs.

**Comment by maksis** [comment]
The only issues that I can see are the missing properties in search view and that there are no updates at all in userlist view. Is it the same with Share, Favorites, Transfers, Web users (in settings) and Filelist tables?

**Comment by NiQ1** [comment]
Share, Favorites and web users work.
File list does not. Can't search for users because there are no results. I can only pick "browse own share", in which case it hangs at "Waiting for server response" and the following errors are displayed in console:
13:26:35.537 filelist_updated AILOIS6BALAMYKZAQLCH7ME3WBFHNGLNKIWTSRY Object { state: Object }1main.66c7779e17774015f153.entry.js:62:12138
13:26:35.541 Update received for a non-existing session Object { location: Object, read: false }1main.66c7779e17774015f153.entry.js:41:10746
Don't know about transfers because I can't initiate a transfer because of this bug. Currently it just says no active transfers.

**Comment by maksis** [comment]
Share, Favorites and Web users don't have that many rows, I assume?  I wonder if it could have something to do with the amount of data being sent. What happens if you resize the browser window so that there only one or two table rows visible. Naturally you need to do that before viewing the tables (or having any errors).

**Comment by NiQ1** [comment]
Doesn't look that way. I also went the other way around, added 10 hubs to the favorites (more than the expected user list), restarted the server and the favorites were still there.

**Comment by maksis** [comment]
> File list does not. Can't search for users because there are no results. 

But you are connected to a hub? The user search is performed in the daemon so the user list view shouldn't affect this (given that you haven't opened any broken views earlier). What do you see in the console when searching for users?

Are you able to see any errors in the daemon console window? The only thing that would currently make sense to me is that there's an error in the sending phase (views won't detect that so they think that the properties have been sent earlier).

**Comment by NiQ1** [comment]
Yes, I am connected to a hub.

This is the entire console output:
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files
Loading Country information
Starting web server.
AirDC++w 1.3.1 running, press ctrl-c to exit...
HTTP port: 5600, HTTPS port: 5601
[2016-11-17 15:26:02] [http]NASRG:5600 192.168.93.5:51557 "GET / HTTP/1.1" 200 1024 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0"
[2016-11-17 15:26:11] [connect] WebSocket Connection 192.168.93.5:51562 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0" / 101
[2016-11-17 15:27:00] [disconnect] Disconnect close local:[1000] remote:[1005]
Saving hash data
Saving the share cache
Closing connections
Saving settings
Shutting down.

**Comment by NiQ1** [comment]
Hi again,
When I've tried compiling on an unrelated machine to verify that it's not a bug in the program itself (it's not) I've also noticed there's one more thing that doesn't show up - The chat window! It does say "connecting" and "connected" but nothing else. Maybe that's also a hint.

If the problem still eludes you I'll try to do some debugging - could you please inform me how to generate debug symbols for this and give me a few hints on where so set breakpoints and what to look at?
Also if everything else fails - is there any way to compile a completely static binary so I can just compile on a different machine?

Thanks!

**Comment by NiQ1** [comment]
New issue now - at some point the WebSocket app stops responding completely (verified via tcpdump). When this happens I can't even stop the server without kill -9. If I attempt ^C is just displays the following error and hangs:

^C[2016-11-19 15:32:14] [info] Error getting remote endpoint: system:9 (Bad file descriptor)
[2016-11-19 15:32:14] [fail] WebSocket Connection Unknown - "" - 0 websocketpp:26 Operation canceled
[2016-11-19 15:32:14] [info] Error getting remote endpoint: system:9 (Bad file descriptor)
[2016-11-19 15:32:14] [fail] WebSocket Connection Unknown - "" - 0 websocketpp:26 Operation canceled
[2016-11-19 15:32:14] [info] asio async_shutdown error: system:9 (Bad file descriptor)
[2016-11-19 15:32:14] [info] handle_accept error: Operation canceled
[2016-11-19 15:32:14] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
[2016-11-19 15:32:14] [info] handle_accept error: Operation canceled
[2016-11-19 15:32:14] [info] Stopping acceptance of new connections because the underlying transport is no longer listening.
[2016-11-19 15:32:14] [info] asio async_shutdown error: asio.ssl:336462100 (asio.ssl error)

The issue remains even with a new configuration. Nothing has been modified in the system.

**Comment by maksis** [comment]
There's a section for reporting application freezes in the CONTRIBUTING doc

**Comment by maksis** [comment]
About the previous comment:

Assuming that the messages are lost in the sending phase, I'm not sure that what you should debug because sending isn't part of the application code. That freeze is more interesting. The browser console is also more informative when trying to find a pattern regarding the possible missing messages/responses to requests.

Generally it's better to use the latest available code when locating issues (develop branch). You can also compile a debug build with `-DCMAKE_BUILD_TYPE=Debug` to see if there are errors in the sending phase. Unfortunately there is no way to log all API messages in the daemon but such option should possibly be implemented. That would help to confirm that the messages won't get lost/filtered after they've been sent.

**Comment by maksis** [comment]
Oh, and did you ever try to use the app via HTTPS?

**Comment by NiQ1** [comment]
Hi, I'm sorry for not having been here for so long, I had some very busy time at work.
Anyway the freeze has something with the configuration since it doesn't happen when I recreated the config directory. I've tried deleting unnecessary lines from DCPlusPlus.xml, which seems to have resolved it but now the issue doesn't reproduce even when I restore the original... weird.

The problem persists even on HTTPS.

I'll try compiling a debug build and see what happens. Please advise which messages I should be looking for. Also please advise whether there's any place in the sources where I can add debug prints that can be helpful.

Thanks!

**Comment by maksis** [comment]
You may comment out https://github.com/airdcpp-web/airdcpp-webclient/blob/develop/airdcpp-webapi/web-server/WebSocket.cpp#L86 to see all messages being sent (and see if data sending failures are being reported, that is now done even in release builds).

You could also ensure that this code gets executed: https://github.com/airdcpp-web/airdcpp-webclient/blob/develop/airdcpp-webapi/api/common/ListViewController.h#L596

**Comment by NiQ1** [comment]
Well, I just compiled a debug build and it seems that indeed these pieces of code are never executed. I'm attaching the console log, maybe you'll find it meaningful (Note: The errors at the end are after I pressed ^C, which resulted in a freeze due to a loop of errors, maybe this is the freeze I had earlier).
[debuglog.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/628822/debuglog.txt)

**Comment by maksis** [comment]
> WebSocket::send failed: A payload contained invalid data

Hmm... that's definitely not normal. Which list views did you try to view? Have you tested it with any ADC hubs (such as adcs://hub.dcbase.org:16591) or small hubs without any cyrillic (or other non-latin) alphabet? 

https://github.com/zaphoyd/websocketpp/blob/378437aecdcb1dfe62096ffd5d944bf1f640ccc3/websocketpp/processors/hybi00.hpp#L347

**Comment by NiQ1** [comment]
Well it actually works with the hub you gave me. However the hub I used in my test (it's actually just one picked at random from a hub list) does work when I compiled on a standard Linux system, so there still has to be something weird. Maybe it's a protocol difference (A/DC/S)?

Regarding those lines you mentioned - Do you want me to place a debug print there?

**Comment by maksis** [comment]
> Regarding those lines you mentioned - Do you want me to place a debug print there?

No, not really. ADC used UTF-8 natively so no character conversions are needed. NMDC hubs don't use any specific locale so all data that is received via the hub is being converted to UTF-8 by the client. The default NMDC locale is specified under Settings -> Profile -> Miscellaneous. You could possibly test different locales there (and try lowercase names). 

The application uses iconv for conversions. Are you able to validate whether the iconv application (https://linux.die.net/man/1/iconv) works correctly on that system? What is your system encoding?

How familiar you are with C++ and character conversions?

https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/Text.h#L97
https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/Text.cpp

**Comment by NiQ1** [comment]
Changing codepages did not help. Iconv seems to be working fine (at least when using the iconv executable).

C++ coding is part of my job so I can say I am familiar. I don't have a lot of experience with the specific iconv API but I don't think that will be a problem.

**Comment by maksis** [comment]
Have you confirmed that all special characters work fine in ADC hubs?

Debugging the conversion progress might help:

https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/Text.cpp#L354
https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/Text.cpp#L386

That code is inherited from DC++ and I'm not that familiar with it. I don't know that how much sense it makes to have that low-level code in the application instead of using Boost Locale or similar conversion library...

**Comment by maksis** [comment]
Especially this location is interesting: https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/Text.cpp#L405-L406

**Comment by NiQ1** [comment]
Recompiled from develop branch.
Indeed it not says code page not supported by the system - but it says that for _any_ code page selected except UTF-8.
This seems very weird because iconv seems to work just fine (I'm attaching the output of iconv -l for reference). I've also checked via ldd and verified that the iconv binary and the airdcppd binary link with the save libiconv.so
[iconvlist.txt](https://github.com/airdcpp-web/airdcpp-webclient/files/642724/iconvlist.txt)

**Comment by NiQ1** [comment]
"ascii" also seems to be working. If we can't think of anything else I'll release the binary and just tell people to use that. Please notify me when 1.4.0 is released because I don't want to post binaries from the develop branch.

**Comment by maksis** [comment]
I released 1.4.0 earlier today: https://github.com/airdcpp-web/airdcpp-webclient/releases

I don't currently have any ideas that what else could be tried.

**Comment by NiQ1** [comment]
OK, We'll close this for now since we've tracked this to be a buggy implementation of libiconv and we have a working workaround (i.e. set encoding to "ascii"). I'll upload the binaries to the relevant forums.

Many thanks for your assistance!
