### ISSUE TITLE
Authentication failed: Cannot connect to the server

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#205]
Got this subj error message on the latest development build.

**Comment by maksis** [comment]
I'm running the latest build without issues. Have you tried to reload the page or use another browser?

**Comment by acmodeu** [comment]
Of course, I did. I ever built it from scratch, checked my config on both stable and develop branches. Stable is ok but develop gives the mentioned error.

**Comment by maksis** [comment]
What's in the console? See https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#ui-related-issues

**Comment by acmodeu** [comment]
FF 50.0.2 x64, Vivaldi 1.5.658.56 (Stable channel) (64 bit), Google Chrome 54.0.2840.99 (64-bit), Opera 41.0.2353.69

```
Starting socket connect  main.dc2124b382e1082945e8.entry.js:62:14643
Socket connected  main.dc2124b382e1082945e8.entry.js:62:14643
1 POST session/v0/auth Object { username: "username", password: "(hidden)", user_session: true }  main.dc2124b382e1082945e8.entry.js:62:14643
Во время загрузки страницы соединение с wss://domain.com:5601/ было прервано.  main.dc2124b382e1082945e8.entry.js:62:12568
Websocket failed: undefined  main.dc2124b382e1082945e8.entry.js:62:14643
Websocket was closed  main.dc2124b382e1082945e8.entry.js:62:14643
Socket disconnected during authentication, reconnecting  main.dc2124b382e1082945e8.entry.js:62:14643
Logging in failed Cannot connect to the server  main.dc2124b382e1082945e8.entry.js:40:18666
```

**Comment by maksis** [comment]
Did you mean to close this issue? Does that Russian text say something about page reload (and did you see that happening)? Do you get the same log if you try logging in again right after that?

I wrote a new section about communication issues and there are a few other things to check: https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#communication-issues-between-the-ui-and-the-application

**Comment by acmodeu** [comment]
I must have closed it accidentally. Could you open it? The russian text says: "Connection with wss:// was aborted (interrupted) during the page load." 

The error occurs with both http & https connections. I run app with --cdm-web and managed to get exceptioninfo.txt
[exceptioninfo.zip](https://github.com/airdcpp-web/airdcpp-webclient/files/634764/exceptioninfo.zip)

**Comment by maksis** [comment]
Ah, so the application had crashed. I can see the bug there.

**Comment by maksis** [comment]
The fix should now be available. Github seems to be having major issues at the moment though.

**Comment by acmodeu** [comment]
Thanks, it works now!
