### ISSUE TITLE
Won't hash filenames with non-alpha characters.

### ISSUE THREAD

**Issue by kendokan** [airdcpp-web/airdcpp-webclient#206]
### Current UI and client versions:

Application version
AirDC++w 1.3.1-46-gfef7 amd64
Web UI version
1.3.3
Web UI build date
October 24, 2016 2:37 AM

### Steps to reproduce the issue:

Hash directories containing filenames that include punctuation other than a period. Log reports:
`[2016-12-08 09:16] [Hasher #3] : Error hashing  /mnt/[redacted]/The Fighting 69th.avi: No such file or directory`

In the example above, the filename is:
`/mnt/[redacted]/The Fighting 69½th.avi`

Issue also occurs with filenames including ":", ";", "'", "¡", "é", and em dashes. There may be others that I just haven't noticed.

**Comment by maksis** [comment]
A bit similar to #137 

Are there any warnings in the Events tab? What is your operating system and the current locale?

**Comment by kendokan** [comment]
Yes, one for each file it encounters that matches my description. They're identical to what shows up in the log. I can privately send the entirety if you like.

Running on FreeBSD 10.3-RELEASE-p3, locale is set to cp1252 in the web UI but US-ASCII in the console. I'm looking at 137 and will try some of the suggestions there, will report results.

**Comment by maksis** [comment]
This is probably related to system locales (the locale set in the web UI is not relevant for file operations). What's the full output of `locale` command in console? If a UTF-8 locale isn't set at the moment, you could try changing it.

**Comment by kendokan** [comment]
Yup, you're exactly right. Adding the following to my init script resolved. Thank you for pointing me at the other issue.

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

**Comment by maksis** [comment]
What was the original output of `locale`? There should be a warning on startup for unset locales.

**Comment by kendokan** [comment]
```
LANG=
LC_CTYPE="C"
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
```

It doesn't pop an error when starting.

```
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files
Loading Country information
Starting web server.
AirDC++w 1.3.1-46-gfef7 running, press ctrl-c to exit...
HTTP port: 5600, HTTPS port: 5601
```

**Comment by maksis** [comment]
> It doesn't pop an error when starting.

There should have been a warning in the Events tab after startup (maybe I should show it in the console as well)

**Comment by maksis** [comment]
Ah, seems like FreeBSD really uses the locale US-ASCII if it's not set correctly while Linux reports ANSI_X3.4-1968 in such cases. I guess I need to show the warning also for US-ASCII.

**Comment by kendokan** [comment]
Yeah, I would have missed it there. There were several hundred events in the Events tab (enough to lock the Chrome tab for a while) and I didn't go through them line by line.

My preference would be an error in the console along with a hard stop.

**Comment by maksis** [comment]
And in fact US-ASCII and ANSI_X3.4-1968 seem to mean the same thing

https://www.compart.com/en/unicode/charsets/US-ASCII
