### ISSUE TITLE
How do I add directories to a Share Profile?

### ISSUE THREAD

**Issue by gangefors** [airdcpp-web/airdcpp-webclient#211]
I can't find a way through the web UI to add directories to a Share Profile.

I can add a new (empty) profile.
I can rename the profile.
I can browse the share for that (empty) profile.
I can delete the profile.

But I can't seem to find an option to add directories for a profile without directly modifiying the DCPlusPlus.xml file.

Your main readme clearly states:

> Key functionality
> Share selected directories with other users

But how do I do that through the web client?

**Comment by maksis** [comment]
When you add or edit shared directories, there should be a field named "Profiles". Click on the field and you should see a list of profiles to choose from.

**Comment by maksis** [comment]
![image](https://cloud.githubusercontent.com/assets/5640804/21912071/68aa4f46-d92c-11e6-8ba3-c4bfe66eee38.png)

**Comment by gangefors** [comment]
I was looking in the wrong place. I stared myself bilnd on Settings>Sharing>Share profiles when I should have clicked on Share in the main dropdown menu.

Feel free to laugh :rofl: 

Would it be possible to get a link to the Share when in Settings>Sharing>Share Profiles and klicking on a profile. That is, on top of browse/rename/remove you could add "edit" which brings you to the place I was looking for.

**Comment by maksis** [comment]
Yeah, some help messages could certainly be added
