### ISSUE TITLE
Weird browser issue

### ISSUE THREAD

**Issue by spinza** [airdcpp-web/airdcpp-webclient#213]
### Current UI and client versions:
AirDC++w 2.0.0b
Copy from *Settings* -> *About*
Chrome Version 56.0.2924.87 (64-bit)
UI related issues should also include the browser version.

### Operating system:
ubuntu 16.10
Accessed from Debian Jessie

### Steps to reproduce the issue:

Can't login to UI from Chrome or Firefox on debian.   After login icon just sits spinning with nothing happening.  From Chrome browser on my mobile I have no issue.  I changed OS on the machine.  Was fine from Ubuntu 16.10 + Chrome also.

This is the only website I have issue with.

**Comment by spinza** [comment]
If I give an incorrect user/password it does raise an error.  If the combination is correct nothing happens.

**Comment by maksis** [comment]
Note that when using beta versions, you should install the latest available git version according to https://airdcpp-web.github.io/docs/installation/compiling.html#installing-a-development-version

Beta versions will download the latest available UI version that will generally require the latest API features as well.

**Comment by maksis** [comment]
Did you manage to update to the latest beta version?

**Comment by spinza** [comment]
Thanks for the follow-up.

I had checked out the [2.0.0b tag](https://github.com/airdcpp-web/airdcpp-webclient/tree/2.0.0b) and compiled that.  I was happy to try a beta version, but didn't want to run dev.  I would have though that the beta version would work independently especially if announced in the feed.  I guess I was wrong.

I went back to master now.

**Comment by vergessen** [comment]
Are you running an ssh tunnel?  I have noticed the use of websockets in the new api seem to fail and never allow you to login when using a ssh tunnel.

**Comment by spinza** [comment]
Nope.

**Comment by maksis** [comment]
Since UI and daemon updates are released separately, cmake will always download the latest UI release available when using a pre-release version. It's different from stable releases, where a 1.4.x series daemon would always download the latest 1.4.x series Web UI.

I work on the code on Windows and update the develop branch here when there is something interesting enough to update my own regular installation. The changes have generally been pushed to Windows dev build users already, but yeah, updates can still be a bit more experimental compared to typical betas.

I've now clarified the beta announcement. Version 2.0.0 focuses mainly on the API and doesn't bring that many visible features to non-dev users. Smaller API changes can still be made, which may also affect the UI compatibility.

> I have noticed the use of websockets in the new api seem to fail and never allow you to login when using a ssh tunnel.

I assume that it's caused by the socket connect URL being changed from ws://server to ws://server/api/v1/ ? Is it something that the ssh tunnel can't be configured to handle?

**Comment by vergessen** [comment]
I will see what I can do I just thought maybe it was the same issue.   I just recompiled the newest version and put it on my vps.  Trying to connect this is what I get, and it gets stuck.  Though I don't want to take over this ticket as it appears to be unrelated the problem spinza mentioned. 

AirDC++w 2.0.0b-54-g172a running, press ctrl-c to exit...
HTTP port: 5600, HTTPS port: 5601
[2017-02-22 10:44:44] [http] 192.168.0.14:5600 [::ffff:192.168.0.14]:46268 "GET /login HTTP/1.1" 200 1032 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
[2017-02-22 10:44:44] [http] 192.168.0.14:5600 [::ffff:192.168.0.14]:46270 "GET /js/main.c92e967b103647f67cc7.entry.js HTTP/1.1" 200 529794 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
[2017-02-22 10:44:45] [http] 192.168.0.14:5600 [::ffff:192.168.0.14]:46272 "GET /js/login.b4b1d15446a54cc9c8d0.chunk.js HTTP/1.1" 200 1121 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
[2017-02-22 10:44:50] [connect] WebSocket Connection [::ffff:192.168.0.14]:46280 v13 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0" /api/v1/ 101
[2017-02-22 10:44:50] [http] 192.168.0.14:5600 [::ffff:192.168.0.14]:46282 "GET /js/home.376813b0ec84076fad3b.chunk.js HTTP/1.1" 200 147454 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

**Comment by vilunov** [comment]
@maksis Sometimes cmake downloads webui 2.0 even for stable versions when it should download 1.4.0, which makes the interface unusable. It seems that it happens when the folder was already used for compiling and wasn't fully cleaned.

**Comment by maksis** [comment]
> It seems that it happens when the folder was already used for compiling and wasn't fully cleaned.

Do you mean after the develop branch was used?

**Comment by vilunov** [comment]
> Do you mean after the develop branch was used?

No, this happens when I build the project two times in the same folder without cleaning it of built files.

**Comment by maksis** [comment]
I wonder if that has happened to anyone else. Why did you choose to rebuild it?

You may test the [UI installation script](https://github.com/airdcpp-web/airdcpp-webclient/blob/master/install_webui.sh) manually by running `sh install_webui.sh 1.4.1` where the number is the application version picked from https://github.com/airdcpp-web/airdcpp-webclient/blob/master/CMakeLists.txt#L13

It shouldn't override the version range as long as you are using the master branch based on the output of `git rev-parse --abbrev-ref HEAD` (or when compiling a non-git version).

**Comment by maksis** [comment]
The current release feed will be replaced with a separate news feed from the main site, which can be used to post news without accompanying releases.

Shipping the Web UI as an extension might be worth of investigating as well.
