### ISSUE TITLE
Non-persistant sharing settings

### ISSUE THREAD

**Issue by itprotj** [airdcpp-web/airdcpp-webclient#214]
AirDC ++ 3.30 x64

Not using the webUI in this instance.

Operating System:
Windows 10 Professional x64

Steps to reproduce issue:

1. Add a folder with other directories inside it to the sharing settings
2. Return to main GUI of AirDC
3. Go back to sharing settings, expand folder structure and untick a folder under the root directory
4. At some point after using the program/restarting the program that folder will automatically tick itself again.

Workaround is to check sharing settings each time AirDC is opened.

Bug is confirmed to happen on two different machines
Windows 7 Professional x64
Windows 10 Professional x64

**Comment by maksis** [comment]
Thanks for the report. Yeah, there are some issues indeed with the sharing settings. I've created a new report for regular AirDC++ at https://bugs.launchpad.net/airdcpp/+bug/1665907

I'll close this issue since it's related only to the Windows GUI, not to any web functionality.
