### ISSUE TITLE
Streaming media files while downloading

### ISSUE THREAD

**Issue by ashishchopra778** [airdcpp-web/airdcpp-webclient#215]
Airdcpp does a great job in making the hubs accessible through browser. I was thinking of having a feature where we can directly stream the media file (audio or video) being downloaded. WebRTC and HTML5 can help us in implementing this feature.

Let me know what you guys think of this. Would be amazing to contribute in this feature.

### Current UI and client versions:

Copy from *Settings* -> *About*

UI related issues should also include the browser version.

### Operating system:

Name and version of the operating system on which the application is installed on

### Steps to reproduce the issue:

If you are unable to reproduce the issue, you can explain that what was happening before the crash/issue occurred. If it is a recurring issue, please mention how often does it occur.

**Comment by maksis** [comment]
Enabling such functionality would be nice. What would it require from the backend and UI? 

I'm currently working on extension support (scripts that are run in a separate process by the application). Allowing people to write extensions for media playback would be interesting.

**Comment by maksis** [comment]
Closing for now as I don't think that there are development resources to implement such functionality
