### ISSUE TITLE
Random crashes...

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#216]
### Current UI and client versions:

Application version
AirDC++w 2.0.0b-67-gaeab6 x86_64
Web UI version
2.0.0-beta11
Web UI build date
February 26, 2017 1:40 PM
API version
1
API feature level
0
Started
3 minutes ago
Active sessions
1
Server threads
4

### Operating system:

Ubuntu 16.10 LXC container running on Debian Jessie

### Steps to reproduce the issue:

It's random...

**Comment by maksis** [comment]
Does it crash or freeze? Which version were you using before?

**Comment by KipourosV** [comment]
Haven't used for some time since version 1.2.
Installed again yesterday and went straight to the beta.

It just quits...

**Comment by maksis** [comment]
There's nothing in console when it quits? Could you try running it with gdb: `gdb airdcppd`? Just do `thread apply all bt full` after the crash.

**Comment by KipourosV** [comment]
This is from console...

Collecting crash information, please wait...
/usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() [0x5563b3d57b9d]
/usr/local/bin/airdcppd in function [unknown] [0x5563b3d4b255]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f750f4ca860]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f750e4f60ba]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f750e4f618b]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f750e4f7ce8]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f750e4f6692]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f750e4f10f4]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function tbb::task_scheduler_init::initialize(int, unsigned long) [0x7f750e4f11ac]
/usr/local/lib/libairdcpp.so.2.0.0b in function dcpp::ShareManager::runTasks(std::function<void (float)>) [0x7f7510822ab0]
/usr/local/lib/libairdcpp.so.2.0.0b in function dcpp::ShareManager::run() [0x7f75108247a6]
/usr/local/lib/libairdcpp.so.2.0.0b in function dcpp::Thread::starter(void*) [0x7f75109aaeda]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7f751049c6ca]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f750f59d0af]

Exception info to be posted on the bug tracker has also been saved in /root/.airdc++/exceptioninfo.txt
Press enter to continue


Trying gdb now...

**Comment by maksis** [comment]
Ah, no need for gdb since you had the log after all. Seems like the crash is caused by the Intel TBB library.

**Comment by maksis** [comment]
Or well, you could still try gdb as well. Better install the package `libtbb2-dbg` first.

**Comment by KipourosV** [comment]
Hm... enlighten me... what does that library do? what is it used for? and how did you figure this out so quickly?

**Comment by KipourosV** [comment]
Just run with gdb and waiting for results...

**Comment by KipourosV** [comment]
now the webui is stuck after username and password prompt with the circle going round forever...

**Comment by maksis** [comment]
> what does that library do? what is it used for? 

It's the last package listed at https://airdcpp-web.github.io/docs/installation/dependencies.html

It's an optional package but I'd still like to know why it crashes. 

> now the webui is stuck after username and password prompt with the circle going round forever...

I just experienced it as well when debugging so I should be able to figure it out at some point. However, the crashed seemed to happen when refreshing the share, so even though you can't access the UI, you could try the example API method shown at http://docs.airdcpp.apiary.io/#introduction/communicating-via-http

**Comment by KipourosV** [comment]
The gdb run hasn't crashed yet...

**Comment by maksis** [comment]
If you don't get anything, uninstalling the tbb library and recompiling the application will possibly fix the issue. Are you able to test it without LXC? Did you use it when running the earlier versions? It might have something to do with a crash related to multithreading.

**Comment by KipourosV** [comment]
Last time I was using docker, now switched to lxc... will see if I can try compiling and installing on a full vm and let you know... for the time being I'll switch back to master...

**Comment by maksis** [comment]
> for the time being I'll switch back to master...

Yeah, that's one thing to try as well. If the issue is related to TBB, you should still get the same crash.

**Comment by KipourosV** [comment]
Last night something weird happened...
Compile quit with an error around 64%... didn't note the error, just restarted compile and it continued from where it left off and finished without error...

**Comment by maksis** [comment]
Could it have run out of memory? That would explain a temporary error.

I'd like to know how it goes with master branch in any case (just don't uninstall tbb yet).

**Comment by KipourosV** [comment]
Master branch does the same... I launch it in the container and after some random time, it's down...
I've just run from terminal without -d and waiting for the crash... :(

**Comment by KipourosV** [comment]
Collecting crash information, please wait...
/usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() [0x55b542f62bdd]
/usr/local/bin/airdcppd in function [unknown] [0x55b542f56345]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fc61ef05860]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df310ba]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df3118b]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df32ce8]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df31692]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df2c0f4]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function tbb::task_scheduler_init::initialize(int, unsigned long) [0x7fc61df2c1ac]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::runTasks(std::function<void (float)>) [0x7fc62025a7e6]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::run() [0x7fc62025c666]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::Thread::starter(void*) [0x7fc6203d3aba]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7fc61fed76ca]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fc61efd80af]

Exception info to be posted on the bug tracker has also been saved in /root/.airdc++/exceptioninfo.txt
Press enter to continue

**Comment by KipourosV** [comment]
root@airdcpp-web:~# cat /root/.airdc++/exceptioninfo.txt
Time: 12:35:45 PM
OS version: Linux 4.4.44-1-pve (x86_64)
Client version: AirDC++w 1.4.1

/usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() [0x55b542f62bdd]
/usr/local/bin/airdcppd in function [unknown] [0x55b542f56345]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fc61ef05860]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df310ba]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df3118b]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df32ce8]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df31692]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7fc61df2c0f4]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function tbb::task_scheduler_init::initialize(int, unsigned long) [0x7fc61df2c1ac]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::runTasks(std::function<void (float)>) [0x7fc62025a7e6]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::run() [0x7fc62025c666]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::Thread::starter(void*) [0x7fc6203d3aba]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7fc61fed76ca]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fc61efd80af]
root@airdcpp-web:~#

**Comment by maksis** [comment]
Yeah, that was quite expected. Do you currently have multithreaded filelist refresh enabled from settings/sharing/refresh-options?

**Comment by KipourosV** [comment]
Yes. 3 hashers

**Comment by maksis** [comment]
> Yes. 3 hashers

No, that's not what I meant

**Comment by KipourosV** [comment]
Oh yes. Multithreadded file list refresh - Always.

**Comment by maksis** [comment]
Could you try compiling the client with the following line commented out: https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/ShareManager.cpp#L2640 (keep the setting unchanged)

**Comment by maksis** [comment]
I'm quite sure that it will prevent the crash from happening.

There's a reason for that line to exist though. TBB creates a default scheduler (thread pool) automatically when the application performs parallel tasks for the first time. However, the default scheduler is shared among all tasks. If filelist refresh consumed all threads from the default scheduler, no other parallel tasks could be run simultaneously. 

The Windows version uses parallel tasks for various GUI actions and those tasks wouldn't complete if filelist refresh was using the default scheduler and consuming all it's threads (there were complaints from users before separate schedulers were added for long running tasks).

The TaskScheduler simply calls [task_scheduler_init](https://software.intel.com/en-us/node/506296) and controls it's lifetime. I can't currently see anything wrong with the way it's being used so I still suspect that the issue has something to do with LXC (especially if everything is working fine without containers or when using Docker).

**Comment by KipourosV** [comment]
Commented the line out and recompiled.
Just got the crash again...

**Comment by maksis** [comment]
Could you post the log?

**Comment by KipourosV** [comment]
I changed the Multithreaded refresh to manual and left it for about an hour now, still no crash...
Gonna re-enable and post the crash log...

**Comment by maksis** [comment]
Hmm, the client shouldn't remove old crash logs. Even better: remove the `libtbb2-dbg` package and run it via gdb to get line numbers. It really shouldn't produce the same crash if you are running the modified version.

**Comment by KipourosV** [comment]
Still waiting for another crash but nothing yet...

**Comment by KipourosV** [comment]
Collecting crash information, please wait...
/usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() [0x561882d4cbdd]
/usr/local/bin/airdcppd in function [unknown] [0x561882d40345]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f04222d8860]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f04213040ba]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f042130418b]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f0421305ce8]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f0421304692]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f04212ff020]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function tbb::internal::allocate_root_with_context_proxy::allocate(unsigned long) const [0x7f04212fd165]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::runTasks(std::function<void (float)>) [0x7f042362d841]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::run() [0x7f042362f616]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::Thread::starter(void*) [0x7f04237a6a4a]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7f04232aa6ca]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f04223ab0af]

Exception info to be posted on the bug tracker has also been saved in /root/.airdc++/exceptioninfo.txt
Press enter to continue

**Comment by KipourosV** [comment]
Time: 10:48:11 PM
OS version: Linux 4.4.44-1-pve (x86_64)
Client version: AirDC++w 1.4.1

/usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() [0x561882d4cbdd]
/usr/local/bin/airdcppd in function [unknown] [0x561882d40345]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f04222d8860]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f04213040ba]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f042130418b]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f0421305ce8]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f0421304692]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function [unknown] [0x7f04212ff020]
/usr/lib/x86_64-linux-gnu/libtbb.so.2 in function tbb::internal::allocate_root_with_context_proxy::allocate(unsigned long) const [0x7f04212fd165]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::runTasks(std::function<void (float)>) [0x7f042362d841]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::ShareManager::run() [0x7f042362f616]
/usr/local/lib/libairdcpp.so.1.4.1 in function dcpp::Thread::starter(void*) [0x7f04237a6a4a]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7f04232aa6ca]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7f04223ab0af]

**Comment by KipourosV** [comment]
*** Reminder ***
The above is after editing the file and commenting out that line...

**Comment by maksis** [comment]
Ah, so the crash is actually a bit different this time. I'd really like to know if there are similar issues when using Docker or other configurations. If such crashes are only happening with LXC, I'm not sure if there is anything that I can do. Multithreaded filelist refresh is also disabled by default as it can be quite disruptive on low-power systems.

**Comment by KipourosV** [comment]
So what do you propose? Should I reinstall the beta and disable Multithreaded filelist refresh?

**Comment by maksis** [comment]
Yeah, disabling multithreaded filelist will help to avoid the crashes (whether you are using beta or not shouldn't matter). Similar code is also used elsewhere though (loading and saving of settings) so I'm not sure if those will cause issues as well.

**Comment by KipourosV** [comment]
[ 10%] Building CXX object airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/DirectoryListing.cpp.o
[ 10%] Building CXX object airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/HttpDownload.cpp.o
[ 11%] Building CXX object airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/ActivityManager.cpp.o
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
airdcpp-core/CMakeFiles/airdcpp.dir/build.make:350: recipe for target 'airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/SearchManager.cpp.o' failed
make[2]: *** [airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/SearchManager.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'airdcpp-core/CMakeFiles/airdcpp.dir/all' failed
make[1]: *** [airdcpp-core/CMakeFiles/airdcpp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@airdcpp-web:~/airdcpp-webclient#

**Comment by KipourosV** [comment]
Disregard the previous post, happens when trying to compile on 2gigs of ram.
When I increase to 4 everything goies smooth...
