### ISSUE TITLE
Devopment build compilation error

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#218]
Console log attached.

**Comment by maksis** [comment]
I don't see the log. Is it the same as https://www.airdcpp.net/forum/viewtopic.php?t=4583 ?

**Comment by acmodeu** [comment]
Yeah seems like it. Strange  - github doesn't attach zip files made with winrar.

**Comment by acmodeu** [comment]
https://drive.google.com/file/d/0BzE-uf1_dvuAaTNGTkFTeE13VGc

**Comment by maksis** [comment]
Ok, it's the same issue. I'll make a fix soon.

**Comment by maksis** [comment]
Fixed
