### ISSUE TITLE
Connection timeout error

### ISSUE THREAD

**Issue by doobnet** [airdcpp-web/airdcpp-webclient#219]
I'm trying to use the airdcpp-webclient on a QNAP NAS using a Docker container. I'm able to login to hubs and search, but when I try to download something I get a Connection timeout error in the client. I've configured my router to allow UPnP, I've also tried by manually specifying the ports and opened them in the router. I've also tried to set up a local hub and then downloading worked.

Not sure what I'm doing wrong.

**Comment by doobnet** [comment]
> Since you receive search results, it suggests that the UDP port is working correctly. 

@maksis answering here instead since I have some issue with login on the forum.

> What is your port config?

* Let AirDC++ determine the best IPv4 connectivity settings
* IPv6 Connectivity (auto detected) - `Disabled`
* TCP (auto detected)
* UDP (auto detected)
* TLS/TCP (auto detected)
* Preferred port mapping interface (auto detected) - `MiniUPnP`

I can see in my router three entries in the UPnP settings which match the ports in the airdcpp connectivity settings.

> Are you using ADC or NMDC hubs?

ADC. Encryption is required (adcs)

> Have you tested it with transfer encryption disabled?

I've tried now, same behavior.

**Comment by maksis** [comment]
https://forum.level1techs.com/t/forwarding-traffic-from-docker-container-on-my-nas/112727/7

Will that help?

**Comment by doobnet** [comment]
No, that did not help. I'm running the docker container with the network configured as "host", which means the port mappings for the container doesn't matter.

**Comment by maksis** [comment]
Can you confirm that the ports are really open to internet when using the test linked in that thread?

**Comment by doobnet** [comment]
I figured out the problem. I had a whitelist of IP addresses that could connect to the NAS. I tried disabling that and then it worked. I apologize for the trouble.
