### ISSUE TITLE
Reverse proxy login issue

### ISSUE THREAD

**Issue by DracoMilesX** [airdcpp-web/airdcpp-webclient#222]
I am using a Xpenology NAS I am running the docker image for airdcpp on it.

Both HTTP and HTTPS locally are working fine but when I setup Reverse proxy and try to access it from URL it gives me: Authentication failed: Cannot connect to the server.

Am I missing something in my settings that I have to do before I am able to login? Or can't I just login with the admin account from a reverse proxy?

**Comment by maksis** [comment]
Does the proxy handle websockets? It most likely requires extra config: 

https://airdcpp-web.github.io/docs/advanced/nginx-setup.html
https://github.com/airdcpp-web/airdcpp-webclient/issues/150

**Comment by DracoMilesX** [comment]
>     location / {
>         proxy_set_header        Host                $host;
>         proxy_set_header        X-Real-IP           $remote_addr;
>         proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
>         proxy_set_header        X-Forwarded-Proto   $scheme;
>         proxy_intercept_errors  on;
>         proxy_http_version      1.1;


^that one is in my server.conf which contains the rest of my reverse proxy as well

> proxy_set_header X-Forwarded-By $server_addr;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-Proto $scheme;
> proxy_set_header X-Forwarded-Port $server_port;
> proxy_set_header Host $http_host;
> proxy_set_header Upgrade $http_upgrade;
> proxy_http_version 1.1;

^That one is my proxy.conf which basically is the only info in it

So seems like the Upgrade and Connection aren't mentioned in the server.conf will figure out how I can manual add it and how it stays added when I reboot the web server.

**Comment by DracoMilesX** [comment]
Ok adding them to the server.conf solved the issue thanks.
