### ISSUE TITLE
web client: login fails "not enough parameters"

### ISSUE THREAD

**Issue by skimj** [airdcpp-web/airdcpp-webclient#223]
When I try to login to the web client I get the following error message:
> Authentication failed: Parsing failed: Not enough parameters

I'm not sure where the issue is or how to debug/resolve it. Any tips would be appreciated.

### Current UI and client versions:

Latest git source: airdcpp-webclient-git-r2726.0ac361e7
Note: built against OpenSSL 1.0 libraries

### Operating system:

Arch Linux

**Comment by maksis** [comment]
Seems like there is something wrong with the UI installation script as it tries to install an incompatible version after the README update that I made on yesterday

**Comment by maksis** [comment]
Could you test with the latest UI installation script from https://github.com/airdcpp-web/airdcpp-webclient/blob/0614b1f79de8634bb70bea3bd09c5dd3c92199c2/scripts/install_webui.sh ? Also check the UI version being installed when running cmake, which should be 1.4.0 instead of ~2.0.0-beta.

**Comment by skimj** [comment]
git version 2.12.2

The UI version is airdcpp-webui@2.0.0-beta16. so it sounds like this would be an issue. Shall I proceed to test with the above installation script or get to the 1.4.0 UI version?

**Comment by maksis** [comment]
I'd like to hear if it works correctly with the updated installation script (as the issue should be fixed). What's the output of `git rev-parse --abbrev-ref HEAD` when executed inside the source directory?

**Comment by skimj** [comment]
`>git rev-parse --abbrev-ref HEAD
master`

So then, I started all over with a fresh git clone and manually updated the install_webui.sh per above. Now everything runs fine, I can login to the UI, etc. So I'll call it a success. Thanks for the help. Shall I mark this closed, or is there anything else to test/report?

**Comment by maksis** [comment]
Great, yes, that's enough for me to know. 

ps. version 2.0.0 will be released within the next few days, which adds support for the latest OpenSSL version
