### ISSUE TITLE
[Config] Can't access to the web-ui

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#225]
### Current UI and client versions:

Edit: UI is 2.0.2-beta1 and client AirDC++w 2.0.0 x86_64

### Operating system:

Debian 8.8

### Steps to reproduce the issue:

Before 2.0, I was using 1.4.1, and  it was working.

I think it's about the new logging system.

I'm using proxying with nginx, protected by a auth_basic.

Before: I go to http://ADRESS/airdcpp/, I enter my auth_basic username/password and after I have the logging page of airdcpp.
Now:  I go to http://ADRESS/airdcpp/, I enter my auth_basic username/password and after I have a "Invalid username or password" message instead of the login system.

Note: accessing to http://ADRESS:PORT/ instead of http://ADRESS/airdcpp/ (the proxy by nginx) does not have this problem.

**Comment by maksis** [comment]
I'm using the app with nginx (without basic auth) and it works. Are you able to see anything helpful in nginx logs? Or if you launch the application with `--cdm-web`?

**Comment by Kcchouette** [comment]
> Or if you launch the application with `--cdm-web`?

Doesn't work, because I can't even access at the login page :(

> without basic auth

My problem should come on the basic-auth. the login/password are totally different from airdcpp and nginx auth-basic

**Comment by maksis** [comment]
nginx's basic auth header would conflict with airdcpp's basic auth that was added in version 2.0.0, which is now mentioned in the example config: https://airdcpp-web.github.io/docs/advanced/nginx-setup.html
