### ISSUE TITLE
"Updating view" when no share

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#226]
### Current UI and client versions:

Application version: AirDC++w 2.0.0 x86_64
Web UI version: 2.0.2-beta1

### Operating system:

Debian 8.8

### Steps to reproduce the issue:

Trying to have the filelist of a personn who don't have any share/share hidden for this hub.

The web UI indicates "Updating view", but we know that the filelist does not exist or is empty.

**Comment by maksis** [comment]
There's a fix for this in the develop branch
