### ISSUE TITLE
Blurred filenames on Chrome

### ISSUE THREAD

**Issue by koxu1996** [airdcpp-web/airdcpp-webclient#229]
### Current UI and client versions:

**Application version:** AirDC++w 1.4.1 x86_64
**Web UI version:** 1.4.0
**Browser:** Google Chrome 58.0.3029.96 (64-bit)

### Operating system:

Ubuntu 16.04 LTS 64-bit 

### Steps to reproduce the issue:

I am not sure it's AirDC++ issue, but on Chrome filenames are a bit blurred: [screenshot](http://i.imgur.com/TnTsFVf.png). On firefox everything look good.

**Comment by maksis** [comment]
Could you try with the latest version? Or just check http://webdemo.airdcpp.net which is the latest one.

**Comment by maksis** [comment]
The UI framework being used: https://semantic-ui.com

**Comment by koxu1996** [comment]
Demo is not working for me: [screenshot](//i.imgur.com/nvBbsdF.jpg). I will download an update and let you know in a moment.

**Comment by koxu1996** [comment]
I think this is the bug https://github.com/Semantic-Org/Semantic-UI/issues/3433 and it is not related to AirDC++ so I am closing issue.

**Comment by maksis** [comment]
I'm using Chrome as well but I'm probably just too used to it already :p

Your demo issue is quite interesting though as the login is working fine for me.
