### ISSUE TITLE
Alt Text for User Icons

### ISSUE THREAD

**Issue by whispy** [airdcpp-web/airdcpp-webclient#233]
Right now, all the user icons are mystery images. Googling around for what they contain gives no information.

It would be nice if there were alt-text for the user icons, so that, upon hover, more information could be giving about what each icon means.

Alternatively, a short guide could be placed under `settings > about` somewhere.

EDIT: While responding to this, could a developer also include a description of what the icons mean in a post here? That might bubble up into the search results, so if people Google, they can get info from here.

**Comment by maksis** [comment]
Sure, that should be doable.

### Main color/icon

Green: online
Yellow: away
Blue: bot
Grey: offline
Red ban: messages ignored

### Corner icons

Key: operator
Blue star: self
Red plug: no connectivity with the user
Orange shield: passive user

**Comment by whispy** [comment]
Thanks for the quick response and info on the icons!
