### ISSUE TITLE
Ignore/Unignore messages doesn't work

### ISSUE THREAD

**Issue by Answer-Man** [airdcpp-web/airdcpp-webclient#234]
### Current UI and client versions:
Application version : AirDC++w 2.0.1 x86_64
Web UI version : 2.0.3
Web UI build date : May 9, 2017 1:45 PM
API version: 1

UA : Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
### Operating system:

Debian Linux 8

### Steps to reproduce the issue:

Simply ignore a client on the hub and it won't work.

**Comment by maksis** [comment]
Are you trying to ignore an operator?

**Comment by Answer-Man** [comment]
An annoying Bot that has more rights than me.

**Comment by maksis** [comment]
Yeah, ignoring operators didn't actually work so I've disabled the ignore option for them again. Please follow https://github.com/airdcpp-web/airdcpp-webclient/issues/221 for future updates.
