### ISSUE TITLE
Apache reverse proxy

### ISSUE THREAD

**Issue by GieltjE** [airdcpp-web/airdcpp-webclient#235]
### Current UI and client versions:

Application version
AirDC++w 2.0.1 x86_64
Web UI version
2.0.3
Web UI build date
May 9, 2017 2:45 PM

[ebuild   R    ] net-p2p/airdcpp-webclient-2.0.1::gentoo  USE="tbb webui -nat-pmp" 0 KiB
[ebuild   R    ] www-apps/airdcpp-webui-2.0.3::gentoo  0 KiB

### Operating system: 
Gentoo
### Result:
Invalid authorization token (session expired?)
### Steps to reproduce the issue: 
Proxy via apache with the following config (worked fine for older versions):

        <Location /airdcpp>

                RewriteEngine On

                RewriteCond %{HTTP:Upgrade} =websocket

                RewriteRule /airdcpp/(.*) ws://localhost:5600/$1 [P,L]

                RewriteCond %{HTTP:Upgrade} !=websocket

                RewriteRule /airdcpp/(.*) http://localhost:5600/$1 [P,L]

                ProxyPassReverse http://localhost:5600/
        </Location>

The webserver runs fine without the proxy, but apache handles ssl+digest auth so it's really handy.

Guess it has something to do with the authentication header, but I cannot find a way to succesfully remove it.

**Comment by maksis** [comment]
Does this help: http://stackoverflow.com/questions/4428903/remove-basic-authentication-header-with-apache-mod-proxy

**Comment by GieltjE** [comment]
Yes, now I feel stupid.

Please feel free to post the following code to the documentation so we can help other people:

        <Location /airdcpp>

                RewriteEngine On

                RequestHeader unset Authorization

                RewriteCond %{HTTP:Upgrade} =websocket

                RewriteRule /airdcpp/(.*) ws://localhost:5600/$1 [P,L]

                RewriteCond %{HTTP:Upgrade} !=websocket

                RewriteRule /airdcpp/(.*) http://localhost:5600/$1 [P,L]

                ProxyPassReverse http://localhost:5600/

        </Location>

Another possibly stupid question, is there a way to disable the authentication as this is performed by apache (I don't mean passing the credentials, just a default user would suffice).

**Comment by maksis** [comment]
That's not currently possible 

https://github.com/airdcpp-web/airdcpp-webclient/issues/186
https://github.com/airdcpp-web/airdcpp-webclient/issues/151

**Comment by GieltjE** [comment]
Ok, i've at least voted for them.
Would you consider adding the code snippet to the documentation for other people?

**Comment by maksis** [comment]
Hmm, I'm not sure if putting configs for third-party software that I'm not fully familiar with is the best solution in terms of maintenance. Possibly they could be kept on the tracker and I could add a generic link to the docs: https://github.com/airdcpp-web/airdcpp-webclient/labels/examples

That would also allow people to report issues/ask questions in the same thread and the config author would generally be notified about those.

**Comment by GieltjE** [comment]
Sounds like a good plan, might also encourage contributions,

**Comment by sbraz** [comment]
@maksis what about using GitHub's wiki?

**Comment by maksis** [comment]
> @maksis what about using GitHub's wiki?

That's a great idea. I've moved the example config provided by @GieltjE to https://github.com/airdcpp-web/airdcpp-webclient/wiki/Apache-proxy-configuration and added a link to it at https://airdcpp-web.github.io/docs/advanced/http-proxy.html.
