### ISSUE TITLE
Cannot share same directories in different profiles anymore

### ISSUE THREAD

**Issue by YamashitaRen** [airdcpp-web/airdcpp-webclient#236]
Back in the time I created two profiles.
1) Default Profile : /path/to/my/files/subdir
2) Profile 2 : /path/to/my/files

Idea was to share everything on one adc hub and share only the subdir on one nmdc hub.

Today, I can't add directories already shared in Profile 2 to the Default Profile. I get "Path is shared already" error. I'd like to be able to, like in the past.

**Comment by YamashitaRen** [comment]
My memory is a bit hazy but maybe I used symlinks to work around the issue back in the time...
So this may be feature request instead of a regression...

**Comment by maksis** [comment]
The feature was just a bit too time consuming to maintain and prone to bugs. It would also complicate the share API (and also the internal usage): if you had a file `/mnt/disk1/share/subdir/file` shared like that, it would also mean having multiple virtual (filelist) paths for it (e.g. `/share/subdir/file1` and `/subdir/file1`). Currently each real path only has a single virtual path, which simplifies things a lot.

Isn't that possible solve by using symlinks?

**Comment by YamashitaRen** [comment]
Yeah using symlinks is okay. Just needed to remember that I could workaround the issue like that...

**Comment by maksis** [comment]
Maybe the application could show a hint for the workaround in such cases...

**Comment by YamashitaRen** [comment]
That's an interesting idea.
