### ISSUE TITLE
Cross-sharing of non-listed data

### ISSUE THREAD

**Issue by Answer-Man** [airdcpp-web/airdcpp-webclient#237]
### Current UI and client versions:

Application version : AirDC++w 2.0.1 x86_64
Web UI version : 2.0.3
Web UI build date : May 9, 2017 1:45 PM
API version: 1

UA : Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

### Operating system:

Debian Linux 8

### Steps to reproduce the issue:
I will designate two hubs,  3 users and 2 profiles for this demonstration, the first user being me, the other two are simply users of the second hub,
Server 1: adcs hub
Server 2: nmdc hub
User 1: Present on Server 1 and 2
User 2: Present on Server 2
User 3: Present on Server 2
Profile 1: Used profile for Server 1
Profile 2 (Default Profile) : Used profile for Server 2

- Create two different profiles for 2 two different servers as described above. 
- Choose different shared content. for those two profiles.
- Now as User 2, seek for a file that exists in Profile 1 and that is available on Server 2. 
_Let's assume here that User 3 has that file._
- Download the file from User 3. 

Happens : User 1 is seeding for User 2 on Server 2 non listed content (coming from Profile 1) through a workaround. User 1 is directly considered as a source.
Expected : User 2 shouldn't be able to see User 1 as a source, and even less download from him. 
Profile 1 must remain exclusive for Server 1 as well as Profile 2 for Server 2 without any cross-sharing possibility.

**Comment by maksis** [comment]
Does User 1 have the uploaded content also in his download queue (e.g. did he download it only recently)?

**Comment by Answer-Man** [comment]
Yes, it's in my download queue (Status: Shared).

**Comment by maksis** [comment]
Files in queue are separate from shared files (and share profiles) and they are available to all users when searching by TTH. Note that it wouldn't even always be possible to connect queued content to a share profile as files can be downloaded outside of shared directories.

**Comment by maksis** [comment]
Oh, I'd like to add that obviously the queued files are not available in hubs where the "Share hidden" option has been selected

**Comment by Answer-Man** [comment]
So this is how it's meant to be ? Isn't possible to make the queued files related to Profiles ?

**Comment by maksis** [comment]
Yeah, it's working like that by design (it should be mentioned in the UI though).

I'd really like to know your use case and why you never want those files to be uploaded via the other (sharing) hub.

**Comment by Answer-Man** [comment]
Actually, I want to have total control on what I would like to share or not and to whom I'm sharing. As I can't limit my bandwidth by hub, I'm not willing to make a bigger community take advantage of the bandwidth I'm reserving to others.

**Comment by maksis** [comment]
I'll add an option to disable partial sharing and add additional information about the feature. Disabling partial sharing will obviously mean that you won't either be able to download partially shared files from other users.

**Comment by maksis** [comment]
This will be available in the next version
