### ISSUE TITLE
develop build error

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#238]
exceptioninfo.txt

Time: 01:28:51 PM
OS version: Linux 3.16.0-4-amd64 (x86_64)
Client version: AirDC++w 2.0.2b-29-gd915

/usr/local/bin/airdcppd in function cow::StackTrace::generate_frames() in file /data/airdcpp-webclient/airdcppd/stacktrace.cpp:44 [0x419bd3]
/usr/local/bin/airdcppd in function __copy_move_a2<false, __gnu_cxx::__normal_iterator<cow::StackFrame*, std::vector<cow::StackFrame> >, std::os$
/usr/local/bin/airdcppd in function installHandler()::{lambda()#1}::_FUN() in file main.cpp:0 [0x4176fb]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 in function [unknown] [0x7fecef9bfbb6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 in function [unknown] [0x7fecef9beca9]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 in function __gxx_personality_v0 [0x7fecef9bf40b]
/lib/x86_64-linux-gnu/libgcc_s.so.1 in function [unknown] [0x7fecef3afff3]
/lib/x86_64-linux-gnu/libgcc_s.so.1 in function _Unwind_Resume [0x7fecef3b0517]
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::detail::do_throw_error(boost::system::error_code const&) [0x7fecf089e760]
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function webserver::SystemUtil::normalizeIp(std::string const&) [0x7fecf089e393]
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function void webserver::WebServerManager::handleHttpRequest<websocketpp::server<websocketpp::confi$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function std::_Function_handler<void (std::weak_ptr<void>), std::_Bind<std::_Mem_fn<void (webserver$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function std::function<void (std::weak_ptr<void>)>::operator()(std::weak_ptr<void>) const [0x7fecf0$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function websocketpp::connection<websocketpp::config::asio_tls>::process_handshake_request() [0x7fe$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function websocketpp::connection<websocketpp::config::asio_tls>::handle_read_handshake(std::error_c$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function websocketpp::transport::asio::connection<websocketpp::config::asio_tls::transport_config>:$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::detail::completion_handler<boost::asio::detail::binder2<std::_Bind<std::_Mem_$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function void boost::asio::detail::strand_service::dispatch<boost::asio::detail::binder2<std::_Bind$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function std::_Function_handler<void (boost::system::error_code const&, unsigned long), boost::asio$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boo$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boo$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::tas$
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::detail::task_io_service::run(boost::system::error_code&) [0x7fecf08b78d1]
/usr/local/lib/libairdcpp-webapi.so.2.0.1 in function boost::asio::io_service::run() [0x7fecf08b8296]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0 in function [unknown] [0x7fecee40eaea]
/lib/x86_64-linux-gnu/libpthread.so.0 in function [unknown] [0x7fecf04d5064]
/lib/x86_64-linux-gnu/libc.so.6 in function [unknown] [0x7fecef69e62d]

**Comment by maksis** [comment]
Fixed
