### ISSUE TITLE
[Admin] Add in the click context menu admin options

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#241]
Hello

Is it possible to add admin command (kick/ban/…) to the list of when we do a click on an user (with send message/browse share)?

Thank you very much!

**Comment by maksis** [comment]
Possibly this could be implemented with extensions: https://github.com/airdcpp-web/airdcpp-webclient/issues/339

**Comment by maksis** [comment]
This should now be possible with an extension in version 2.8.0. Maybe you could ask in https://github.com/peps1/airdcpp-user-commands if such functionality would fit the project.
