### ISSUE TITLE
https ???

### ISSUE THREAD

**Issue by alexsalex** [airdcpp-web/airdcpp-webclient#242]
### Current UI and client versions:

Application version
AirDC++w 2.0.1 x86_64
Web UI version
2.0.3
Web UI build date
May 9, 2017 5:45 AM
API version
1
API feature level
0
Started
13 minutes ago
Active sessions
1
Server threads

### Operating system:

Ubuntu 16.04

### Steps to reproduce the issue:

I have .pem certs from let's encrypt. I want to use this serts fo acsess to airdcpp on port 5601 over https. Pls, help with set up. Where I have to put .pem files?

With my setup a had error like this:
[2017-06-09 08:45:18] [error] handle_transport_init received error: TLS handshake failed
[2017-06-09 08:45:18] [fail] WebSocket Connection 172.123.321.123:61122 - "" - 0 websocketpp.transport.asio.socket:8 TLS handshake failed

What I did wrong?

**Comment by maksis** [comment]
If you are affected by bug #243, please try the latest develop build from http://web-builds.airdcpp.net/develop/

**Comment by alexsalex** [comment]
Yes, same bug.
For me airdcpp is realy important service. When you plan to realise version without this bug?

**Comment by maksis** [comment]
They are inside the settings directory in the directory `Certificates`. I'm not sure that how Let's encrypt will work with file transfers though so I recommend using the linked develop builds instead (there are no plans for a new release yet).

**Comment by maksis** [comment]
@alexsalex were you able to solve the issue?

**Comment by alexsalex** [comment]
@maksis no. I put certs in Certificate folder, in web interface I put just only filenames. But it still doesn't work... Like I sad before, for me airdc critical service, I can't update it on testing brunch.

**Comment by maksis** [comment]
If you look at the commit log, this is the only change that has been made after the release of version 2.1.0: https://github.com/airdcpp-web/airdcpp-webclient/tree/develop (and it's a single line edit)

I don't think that you should be too worried with the update.

**Comment by maksis** [comment]
Closing as the actual bug should be fixed
