### ISSUE TITLE
certificate path validation

### ISSUE THREAD

**Issue by jahrock** [airdcpp-web/airdcpp-webclient#243]
Thanks for looking at this.
Not sure if this issue is related to ticket #242

Since I did upgrade my AirDC++w from 1.4.x to 2.x.x I recognized that HTTPS support was broken.
AirDC++w does store rewritten information to WebServer.xml while saving the configuration values.
Even on startup AirDC++w does rewrite the WebServer.xml file.

#### Application version
AirDC++w 2.0.1 x86_64
or
AirDC++w 2.1.0 x86_64

#### Web UI version
2.1.0

#### Operating system:
DSM @ Synology NAS

#### OS Docker Container by gangefors
gangefors/docker-airdcpp-webclient

#### Client
Chrome v57.0.2987.133 @ Windows

#### Install from gangefors/docker-airdcpp-webclient

1. AirDC++w 2.0.1 or AirDC++w 2.1.0
2. Login to WebUI
3. Goto System - Server Settings
4. Set certificate path and key path in your WebUI
- Certificate path -> /.airdcpp++/Certificates/letsencrypt/cert.pem
- Certificate key path -> /.airdcpp++/Certificates/letsencrypt/privkey.pem. 
9. Save changes

#### Expected configuration on WebUI
Port ->5601
Bind address -> 0.0.0.0
Certificate path -> /.airdcpp++/Certificates/letsencrypt/cert.pem
Certificate key path -> /.airdcpp++/Certificates/letsencrypt/privkey.pem

#### Displayed configuration on WebUI
Port ->5601
Bind address -> 0.0.0.0
Certificate path -> _.airdcpp++_Certificates_letsencrypt_cert.pem
Certificate key path -> _.airdcpp++_Certificates_letsencrypt_privkey.pem

#### Content of WebServer.xml
`<?xml version="1.0" encoding="utf-8" standalone="yes"?>`
`<WebServer>`
`	<Config>`
`		<Server Port="5600"/>`
`		<TLSServer Port="5601" Certificate="_.airdcpp++_Certificates_letsencrypt_cert.pem" CertificateKey="_.airdcpp++_Certificates_letsencrypt_privkey.pem"/>`
`	</Config>`
`	<WebUsers>`
		...
`	</WebUsers>`
`</WebServer>`

**Comment by maksis** [comment]
Paths were validated incorrectly indeed, which has now been fixed in the develop branch

**Comment by jahrock** [comment]
Awesome, thank you very much

**Comment by alexsalex** [comment]
Exactly the same problem. I didn't post it, but the path to certs were change like in your post.
