### ISSUE TITLE
RSS Feed Widget infinite loading

### ISSUE THREAD

**Issue by Answer-Man** [airdcpp-web/airdcpp-webclient#245]
### Current UI and client versions:
Application version
AirDC++w 2.1.0 x86_64
Web UI version 2.1.0
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
### Operating system:
Windows 10

### Steps to reproduce the issue:
Add an RSS Feed Widget containing this url: http://fetchrss.com/rss/594351de8a93f8976a8b4567579713941.xml
It will infinitely load and won't display anything.

**Comment by maksis** [comment]
Yeah, seems like only the first 10 items in that feed have a title and the rest have nothing

**Comment by maksis** [comment]
It's an invalid feed, which should be detected by the client: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffetchrss.com%2Frss%2F594351de8a93f8976a8b4567579713941.xml

**Comment by Answer-Man** [comment]
Ah ok, thanks then.

**Comment by maksis** [comment]
Yes, the next UI version will handle such cases correctly
