### ISSUE TITLE
Character not supported ":"

### ISSUE THREAD

**Issue by Answer-Man** [airdcpp-web/airdcpp-webclient#246]
### Current UI and client versions:
AirDC++w 2.1.0 x86_64
Web UI version 2.1.0
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
### Operating system:
Debian Linux 8
### Steps to reproduce the issue:
Create a folder and choose a name containing the character ":"
E.g: DanMachi:Sword.Oratoria.S01 is replaced by DanMachi_Sword.Oratoria.S01

**Comment by maksis** [comment]
This will be possible in the next version. However, I wouldn't recommend using colon in shared file/directory names as it's a reserved character on various operating system (e.g. Windows and macOS).
