### ISSUE TITLE
Advanced DC++ doesn't seem to work with PtokaX hubs--will there be testing/fixing?

### ISSUE THREAD

**Issue by dchmelik** [airdcpp-web/airdcpp-webclient#249]
I said (then maksis replied: )
>>One says PtokaX DC Hub 0.5.2.1.
>
>Thanks, that's what I wanted to know. I'm not aware of any special issues caused by that hubsoft, unless it has been configured to block transfers. The hubsoft is written for a legacy protocol though, which may cause different types of issues. You may always connect to the dev/support hub at adcs://web-dev.airdcpp.net:1511 and ask for someone to try browsing your filelist. [...]

So, no Advanced DC++ software I tried (AirDC++, EiskaltDC++, LinuxDC++) worked with those PtokaX hubs, but after conversation above, I was able to use AirDC++ web-client with the AirDC++ developers' hub just fine, then didn't do/change anything else until trying PtokaX hubs, and they put me in passive mode. This does seem to be a problem of the legacy protocol. Are there any plans to test that and see how AirDC++ could be fixed, or if just PtokaX is incompatible now, or if you have to do certain setup? (I tried all sorts of stuff, like running on ports only up to 32,000, or using port 412 for the two main things and 413 for TLS as descriptions of old protocols seemed to imply you should do.)

**Comment by maksis** [comment]
Ptokax is the hubsoft that I use for testing NMDC compatibility, so it should be working just fine. However, hubs use different settings that may also affect transfers. In how many Ptokax hubs have you tested downloading? Can you download from users in hub dchub://dc-united.sytes.net:4111 that I've confirmed to be working correctly with AirDC++?

**Comment by dchmelik** [comment]
Two hubs earlier, now the one you mentioned. There I couldn't get a list from other passive users, which according to another hub administrator means I have a problem. I.e., the hub you mentioned also puts me in passive mode, so basically I can't share much. So, I have the same problem there.

**Comment by maksis** [comment]
So you are passive in NMDC hubs but active in ADC hubs? That's new to me. Are you having the issue with other NMDC hubsofts? Hubs to test: johtajat.no-ip.org (Aquila), talsi.sytes.net  (Verlihub)

Additional information that might be helpful (can also be sent privately in the dev hub):

- Your full IPv4 connectivity settings
- Full protocol messages including the hub connect process and initiating of the transfer connection (you can view those in the server console after starting the client with `--cdm-hub` and `--cdm-client` parameters)

**Comment by dchmelik** [comment]
Situation is same on those two hubs: I was passive, couldn't get file list from passive users after several minutes. These are my IPv4 settings: router with static IP address 206.63.237.146 (which my PC also has when I check sites that give your IP address,) and entered in AirDC++ web-client ‘External/WAN IP.’  My PC's LAN address is 192.168.1.101 (which I have set static from the router) and shown in ifconfig, and entered in AirDC++ web-client ‘bind address.’  I opened ports 30000 (TCP & UDP) and 30001 (TCP) in the router and entered those for the three AirDC++ ports (well, 30000 used for the first two and 30001 for TLS.)

**Comment by maksis** [comment]
I'd like to get the protocol messages and possibly your DCPlusPlus.xml file as well as I don't currently know that what's happening there

**Comment by maksis** [comment]
Oh, and obvious question: does this also happen if you connect to those hubs with a clean installation without any manual config?

**Comment by dchmelik** [comment]
Yes. After that (and copying & pasting the random ports into a router port open line, triple-checking them and also the LAN address and protocols) it also connects me as passive on all hubs. Earlier, I had copied the decompressed tarball's directory into /usr/local, and at least my manual setup worked with your hubs. This time, I found more of your installation guide (not sure it's in the tarball) and did the 'sudo make install' instead of copying the folder, but apparently something went wrong with the automatic setup.

**Comment by dchmelik** [comment]
I found the file, but don't know where those messages are; what should I do next?

**Comment by maksis** [comment]
> I found the file, but don't know where those messages are

See https://github.com/airdcpp-web/airdcpp-webclient/issues/249#issuecomment-310832458

**Comment by dchmelik** [comment]
So apparently you mean a standard OS terminal console with a shell, not a console within airdcppd...  Ok; I'll look at that.  Is it safe to upload that XML file as it is (only, it doesn't have my password, right?) in another comment here? (or you want me to use that Github pastebin?)

**Comment by maksis** [comment]
> Is it safe to upload that XML file as it is (only, it doesn't have my password, right?)

Web server passwords aren't stored in that file but you might still want to skim it through. I wouldn't paste large text files directly into comments but it's ultimately up to you.

**Comment by dchmelik** [comment]
Ok, where's preferred to paste?  Yeah, output on the console will also be big... do you want it from all test servers mentioned previously?

**Comment by dchmelik** [comment]
[DCPlusPlus.xml](https://gist.github.com/dchmelik/94db50271d8084edebe77c822f385801)
[AirDC++ log](https://gist.github.com/dchmelik/600d5a5b2080d7d3f3af7423fa2e24e0)

**Comment by maksis** [comment]
There is no protocol communication in the log. Some clarifications to comment https://github.com/airdcpp-web/airdcpp-webclient/issues/249#issuecomment-310832458:

- Launch the application with command `airdcppd --no-auto-connect --cdm-hub --cdm-client > output.txt`
- Connect to a hub that is causing issues. To minimize the amount of extra protocol messages, you should rather connect to a small hub. Note that all information exchanged between the application, hubs and other clients will be logged so I don't recommend testing with the most secret hub you have (or with hubs where you have a registered account).
- Quit the application and upload the generated log

**Comment by maksis** [comment]
Update: launch with `airdcppd --no-autoconnect --cdm-hub --cdm-client > output.txt` that will skip the hub auto-connect correctly (the parameter name listed in `--help` is incorrect)

**Comment by dchmelik** [comment]
Oops, ok, I replaced my old gist log of that with a new [file](https://gist.github.com/dchmelik/600d5a5b2080d7d3f3af7423fa2e24e0).

**Comment by dchmelik** [comment]
Did anyone check my revised file?  Is it taking a lot of debugging, or people forgot?

**Comment by maksis** [comment]
The active flag is being sent correctly to the hub and the hub forwards it correctly as well, so everything looks normal there. 

Additional questions:

- What kind of system are you running the client on (operating system, CPU...)?
- Are you using the precompiled binary or have you compiled one by yourself? (you could test both)
- Are you able to test the app on other systems? In case you have a Windows machine available,  have you tested the Windows app?

**Comment by dchmelik** [comment]
I'm running precompiled airdcppd-webclient on a stable major GNU/Linux OS distribution with i6700K CPU.  Before, I had compiled airdcppd-webclient, realized I didn't have to, then uninstalled & reinstalled.  I can't test on anything else now... maybe a BSD, later, if available.

**Comment by maksis** [comment]
Next version should display the the connectivity mode correctly for own user in NMDC hubs (I'm not sure if actual transfers were affected)
