### ISSUE TITLE
HTTPS with Let's Encrypt certs. 

### ISSUE THREAD

**Issue by Ve0** [airdcpp-web/airdcpp-webclient#250]
Did you fix it in 2.1.0 ver?

**Comment by alexsalex** [comment]
Still problem....
`_etc_letsencrypt_live_p.dazab.club_fullchain.pem`

**Comment by maksis** [comment]
This is fixed in the develop builds (https://github.com/airdcpp-web/airdcpp-webclient/issues/242)
