### ISSUE TITLE
HTTP disabling not allowed via webclient

### ISSUE THREAD

**Issue by Answer-Man** [airdcpp-web/airdcpp-webclient#252]
### Current UI and client versions:

AirDC++w 2.1.0 x86_64
Web UI version 2.1.0

### Operating system:

Debian Linux 8

### Steps to reproduce the issue:
While editing the web server system settings I've encountered an issue that prevents me from saving.
The minimum allowed value for the HTTP Port is set to 1 while it's recommended to set it to 0 to disable the protocol. 
Screenshot: [
![72e0433ba7 1](https://user-images.githubusercontent.com/21156699/28557451-d91166ac-710c-11e7-9ecf-e1c0e0094c6a.png)
](url)

**Comment by maksis** [comment]
There's an existing fix for this in the dev branch (https://github.com/airdcpp/airdcpp-webapi/commit/c92e63dcd9f910425a2c5e7e76a6d4cd7c1be759)
