### ISSUE TITLE
nginx reverse proxy and   auth_basic fails

### ISSUE THREAD

**Issue by Night1** [airdcpp-web/airdcpp-webclient#255]
### Current UI and client versions:
Application version
AirDC++ 3.42a-27-gd88f1 x64
Web UI version
2.2.0-beta.1

UI related issues should also include the browser version.

### Operating system:
Windows 10 Pro

Ngix running on a Ubuntu box

`nginx version: nginx/1.13.3
built by gcc 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)
built with OpenSSL 1.1.1-dev  xx XXX xxxx
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-pcre=../pcre-8.40 --with-zlib=../zlib-1.2.11 --with-http_ssl_module --with-openssl=../openssl --with-openssl-opt=enable-tls1_3 --with-http_gzip_static_module --with-http_addition_module --with-http_geoip_module --with-http_dav_module --with-http_stub_status_module --with-http_sub_module --with-http_ssl_module --with-stream --with-stream_ssl_module --with-mail=dynamic --with-http_v2_module
`
Nginx proxy for airdc looks like this 

```
     location /airdcpp/ {
          proxy_pass http://192.168.1.50:5600/;
          gzip_types text/plain application/javascript;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          auth_basic "Restricted";
          auth_basic_user_file /etc/nginx/.htpasswd;
     }
```

With this enabled after having input auth_basic credentials in Chrome I'm faced with this error

> Invalid username or password

Looks like AirDC is trying to use credentials passed thought auth_basic and not allowing me to input application username/password

**Comment by maksis** [comment]
This has been documented at https://airdcpp-web.github.io/docs/advanced/nginx-setup.html

**Comment by Night1** [comment]
Sorted, Thank you :)
