### ISSUE TITLE
Problem with nginx reverse proxy

### ISSUE THREAD

**Issue by spinza** [airdcpp-web/airdcpp-webclient#259]
### Current UI and client versions:
Application version
AirDC++w 2.2.1 x86_64
Web UI version
2.2.1
Web UI build date
October 8, 2017 9:52 AM
API version
1
API feature level
0
Started
25 minutes ago
Active sessions
1
Server threads
4

### Operating system:

ubuntu 17.10
nginx 1.13.3

### Steps to reproduce the issue:
I've run using a nginx reverse proxy for some time.  This is available at https://dcpp.example.com (say)
On upgrading to 2.2.1 I get blank screen when browsing to the site. 
I can access the site at http://dcpp.example.com:5600/ on my local network.
It doesn't work through proxy.

Fairly standard site conf:
```
server {
    listen 80;
    server_name dcpp.example.com;
    rewrite ^ https://$server_name$request_uri? permanent;
}


server {
        listen 443 ssl;

        ssl_certificate ....;
        ssl_certificate_key ...;

        server_name dcpp.example.com;

        location / {

                # Client URL (no need for HTTPS when using localhost)
                proxy_pass  http://localhost:5600/;

                # Gzipping javascript will reduce the transferred data significantly
                # This has no effect if gzip compression is disabled from nginx
                gzip_types      text/plain application/javascript;

                # Proxy websockets
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }

}
```

**Comment by maksis** [comment]
Version 2.2.1 is known to work with nginx. What was the version you upgraded from?

**Comment by spinza** [comment]
Sorry not sure.  Possibly 2 or 3 months ago I last upgraded.  The in browser error is:
`No session token available for reconnecting`

**Comment by maksis** [comment]
Is that the full console log? Have you tried clearing the browser cache or using a different browser?

**Comment by spinza** [comment]
I use Chrome.  It works in Firefox and also in incognito mode in Chrome.  Cleared the site cached and also cookies.  Also cached images and files.

Might be a extension?
