### ISSUE TITLE
Error on # cmake .

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#264]
I start with # make uninstall, then # git pull
and when running # cmake . I get this:

-- Installing Web UI
Wanted UI version 2.3.0-beta.1 is installed already
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBMAXMINDDB_LIBRARY (ADVANCED)
    linked by target "airdcpp" in directory /root/airdcpp-webclient/airdcpp-core

**Comment by maksis** [comment]
The list of dependencies has not been updated for 2.3.0 but you need to install libmaxminddb (`libmaxminddb-dev` on Ubuntu)
