### ISSUE TITLE
Download to default path doesn't work

### ISSUE THREAD

**Issue by acmodeu** [airdcpp-web/airdcpp-webclient#265]
OS:  4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
app version: airdcpp_2.3.0b-40-g413eb_webui-2.3.0-beta.1_64-bit_portable.tar.gz

**Download** to default path (w. green icon) doesn't do anything (the path is set in preferences), **download to...** (w. blue icon)  works as it supposed to.

**Comment by maksis** [comment]
This is now fixed in Web UI 2.3.0-beta.2
