### ISSUE TITLE
Creation Mask?

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#266]
Is there a way to set the file creation mask somehow?
I mean the default permissions on newly downloaded files...

**Comment by maksis** [comment]
No, that's hardcoded: https://github.com/airdcpp/airgit/blob/039e665aa1ceb6a4d511c2ee8c2542f69092ebad/airdcpp/airdcpp/File.cpp#L370

**Comment by KipourosV** [comment]
Any way or tips on how to circumvent this somehow?
Everytime I download new stuff, I need to manually change the permissions
on the files so other apps (plex, subsonic) can access the files... :(

**Comment by maksis** [comment]
Could you write a script that would regularly update the permissions of you downloaded data....?

I haven't heard of anyone else having such issue. Which creation mask do you need for those apps?

**Comment by KipourosV** [comment]
I'm running airdc in an LXC container, as I do with plex, transmission & subsonic.
All of the containers have a common bind mount on the datastore 
Airdc is the only one running as root user, so the new files it creates are owned
by root:root and have permisions 770, so I manually have to change permissions to 775
for the plex/subsonic user to have read access...

**Comment by maksis** [comment]
Yeah, you probably need to use external tools/scripts for the permissions (the application isn't really meant to be run as a root)

**Comment by KipourosV** [comment]
How do I change the user?

**Comment by maksis** [comment]
How do you run the app as another user? I don't know that how you are starting the application at the moment but https://www.cyberciti.biz/open-source/command-line-hacks/linux-run-command-as-different-user/ or similar guides might help.

**Comment by KipourosV** [comment]
I remember creating init.d script or something like that....
I need to do some digging...

**Comment by maksis** [comment]
Were you able to solve it?

**Comment by KipourosV** [comment]
Sorry for the late reply, I've beeen really busy.
I'm trying to locate the thread I followed to run as service.
In the service definition file,
in my case /etc/systemd/system/airdcppd.service
there is user and group definition and also umask which controls exactly that
(the permissions newly created files (by airdcpp) get)

Thanx
