### ISSUE TITLE
Only one hub profile allowed...

### ISSUE THREAD

**Issue by MattSessions** [airdcpp-web/airdcpp-webclient#270]
Hi. Love the docker version... just one issue for me... if i want to join more than one hub with a different NICK but the same shares i assume you can't. I guess that this means setting up a second Docker... thats a bit annoying...

Tried creating a new account in the docker but its the same settings... any way round this?

**Comment by maksis** [comment]
You can add the hubs in *Favorite hubs* and set a different nick for each one. Which version are you using?

**Comment by MattSessions** [comment]
Im such a noob! Figured it all out... just working my way around the UI.

**Comment by maksis** [comment]
Version 2.3.0 has an info message regarding adding the hubs in favorites so it should be less confusing to the users
