### ISSUE TITLE
Any good resources on how to upgrade versions??

### ISSUE THREAD

**Issue by MattSessions** [airdcpp-web/airdcpp-webclient#271]
Currently on version 2.2.1 in a Docker on a Synology NAS and looking to move to the new version... quick guide on the process would be amazing. Would like to keep all settings and account info etc.

**Comment by MattSessions** [comment]
OK so i followed a couple of websites online and tried to do an update by pulling the new image and transferring the setting from one docker to the next... restarted the new docker and this is where i realized that all the HashDB and core settings are stored on the Docker image? Why do this? I think the image should store app Core files away from the Docker and then you can just update the app without losing all you settings and most importantly the HASH DB

**Comment by maksis** [comment]
There is no official Docker image as part of this project. Which image do you use? https://github.com/gangefors/docker-airdcpp-webclient? You might want to post the question on their issue tracker.

**Comment by MattSessions** [comment]
Good call, thanks for the advice.
