### ISSUE TITLE
Support the author, hope to support Chinese language, thank you.

### ISSUE THREAD

**Issue by msmkls** [airdcpp-web/airdcpp-webclient#275]
### Current UI and client versions:

Copy from *Settings* -> *About*

UI related issues should also include the browser version.

### Operating system:

Name and version of the operating system on which the application is installed on

### Steps to reproduce the issue:

If you are unable to reproduce the issue, you can explain that what was happening before the crash/issue occurred. If it is a recurring issue, please mention how often does it occur.

**Comment by maksis** [comment]
I believe that this is part of https://github.com/airdcpp-web/airdcpp-webclient/issues/251

**Comment by maksis** [comment]
Localization support will be available in version 2.6.0
