### ISSUE TITLE
Instant airdpp-webclient crash in FreeNAS when trying to refresh a large share

### ISSUE THREAD

**Issue by ajshell1** [airdcpp-web/airdcpp-webclient#276]
I have a rather large shared folder, and I'm trying to share it. Whenever I try to refresh it, it instantly crashes. This happens EVERY time I try to refresh the share.

I'm using FreeNAS 11.1 U4, with the webclient in a jail.

Contents of exceptioninfo.txt
Time: 15:38:38
OS version: FreeBSD 11.1-STABLE (amd64)
Client version: AirDC++w 2.3.0

0x41d7b8 in function  [0x0000000]
0x41b22a in function  [0x0000000]
0x801c9578f in function  [0x0000000]
0x801c94d6f in function  [0x0000000]

**Comment by maksis** [comment]
Unfortunately the content of that exceptioninfo isn't really useful. Possibly you could also try attaching a debugger to the crashed process: https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#application-freezesdeadlocks

Are you able to share other (smaller) directories without issues? Have you added it in share earlier (and are the files hashed from it)? How large is the folder (size in bytes and number of files)?

**Comment by ajshell1** [comment]
I don't know what I did, but I recompiled it and now it doesn't do that anymore.

**Comment by ajshell1** [comment]
I figured out a clue: sometimes this happens on the latest verion of airdcpp-webclient, but only when I transfer files over via NFS (using Krusader). When I FTP the files over via Filezilla, this never happens.

**Comment by psychogun** [comment]
@ajshell1 care to share how you compiled airdcpp in jarl? I cannot seem to to find all the repositories; boost / stdc++ / pkg-config / zlib?

**Comment by psychogun** [comment]
@ajshell1 nevermind, I managed to compile it :)

**Comment by maksis** [comment]
@ajshell1 are you still experiencing these crashes?

**Comment by ajshell1** [comment]
@maksis  Not anymore.

I discovered that I don't get this issue when I transfer files over to my FreeNAS datasets via SFTP, but it does happen sometimes when I transfer them via NFS.

Thus, I've been exclusively using Filezilla for the time being.

Also, my host system I was transferring these files from was a Linux system.

**Comment by maksis** [comment]
I'll close the issue as it seems like no one else is experiencing the issue and there is no valid crash log available. If someone finds new information, feel free to reopen this.
