### ISSUE TITLE
[Extension] Unable to connect to API

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#279]
### Current UI and client versions:

**Application version:** AirDC++w 2.3.0 x86_64
**Web UI version:** 2.3.0

### Particularity of my instance

 -  it uses the portable binarie version
 - I access to airdcpp-web using the nginx proxy (https://airdcpp-web.github.io/docs/advanced/nginx-setup.html)

### Operating system:

Debian 9.4

### Steps to reproduce the issue:

1. Installing an extension, for example *airdcpp-release-validator* 
![screenshot_2018-05-16 airdc web client](https://user-images.githubusercontent.com/3000936/40144915-587cd1b0-5960-11e8-988a-e7c1cef85741.png)
1. Try to start it
1. it fails, the event message is: *Extension airdcpp-release-validator has exited (see the extension log `/home/<user>/airdcpp-webclient/config/extensions/airdcpp-release-validator/logs/error.log` for error details)*
1. `cat /home/<user>/airdcpp-webclient/config/extensions/airdcpp-release-validator/logs/error.log`:
```
[2018-5-16 12:13:42:997] Connecting socket failed
[2018-5-16 12:13:43:0] Failed to connect to server localhost:<PORT>/api/v1/, exiting...
```

`localhost:<PORT>` is the same than the one in my nginx proxy configuration

**Comment by maksis** [comment]
What do you see when you try run the following command on the same machine that the application is running on: `curl http://localhost:<PORT>/api/v1/`

**Comment by Kcchouette** [comment]
`$ curl http://localhost:<PORT>/api/v1/`
{"message":"Parsing failed: Not enough URL parameters"}

**Comment by maksis** [comment]
I tested running extensions on the latest Debian and it worked fine. Which version of node are you using (`nodejs -v` or `node -v`)? Which HTTP and HTTPS ports are you using?

**Comment by Kcchouette** [comment]
Remember that I use the portable version of airdcpp-web.
nodejs -v = v8.11.1
HTTP port 5690
HTTPS disable (Port = 0)

**Comment by maksis** [comment]
Could you try installing the latest version of `airdcpp-create-extension` to see if it works?

**Comment by maksis** [comment]
I've also released a new version of `airdcpp-release-validator`  and `airdcpp-message-emailer`. The catalog page may still show cached data with old version information but you should still get the latest one when you click Install.

**Comment by Kcchouette** [comment]
- New version of `airdcpp-release-validator` (0.2.2): same problem.
 - `airdcpp-create-extension` (0.1.4): same problem
 - `airdcpp-message-emailer` (0.0.7): exactly the same:

```
Extension airdcpp-message-emailer has exited (see the extension log /home/<user>/airdcpp-webclient/config/extensions/airdcpp-message-emailer/logs/error.log for error details)
```

```
$ cat /home/<user>/airdcpp-webclient/config/extensions/airdcpp-message-emailer/logs/error.log
[2018-5-17 13:27:38:275] Connecting socket failed
[2018-5-17 13:27:38:278] Failed to connect to server localhost:5690/api/v1/, exiting...
```

**Comment by maksis** [comment]
I just realized that you must have set the bind address to `localhost`. You could try using `127.0.0.1` or `[::1]` for now, as that should avoid the issue.

**Comment by Kcchouette** [comment]
I've updated the bind address in settings/system/server-settings **without restarting my instance**:
 - `127.0.0.1` occurs the same error:
```
[2018-5-17 18:16:10:994] Connecting socket failed
[2018-5-17 18:16:10:996] Failed to connect to server 127.0.0.1:5690/api/v1/, exiting...
```
 - `[::1]` is working:
```
This is a test message sent by extension airdcpp-create-extension 0.1.4. Please visit https://github.com/airdcpp-web/airdcpp-create-extension to find out how to develop more useful extensions than this.
```

**Comment by maksis** [comment]
> without restarting my instance

Yeah, you should restart the web server after such changes... but seems like it's working fine now. The actual bug will be fixed in the next version.
