### ISSUE TITLE
Feature request: Scrolling windows to remember their last position.

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#280]
Hello,

When going to hub chat, or to a personal message,
and browse up for example (to see what was mentioned in chat earlier),
and then you navigate away from that window,
when you get back to the same chat/window, the position of the chat resets
and you need to scroll back up to where you were.

Is it possible to make those scrolling windows, remember their last position?

Regards
Vassilis

**Comment by cirojr82** [comment]
Upvoted. I have this "problem" when I'm navigating a share that's too big. If I had to leave the filelist window for some reason, when I come back it loses track.

**Comment by maksis** [comment]
This will be implemented in version 2.9.0 for tables, message views and viewed text file
