### ISSUE TITLE
Spaces are not properly handled by airdcppd --configure

### ISSUE THREAD

**Issue by sbraz** [airdcpp-web/airdcpp-webclient#282]
### Operating system:

Gentoo Linux

### Steps to reproduce the issue:

* Run `airdcppd --configure`
* Type a username or a password containing spaces

Here's what happens if I type a password containing spaces:
```
Enter password (input hidden): 
Retype password: 
Passwords didn't match

No valid configuration was entered. Please re-run the command.
```

It looks like the part after the space is interpreted as the password confirmation. The same thing happens for the username: the part after the space is interpreted as the password.

**Comment by maksis** [comment]
Fixed
