### ISSUE TITLE
!commands aren't understood by the HUBs.

### ISSUE THREAD

**Issue by cirojr82** [airdcpp-web/airdcpp-webclient#285]
### Current UI and client versions:

AirDC++w 2.3.0 armv7l

### Operating system:

Dietpi

### Steps to reproduce the issue:

When I log on in a HUB and they ask to register fisrt, with commands like !regme <password>, the hub doesn't recognize the command as it should.

Whereas I try to send a !command to a HUB, it doesn't understand as command, but as a normal chat.

**Comment by maksis** [comment]
Commands are sent as normal messages and it's up to the hub to handle them correctly. Have you contacted the operators in that hub for help? It sounds like an issue with the hub.

**Comment by cirojr82** [comment]
Thanks Maksis, I found out the problem. Yes, it's not a problem with AirDC actually, the problem is the HUB doesn't allow passive user to send messages. Thanks anyway.

BUT, I have another question, it's a about "fonts". I'll attach prints to explain better, but when I log on the HUB I can't understand any word of the writings, while I log on the same hub using another cliente, I can read the texts. Is there a way to solve this.
![selecao_009](https://user-images.githubusercontent.com/13918940/42728410-25e1937c-8790-11e8-9208-18ca90ae7b88.jpg)
![selecao_010](https://user-images.githubusercontent.com/13918940/42728423-4fb07b14-8790-11e8-97e9-0c385cb86b95.jpg)


PS: If I need to open antoher post, just tell me and close this one and open a new one.

**Comment by maksis** [comment]
You could try changing the NMDC encoding from Settings -> Profile -> Miscellaneous. If it won't help, feel free to open a new issue.
