### ISSUE TITLE
Add in the ability to set the IP for each favourite hub

### ISSUE THREAD

**Issue by dandantheflyingman** [airdcpp-web/airdcpp-webclient#286]
Feature Request.

In the AirDC full client, you are able to set the IP (v4 and v6) on a per-favourite hub basis:
![image](https://user-images.githubusercontent.com/19147435/46137592-4cd4ec80-c28d-11e8-8923-8cb578345f8d.png)

This is very useful for me as I have my client connected to two hubs, one that is an internet accessible hub, and one that is only available on our LAN. If I force the LAN IP address in the settings, then the Internet hub doesn't work, and vice versa. 

This feature exists in the full client, and is set in the Favorites.xml with the UserIP="x.x.x.x" setting. I have tried to change this value in the Favorites.xml file directly, but the AirDC-webclient doesn't seem to apply it.

I am open to suggestions if there is another way to achieve this - through routing or DNS addresses. When I tried using a DNS name in the general IPv4 address for the client, what was advertised to other clients was always a IP address rather than a DNS name, so I couldn't do any sort of split-dns routing..

Thanks

**Comment by maksis** [comment]
This will be implemented in the next release
