### ISSUE TITLE
Single missing File from Queue Bundle blocks complete Download from User

### ISSUE THREAD

**Issue by TheEvil-zz** [airdcpp-web/airdcpp-webclient#287]
### Current UI and client versions:
Application version
AirDC++w 2.3.0 x86_64
Web UI version
2.3.0
Web UI build date
March 11, 2018 2:57 PM
API version
1
API feature level
0

### Operating system:

CentOS Linux release 7.5.1804 (Core)

### Steps to reproduce the issue:

When you Queue a whole Folder with multiple Files and the Source deletes one of the files from this Folder it blocks the whole Transfer with this User when the file is selected to transfer.
The transfer stuck at "File Missing xyz" and it didn't continue with the next available file

**Comment by maksis** [comment]
Thanks, it was broken indeed in NMDC hubs. This will be fixed in the next version.

**Comment by maksis** [comment]
The fix is also available in http://web-builds.airdcpp.net/develop/airdcpp_2.4.0b-54-gd7b5_webui-2.4.0-beta.5_64-bit_portable.tar.gz
