### ISSUE TITLE
Temporary directory

### ISSUE THREAD

**Issue by Revenger** [airdcpp-web/airdcpp-webclient#288]
Issue "Make directory for temporary files selectable #139" in 2016 talked about this but was closed by maksis  as "The final destination directory is used also for temp files so having such option isn't applicable."

I believe the option of a temporary directory is applicable which the reasons were probably overlooked by maksis.

As a user on a NAS I am looking at setting up AirD++ to see if its viable for my needs.

The option of a temporary directory is applicable to not lump all files unfinished and finished into a single folder which makes organisation worse as I know back when I was lanning regularly.

In the Documentation "HOWTO : A beginners guide to AirDC++" by by en_dator » 05 Nov 2008, 22:31
There is a temporary directory in the main client,
"Downloads tab
Here you select a default folder for your downloads and a folder where your temporary files will be while they are being downloaded."

This is the whole reason for a temporary directory to split downloaded and incoming files up.

Most services use a structure to keep things neat and tidy.

The DC++ directive for this is:
"< TempDownloadDirectory type="string">/Downloads/Incoming/</ TempDownloadDirectory>"

Adding it to the config file and making any change in the web config and saving this line gets removed from the config.

Whether it will work without saving any changes in the UI I haven't tested as I am still setting things up.

The logic that the incoming files should be in the same folder as finished files and is adequate, isn't sound for those who download loads of files especially terabytes at lans etc, and want to nearly be able to see whats fully down and isn't especially when manually cleaning up files to proper shares.

**Comment by maksis** [comment]
That feature was removed mainly because of maintenance costs. Note that the application has support for extensions so it would also be possible to write an extension that will move completed bundles (or individual files) from the target location to another directory.

**Comment by maksis** [comment]
It should be possible to write an extension for this.

The extension could change the target directory of the bundle to a temp directory: https://airdcpp.docs.apiary.io/#reference/queue/validation-hooks/add-bundle

After the bundle has finished downloaded, it can move the files to the correct destination directory and trigger a refresh. It can even be shared without hashing by calling https://airdcpp.docs.apiary.io/#reference/hashing/methods/rename-path

Alternatively it would be possible to write the extension in a way that all bundles are queued in to the default download directory and then extension is able to detect the correct final destination directory automatically based on the bundle name/content.
