### ISSUE TITLE
Got this trying to upgrade...

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#294]
root@pve1:~# pct enter 102
root@airdcpp-web:~# cd airdcpp-webclient/
root@airdcpp-web:~/airdcpp-webclient# make -j8
[ 59%] Built target airdcpp
[ 96%] Built target airdcpp-webapi
[ 96%] Linking CXX executable airdcppd
../airdcpp-core/libairdcpp.so.2.4.1b: undefined reference to `SSL_is_init_finished'
../airdcpp-core/libairdcpp.so.2.4.1b: undefined reference to `dcpp::ssl::X509_digest(x509_st*, env_md_st const*)'
collect2: error: ld returned 1 exit status
airdcppd/CMakeFiles/airdcppd.dir/build.make:217: recipe for target 'airdcppd/airdcppd' failed
make[2]: *** [airdcppd/airdcppd] Error 1
CMakeFiles/Makefile2:461: recipe for target 'airdcppd/CMakeFiles/airdcppd.dir/all' failed
make[1]: *** [airdcppd/CMakeFiles/airdcppd.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
root@airdcpp-web:~/airdcpp-webclient#

**Comment by maksis** [comment]
That shouldn't be caused by changes made in 2.4.1b. Could you try cloning it into a new directory with no previous build files and see if it helps?

**Comment by KipourosV** [comment]
You were right, deleting the dir and starting clean fixed it!
Thanx!!!
