### ISSUE TITLE
Random inserting old chat text

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#295]
### Current UI and client versions:

Application version: AirDC++w 2.4.0 x86_64
Web UI version: 2.4.0

Browser: Mozilla Firefox 64.0b9 (latest beta version as 15 November 2018)

### Operating system:

debian 9.6

### Steps to reproduce the issue:

No idea for the moment.

Here a screenshot of the bug:
![the bug](https://user-images.githubusercontent.com/3000936/48587100-37497e00-e932-11e8-9b1e-6da27ea94d7a.png)

And here the same thing, after a refresh of the airdcpp url (F5): no bug
![no more bug](https://user-images.githubusercontent.com/3000936/48587151-67911c80-e932-11e8-812d-cc782adb834a.png)

**Comment by maksis** [comment]
This might be fixed by https://github.com/airdcpp-web/airdcpp-webui/commit/1f61f93512019ab70fe574b025a4298e383bb7ad already
