### ISSUE TITLE
IMPROVEMENT : To have in SHARE an option to choose how to hash each "volume" and manuallly start stop it per volume

### ISSUE THREAD

**Issue by felisucoibi** [airdcpp-web/airdcpp-webclient#300]
Exmple, i have 5 volumes, i know what kind of topology has each volume, like is a separate volume, or this raid is slow, this one is fast.. so i can choose how many threads to hash each volume, start/stop hashing of each volume manually, etc, now i'm trying to figure out how to make one thread for each volume, and the 5 volumes to start to hash or stop, by now i figured out that refreshing file lists makes some volumes to start hashing, sometimes... i think the same as start refreshing file list for start hashing manually or stop it could be nice, and choose how many threads per volume.

I know there is a global config that sould take care of this, but starts hashing randomly each volume, and for a reason i do't know wjy it don't start the 5 volumes, just 3 of them...

My global config is:

max 25 threads
1 thread per volume.

Also seems when refreshing a volume filelist, it stop hashing the rest of the volumes. why?

**Comment by maksis** [comment]
How often do you hash files simultaneously from multiple volumes?

**Comment by felisucoibi** [comment]
Hi, all the time, maybe i'm a special case, but i hash all the time, and i have to choose wich drive (raid) use, so i need more control of the threads, and start stop them, but maybe i'm kind of special case.

**Comment by maksis** [comment]
I can see the point of the feature. However, the hashing code is quite complicated already (especially when compared to other clients) and implementing this feature would increase the complexity even more, which would increase the likelihood of new bugs, thus making things worse for most users. Implementing a feature like this would also be problematic time-wise with the current development resources.
