### ISSUE TITLE
IMPROVEMENT : To be able to see in filelists how old is a file.

### ISSUE THREAD

**Issue by felisucoibi** [airdcpp-web/airdcpp-webclient#301]
Is something other software does, so you can sort by age and see what's new in your friend filelists.
i understand this feature must be enable both sides.

**Comment by maksis** [comment]
A column "Last modified" should exist in filelists and the dates will be visible when browsing filelists from other AirDC++ users. Or do you mean something else with this request?

**Comment by felisucoibi** [comment]
true, sorry for my stupid proposal, i coe fro eiskalt that i cant see it, and some airdc users askem about it, probably they don't know is there too, i close this.
