### ISSUE TITLE
Bug Report: User Description erroneously showing Active/Passive status

### ISSUE THREAD

**Issue by DaSilva1** [airdcpp-web/airdcpp-webclient#302]
This is a bug report for the Windows client (3.53 x64 on Win10) but unfortunately despite trying to edit my post for the last 10 damn minutes (and even trying to post as an image), your effing forum keeps complaining that "Akismet says your post is spam". (Sorry, quite angry by now and had to again create an account here just to try and post this. Please fix your completely user-unfriendly forum ASAP.)

Bug Report:

"A" or "P" (for Active or Passive) is being added to the Description field by default in any user's info tooltip (shown when hovering on the user's name). Thus if the Description is left blank by a user under Settings, the tooltip shows "A" or "P", and if the Description is set for example to "Sample Text", the tooltip displays "ASample Text" or "PSample Text".

If you can add a separate "Connection Type" or similar line to the tooltip for Active or Passive status, that would be great. You can also then display the full "Active" or "Passive" text which is clearer than simply "A" or "P".

**Comment by maksis** [comment]
The client shouldn't add A/P in description field and I can't reproduce this issue. Possibly it was added by the hubsoft?

If you are able to provider the steps for reproducing this issue, please post them to  https://github.com/airdcpp/airgit or https://bugs.launchpad.net/airdcpp/+bugs?orderby=-date_last_updated&start=0
