### ISSUE TITLE
Feature Request: See exact file size in bytes

### ISSUE THREAD

**Issue by DaSilva1** [airdcpp-web/airdcpp-webclient#304]
This is a feature request for the Windows client (3.53 x64 on Win10) but unfortunately despite trying to edit my post for the last 10 damn minutes (and even trying to post as an image), your effing forum keeps complaining that "Akismet says your post is spam". (Sorry, quite angry by now and had to again create an account here just to try and post this. Please fix your completely user-unfriendly forum ASAP.)

Feature Request:

Is there any way to add an "Exact size" column to the various tabs (Download queue tab, Search tab etc.)? I just switched from Apex and couldn't find the option to add the "Exact size" column that would display the file size in bytes (as opposed to the Size column that uses MB/GB etc.) If this feature isn't there please add it.

**Comment by maksis** [comment]
The exact size column exists in the search and filelist tabs (right-click on the table header row if you can't see it). What comes to the queue tab, see https://github.com/airdcpp-web/airdcpp-webclient/issues/303#issuecomment-472092959

I also added the exact size in the file/directory detail dialog in the Web UI.
