### ISSUE TITLE
Compilation broken with boost 1.69.0

### ISSUE THREAD

**Issue by selmf** [airdcpp-web/airdcpp-webclient#308]
### Current UI and client versions:

Application version: AirDC++w 2.5.0 x86_64
Web UI version: 2.5.1

### Operating system:

Arch Linux

### Steps to reproduce the issue:

When compiling airdcpp-webclient with boost 1.69.0 compilation fails with the following message:

``
                                                           ^
/tmp/makepkg/airdcpp-webclient/src/airdcpp-webclient-2.5.0/airdcpp-core/airdcpp/Client.cpp: In member function 'bool dcpp::Client::changeBoolHubSetting(dcpp::HubSettings::HubBoolSetting)':
/tmp/makepkg/airdcpp-webclient/src/airdcpp-webclient-2.5.0/airdcpp-core/airdcpp/Client.cpp:151:75: error: no matching function for call to 'dcpp::FavoriteManager::setHubSetting(const string&, dcpp::HubSettings::HubBoolSetting&, boost::logic::tribool&)'
   FavoriteManager::getInstance()->setHubSetting(hubUrl, aSetting, newValue);
                                                                           ^
In file included from /tmp/makepkg/airdcpp-webclient/src/airdcpp-webclient-2.5.0/airdcpp-core/airdcpp/Client.cpp:27:
/tmp/makepkg/airdcpp-webclient/src/airdcpp-webclient-2.5.0/airdcpp-core/airdcpp/FavoriteManager.h:69:7: note: candidate: 'void dcpp::FavoriteManager::setHubSetting(const string&, dcpp::HubSettings::HubBoolSetting, bool)'
  void setHubSetting(const string& aUrl, HubSettings::HubBoolSetting aSetting, bool newValue) noexcept;
       ^~~~~~~~~~~~~
/tmp/makepkg/airdcpp-webclient/src/airdcpp-webclient-2.5.0/airdcpp-core/airdcpp/FavoriteManager.h:69:7: note:   no known conversion for argument 3 from 'boost::logic::tribool' to 'bool'
/tmp/makepkg/airdcpp-webclient/src/airdcpp-webclient-2.5.0/airdcpp-core/airdcpp/Client.cpp:153:9: error: cannot convert 'boost::logic::tribool' to 'bool' in return
  return newValue;
         ^~~~~~~~
``

From the information I could gather this is triggered by a change in how boost handles tribool->bool conversions (removing implicit conversions), so an explicit conversion is required.

**Comment by ajshell1** [comment]
I'm getting a similar error in a FreeNAS jail:
/usr/local/include/boost/pending/integer_log2.hpp:7:1: warning: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead. [-W#pragma-messages]
BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
^
/usr/local/include/boost/config/header_deprecated.hpp:23:37: note: expanded from macro 'BOOST_HEADER_DEPRECATED'
# define BOOST_HEADER_DEPRECATED(a) BOOST_PRAGMA_MESSAGE("This header is deprecated. Use " a " instead.")
                                    ^
/usr/local/include/boost/config/pragma_message.hpp:24:34: note: expanded from macro 'BOOST_PRAGMA_MESSAGE'
# define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
                                 ^
<scratch space>:269:2: note: expanded from here
 message("This header is deprecated. Use " "<boost/integer/integer_log2.hpp>" " instead.")
 ^
2 errors generated.
--- airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/Client.cpp.o ---
*** [airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/Client.cpp.o] Error code 1

make[2]: stopped in /root/airdcpp-webclient
1 warning generated.
1 error

make[2]: stopped in /root/airdcpp-webclient
--- airdcpp-core/CMakeFiles/airdcpp.dir/all ---
*** [airdcpp-core/CMakeFiles/airdcpp.dir/all] Error code 2

make[1]: stopped in /root/airdcpp-webclient
1 error

make[1]: stopped in /root/airdcpp-webclient
*** [all] Error code 2

make: stopped in /root/airdcpp-webclient
1 error

make: stopped in /root/airdcpp-webclient

**Comment by maksis** [comment]
This is now fixed in the develop branch
