### ISSUE TITLE
There is a way to safely turn off the airdc webserver? By now i have to turn off computer or kill process.

### ISSUE THREAD

**Issue by felisucoibi** [airdcpp-web/airdcpp-webclient#309]
There is a way to safely turn off the airdc webserver? By now i have to turn off computer or kill process. Every time that i retar it says i scanned a directory a few days ago, but i did today and i restaretd the server, so probably when closing hte erver something is not properly saved.

**Comment by maksis** [comment]
There's a shutdown option in the Application widget in the UI home screen. Using regular kill command should be fine though as the application will then shut down in a clean way.

**Comment by felisucoibi** [comment]
I can't see the shutdown option in my webui, where? I searched for it lot of times. Sorry for this question if is trivial. So this does not explain why the latest refreshed directory in Share is not working properly.

**Comment by felisucoibi** [comment]
I'¡m using 
Web UI version 2.5.1
And in About > Aplication there is no shutdown option.

Trying to find out where it is.

Wait, is a widget??? the shutdown is in  widget??

I think it shoud be in the main bar, maybe below Log Out, or if not in Settings > System

**Comment by felisucoibi** [comment]
It worked with shutdown, and restart.

**Comment by maksis** [comment]
What's the issue that you have with refreshed directories when killing the app or restarting the server? I added a new directory into a shared directory, then refreshed my share, killed the app with `pkill airdcppd` and started it again. The newly added directory was still present in share (auto refresh after startup is disabled). I tested it many times.

**Comment by felisucoibi** [comment]
I can close this question, but i think the turn off option should be in main enu, not in a toolbox i home.

**Comment by maksis** [comment]
I want to keep it out of main menu as I don't think that most users are going to be shutting down the app all the time. I'd say that the optimal way would be to use a systemd script or similar for starting/stopping/restarting the app (and `pkill` should also work fine).

**Comment by felisucoibi** [comment]
as you consider, i tooke months to realize where the sutdown was. Also i would propose the Shared in main menu bar.
