### ISSUE TITLE
Login fields not properly selected

### ISSUE THREAD

**Issue by doobnet** [airdcpp-web/airdcpp-webclient#313]
Using Safari there's an annoying small bug in the login form. When first navigating to the login page the cursor is correctly placed in the username field (the border of the username field does not become blue). When I type one letter the cursor is not placed in the username field anymore. At this time the border is blue. I have to manually click in the username field to type the remaining username. The issue does not occur when using Chrome or Firefox. When using Chrome or Firefox the border is blue from the beginning and the cursor stays in the field.

This issue occurs on the demo site and on my own installation.

**Comment by maksis** [comment]
Does it happen with older versions of the Web UI? This is hard for me to trace as I don't have a computer for testing it.

**Comment by doobnet** [comment]
> Does it happen with older versions of the Web UI?

I'm pretty sure it has happened for as long as I've been using airdcpp-web.

> This is hard for me to trace as I don't have a computer for testing it.

Perhaps you could give Saucelabs [1] a try. It's a service for browser testing, they support Safari. It's a paid service but they have a free trail.

[1] https://saucelabs.com

**Comment by doobnet** [comment]
I cannot reproduce this anymore. I cleared all the browser data (due to other issues) and the problem seems to be gone.
