### ISSUE TITLE
Suggestion about translation

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#314]
### Current UI and client versions:

**Application version:** AirDC++w 2.6.0b x86_64
**Web UI version**: 2.6.0-beta.2

### Operating system:

Fedora, using portable build

### Suggestions

1. Indicate that the new language is setted after the restart of the client
1. Changing language (eg French to English), then restart the client. The label of the login page is in french even if you switch English. After logging, it seems fixed.
1. Be careful: some logs are translated. It'll be harder for you when logs will speak not-know language 
```
Starting.
.Loading Données d'indexation
Loading File d'Attente Téléchargements
Loading Fichiers partagés
Loading Information du pays
Starting web server.
```

**Comment by maksis** [comment]
> 1. Indicate that the new language is setted after the restart of the client

It's done: https://github.com/airdcpp-web/airdcpp-webui/commit/56c24388eefb43f9f874e3d410d66f31a4e008e6

> 2. Changing language (eg French to English), then restart the client. The label of the login page is in french even if you switch English. After logging, it seems fixed.

I'd say that this is acceptable (the updated language is applied on login)

> Be careful: some logs are translated. It'll be harder for you when logs will speak not-know language

"not-know language"? You have selected that language.

**Comment by Kcchouette** [comment]
> Be careful: some logs are translated. It'll be harder for you when logs will speak not-know language

I just want to show you that if an error occurs and log are not in a language you know, you'll have to debug longer than if you understand the logs…

If you don't mind, then it's okay

**Comment by maksis** [comment]
I may not have understood the your point correctly. In which case are the logs are in a language that you don't understand? 

The default application language is always English. You shouldn't change the language to something that you don't understand.

**Comment by Kcchouette** [comment]
> In which case are the logs are in a language that you don't understand?

No, I would understand. But in case of reporting a bug, I'll probably copy-paste this log to you, and YOU, @maksis, won't be able to understand it.

**Comment by maksis** [comment]
Yes, that's unfortunately what would happen. If the text would be in English, then the French user may not understand the error. I'd also probably understand the message if you translate it back to English when asking for help (or I can use an online translator). 

Are there applications that behave differently?

**Comment by maksis** [comment]
Note that error messages returned by the operating system are generally also localized

**Comment by Kcchouette** [comment]
For me, logs should always be in English, but if you want to translate it, do as you want
