### ISSUE TITLE
Design request: Merge the "+" with the "send" button

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#315]
### Current UI and client versions:

**Application**: AirDC++w 2.6.0b-50-gb248 x86_64
**Web UI version**: 2.6.0-beta.6
**Browser version**: Firefox stable as the day of opening the issue

### Operating system:

Fedora 29

When text is empty:
![text empty](https://user-images.githubusercontent.com/3000936/54074518-917c9f00-4293-11e9-88d2-40289eb2d77c.png)

When text is not empty:
![text not empty](https://user-images.githubusercontent.com/3000936/54074525-a78a5f80-4293-11e9-82f4-3790166be532.png)

**Comment by maksis** [comment]
Implemented in https://github.com/airdcpp-web/airdcpp-webui/commit/6888d8745936d5b4d8044d7f1acf3ec7a0ad0777
