### ISSUE TITLE
Feature request: use an alternative tmp forder of /tmp

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#316]
### Current UI and client versions:

Application: AirDC++w 2.6.0b-50-gb248 x86_64
Web UI version: 2.6.0-beta.6

### Operating system:

Fedora 29

You can to like vscode : https://code.visualstudio.com/docs/editor/portable#_tmp-directory:

> By default, the default TMP directory is still the system one even in Portable Mode, since no state is kept there. If you wish to also have your TMP directory within your portable directory, simply create an empty tmp directory inside the data folder. As long as a tmp directory exists, it will be used for TMP data.

**Comment by peps1** [comment]
Just ran into this, when running two instances on the same machine, even running as different users they're trying to use the same tmp folder.

This can create a permission error with the /tmp/Opened Files directory, as it will be created by the user that runs the first instance and the second instance won't have access to write to the folder.
