### ISSUE TITLE
Select multi-files send multi tth link

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#319]
### Current UI and client versions:

**Application**: AirDC++w 2.6.0b-50-gb248 x86_64
**Web UI version**: 2.6.0-beta.6
 **Browser version**: Firefox stable as the day of opening the issue

### Operating system:

Fedora 29

### Steps to reproduce the issue:

When choosing more than one file to send through the "+" chat, it doesn't copy all the TTH of the files we select but only one

**Comment by maksis** [comment]
Please check with Web UI 2.6.0-beta.9

**Comment by Kcchouette** [comment]
my bad, seems to be old firefox cache
