### ISSUE TITLE
Search for directory/file/archive or audio file

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#32]
This is an enhancement request since I'm used to the way ncdc works my standard search option there is to search for directory.

The following snippet is from ncdc manual page to get an idea on options.

/search [options] <query>
Performs a file search, opening a new tab with the results.

Available options:
  -hub      Search the current hub only. (default)
  -all      Search all connected hubs, except those with `chat_only' set.
  -le  <s>  Size of the file must be less than <s>.
  -ge  <s>  Size of the file must be larger than <s>.
  -t   <t>  File must be of type <t>. (see below)
  -tth <h>  TTH root of this file must match <h>.
File sizes (<s> above) accept the following suffixes: G (GiB), M (MiB) and K (KiB).

The following file types can be used with the -t option:
  1  any      Any file or directory. (default)
  2  audio    Audio files.
  3  archive  (Compressed) archives.
  4  doc      Text documents.
  5  exe      Windows executables.
  6  img      Image files.
  7  video    Video files.
  8  dir      Directories.
Note that file type matching is done using file extensions, and is not very reliable.

**Comment by tunestal** [comment]
Is there a way to do this already? Search for a specific file type (audio, video, directory)?

**If not** I'd certainly want this feature added as well.

**Comment by maksis** [comment]
No, open feature requests haven't been implement.

ps. you can click on the reaction button to upvote this request

**Comment by cirojr82** [comment]
That's is something I really miss out. Search for something, but just in some Hubs that I'm connect to. Besides that, I usually search just for directories, not files alone.

Eg:
I'm connect to comics hub and music hubs. If I'm searching for a comic, I just need to search for it in the comics hubs that are more organized in this matter. So I miss this option.
