### ISSUE TITLE
Bad display on mobile view for long title

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#324]
### Current UI and client versions:

**Application version:** AirDC++w 2.6.0 x86_64
**Web UI version:** 2.6.0
**Browser:** Firefox (latest stable when writing this issue) on a mobile

### Operating system:

Debian 9.3

### Steps to reproduce the issue:

Have a long title of file, eg: `A long title that takes a lot of line AAAAA AAAA AAAA AAAA.mkv`
and a mobile (tested on resolution of 360x640): 

![Screen Shot 2019-04-09 at 20 05 16](https://user-images.githubusercontent.com/3000936/55824591-6e4c4600-5b04-11e9-8583-030695ace083.png)

**Comment by maksis** [comment]
How would you improve it?

**Comment by Kcchouette** [comment]
The page is the "detail" view.
"Close" is not available in this resolution

**Comment by maksis** [comment]
Ah I see

**Comment by Kcchouette** [comment]
Adding `style="text-overflow: ellipsis; overflow: hidden;white-space: nowrap;"` to the element does the trick, for example

**Comment by Kcchouette** [comment]
![Screen Shot 2019-04-09 at 20 30 56](https://user-images.githubusercontent.com/3000936/55825498-668da100-5b06-11e9-8fff-01e1400f7bad.png)
