### ISSUE TITLE
[Regression] /me feature doesn't work anymore

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#325]
Related to the feature #173 

### Current UI and client versions:

**Application version:** AirDC++w 2.6.0 x86_64
**Web UI version:** 2.6.0

### Operating system:

Debian 9.3

### Steps to reproduce the issue:

Write `/me test` in hub chat / private chat, try to send it, it does nothing

**Comment by maksis** [comment]
This was fixed in https://github.com/airdcpp-web/airdcpp-webui/commit/6e381717d2ec9f30af44a1494d16d6d104f92835
