### ISSUE TITLE
Improve the mobile view

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#326]
### Current UI and client versions:

**Application version:** AirDC++w 2.6.0 x86_64
**Web UI version:** 2.6.0
**Browser:** Firefox (latest stable when writing this issue) on a mobile (using landscape view)

### Operating system:

Debian 9.3

### Steps to reproduce the issue:

Using 731 x 250 (Pixel 2 in landcape mode, and adding the navbar browser in account):

![Screen Shot 2019-04-24 at 13 56 12](https://user-images.githubusercontent.com/3000936/56657927-8b068300-6699-11e9-83d8-b9b118014df4.png)

![Screen Shot 2019-04-24 at 13 56 19](https://user-images.githubusercontent.com/3000936/56657929-8e017380-6699-11e9-8099-ebd63d29497f.png)

For me, we should be able to see all the content using the real full size (and so by avoiding the 2nd picture)

**Comment by maksis** [comment]
> adding the navbar browser in account

What do you mean with this? I'm not sure how to reproduce this issue. It would also be good to also try with the latest beta UI.

**Comment by Kcchouette** [comment]
> adding the navbar browser in account

It means the green zone here:

![](https://user-images.githubusercontent.com/3000936/57876539-dbdf4680-7815-11e9-9553-00f6e4b109b0.png)

---

So on a smartphone with size of the smartphone Pixel 2 (411 x 731) that you can simulate on chrome:
![](https://user-images.githubusercontent.com/3000936/57876599-029d7d00-7816-11e9-800b-78fefa2b5a78.png)

You remove some size to "simulate" the green zone I show you: **250** x 731  
And you put in landscape mode: 731 x 250

**Comment by maksis** [comment]
Landscape mode will work better in the next version
