### ISSUE TITLE
Added users are not saved

### ISSUE THREAD

**Issue by zersetz-end** [airdcpp-web/airdcpp-webclient#327]
When adding a user through "Settings > System > Users" the infromation isn't persisted to WebServer.xml unless other settings (with an "No unsaved changes/Save changes" button) are saved.

Application version
AirDC++w 2.6.0 x86_64
Web UI version
2.6.0

**Comment by maksis** [comment]
Users will also be saved when closing the application (server daemon). Are you having issues with new users disappearing?

**Comment by zersetz-end** [comment]
Yes. I guess the last shutdown wasn't a regular one.

**Comment by maksis** [comment]
The next version will save the setting file every 30 seconds if something has changed
