### ISSUE TITLE
Crash when using HTTPS (Websocket++)

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#33]
Application version: AirDC++w 0.12.4 x86_64 / 0.850
Web UI version: 0.12.4
Web UI build date: January 11, 2016 3:33 PM

After about 12 hours of uptime to airdcppd it chrashed, attached exceptioninfo.txt.
[exceptioninfo.txt](https://github.com/maksis/airdcpp-webclient/files/87324/exceptioninfo.txt)

**Comment by maksis** [comment]
The latest commits made for Websocket++ seem to address TLS-related stability issues. This bug is likely to be fixed when the next version of Websocket++ is released, which shouldn't take too long.

**Comment by maksis** [comment]
Websocket++ 0.7.0 is now available and I hope that it fixes this bug as well. I'd suggest upgrading to it especially if HTTPS is used.
