### ISSUE TITLE
Unable to upload file when using nginx proxy

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#330]
### Current UI and client versions:

**Application version:** AirDC++w 2.6.1 x86_64
**Web UI version:** 2.6.1

### Operating system:

Debian 9

### Steps to reproduce the issue:

1. Using airdcpp through Nginx proxy (https://airdcpp-web.github.io/docs/advanced/nginx-setup.html)
 1. Try to send file using the chat file upload button
 1. We receive a `Failed to upload the file - Unauthorized (code 401)`

Note: If you don't use Nginx proxy, sending file works

**Comment by maksis** [comment]
That is related to using basic auth with nginx

**Comment by Kcchouette** [comment]
Do you have any idea to fix that?

**Comment by maksis** [comment]
Do you have accounts with identical credentials in the app and nginx? You could test that.

**Comment by Kcchouette** [comment]
Commenting `proxy_set_header Authorization "";` and having an account with identical credentials in the app and nginx does not fix this issue

**Comment by maksis** [comment]
This will be working in the next version
