### ISSUE TITLE
Import / Export for Setting and Favorites

### ISSUE THREAD

**Issue by Hohenbostler** [airdcpp-web/airdcpp-webclient#341]
Hello could you please add an import / Export for all favorite things.

Problem: I use Airdc in a Docker on my NAS and if i update all Settings are deleted. With an import Export function i could after the first restart my file and all is filled correctly.

**Comment by maksis** [comment]
The settings are saved on disk so you can copy them from there. You may also use the API to implement such functionality: https://airdcpp.docs.apiary.io/#

Wouldn't it be possible to make the Docker image to persist the setting files...? Generally people should be able run the app with Docker without losing their settings.

**Comment by maksis** [comment]
I don't think that manual import/export is an optimal solution. Seems like at least one user is using the portable binaries for running the application directly from the terminal (without Docker): https://github.com/airdcpp-web/airdcpp-webclient/issues/272

Also: https://github.com/gangefors/docker-airdcpp-webclient/issues/7

**Comment by Hohenbostler** [comment]
Hi,

ok for people who are familiar with it, this is probably a possible option. But there are people (myself included) who just don't know about it and we just want it to work. 

Nevertheless I understand that the effort is too big or the whole thing is not desired.

**Comment by maksis** [comment]
Optimal solution would to have a native package for Synology, but I haven't heard of anyone working on it.

Running the portable version should be rather simple (similar to using a portable wizard on Windows), especially when compared to losing settings or exporting/importing them. Instructions are provided at https://airdcpp-web.github.io/docs/installation/linux-binaries.html (download, unpack, run the config wizard and start the app).
