### ISSUE TITLE
Connectivity settings: indicate if auto detected ports are being used

### ISSUE THREAD

**Issue by Hohenbostler** [airdcpp-web/airdcpp-webclient#343]
Hello. I am using AirDC++ web on my NAS, but for a long time I have had the problem that after an indefinite time no more searches or downloads can be done. If I kill the process and restart it, it works again. Does anyone know the problem?

**Comment by Hohenbostler** [comment]
A find Out tust every time my Ports are changing . I Set then manually and cant save.

**Comment by Hohenbostler** [comment]
![Screenshot_2020-03-12-04-20-20-273_com android chrome](https://user-images.githubusercontent.com/42488069/76483999-da23e680-6418-11ea-906e-df7a541d8b44.jpg)

![Screenshot_2020-03-12-04-20-27-176_com android chrome](https://user-images.githubusercontent.com/42488069/76484020-e8720280-6418-11ea-8c1d-25ffb39675ac.jpg)

**Comment by maksis** [comment]
Could you show the information from the Auto detection page (settings/connectivity/detection)?

**Comment by Hohenbostler** [comment]
![image](https://user-images.githubusercontent.com/42488069/76502489-639cde00-6444-11ea-8b41-61a6bf87255d.png)

Here it is

**Comment by maksis** [comment]
You should check your IPv4 connectivity settings (disable auto config). If UPnP port mapping is enabled, the configured ports may not stick.

**Comment by Hohenbostler** [comment]
This is strange -> Now i changed it to this one here
![image](https://user-images.githubusercontent.com/42488069/76504187-811f7700-6447-11ea-851d-ad257dbfb06b.png)

and now if ave in the Port section all old ports i normally used .. they changed automaticlly. 


![image](https://user-images.githubusercontent.com/42488069/76504155-749b1e80-6447-11ea-88f5-95f60e5a7620.png)

**Comment by maksis** [comment]
It will display the mapped ports instead of manually configured ones when UPnP is being used. It's just not being indicated in the UI at all, which should be fixed at some point (this issue can be left open until the UI has been improved).

**Comment by maksis** [comment]
This will be fixed in the next version
