### ISSUE TITLE
Please show the steps to compiling the source code for airdcpp-webclient in detail! Thanks!

### ISSUE THREAD

**Issue by roboirc** [airdcpp-web/airdcpp-webclient#345]

**Comment by maksis** [comment]
Is there something that is missing from https://airdcpp-web.github.io/docs/installation/compiling.html ?

**Comment by roboirc** [comment]
Getting this error while trying to compile. Please guide me thanks: https://pastebin.com/q9GtpfUL

**Comment by maksis** [comment]
Seems like you haven't installed the required dependencies

**Comment by roboirc** [comment]
Ok I guess I need to configure the dependencies properly first right.

**Comment by maksis** [comment]
Yes, the dependencies are documented in the guide that I linked here. Note that you may also use the dev hub if you need help.

**Comment by roboirc** [comment]
Thanks

**Comment by roboirc** [comment]
Finally got it working. I used these resources in case it helps others:

1) https://stackoverflow.com/questions/45884752/npm-err-code-unable-to-get-issuer-cert-locally
2) https://stackoverflow.com/questions/24173330/cmake-is-not-able-to-find-boost-libraries
3) https://airdcpp-web.github.io/docs/installation/dependencies.html

**Comment by roboirc** [comment]
Now getting this error:

Exception.h:23:10: fatal error: websocketpp/http/constants.hpp: No such file or directory
   23 | #include <websocketpp/http/constants.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
