### ISSUE TITLE
Question regarding airdcpp-webclient code

### ISSUE THREAD

**Issue by roboirc** [airdcpp-web/airdcpp-webclient#346]
Dear maksis
I was wondering which section of code in the airdcpp-webclient source code deals with adding new hubs to the server list? I was thinking of improving that section of code so that it would automatically get the latest dc++ hub list from the internet and add all the hubs to airdcpp-webclient. 

Thanks

**Comment by maksis** [comment]
> I was thinking of improving that section of code so that it would automatically get the latest dc++ hub list from the internet and add all the hubs to airdcpp-webclient.

What do you exactly mean with this? Would it connect to all hubs in the hublist?

**Comment by roboirc** [comment]
No, only add all the hubs in a "user specified hublist http link" to airdcpp-webclient's list thats all.

**Comment by roboirc** [comment]
Not connect automatically

**Comment by roboirc** [comment]
For this I would need to find out how to use the airdcpp-webclient API and use that to add additional items to the favourites hubs list.

**Comment by maksis** [comment]
https://airdcpp.docs.apiary.io/#reference/favorite-hubs/favorite-hubs/create-favorite-hub

Is that what you need?

**Comment by roboirc** [comment]
I guess but how do I use it?

**Comment by maksis** [comment]
You could write your own extension for that - see the introduction and additional instructions at https://airdcpp.docs.apiary.io (and "Settings" -> "Extensions" for existing extensions, just for reference)

**Comment by roboirc** [comment]
Thanks!
