### ISSUE TITLE
Improve the search function when using magnet link

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#347]
When we click on a magnet link, let's say:

```
magnet:?xt=urn:tree:tiger:VIQ736JQQW24K2ZS55VKOTPQQIFF6O7AP7ESNLI&xl=27698&dn=firefox.png
```

it opens the "search view" of airdcpp-webclient.

Sadly, this search view is not optimized as we want as:
1. when clicking on this kind of link, `dn` and `xl` parameters are not used (even if provided)
2. all result have "1.01" of relevance score even if it don't correspond at all to the has (??)

What I purpose:
 - put  Relevance max is 1.00
- keep the result sorted by relevance score

If I click on the magnet above:
1. if it found same title (dn), same size (xl) and same hash, put 1.00
2. else if only same hash and same size, put 0.99 (or less)
3. else if only same hash and same title, put 0.98 (or less)
3. else if only same hash, put 0.95 (or less)

As it seems hash of adc hub is not tiger-dependent (it seems, to be confirmed with specs), the best will be to (to my mind):
1. if decomposed with "magnet:" then use the schema above (and keep **all the search** put by the user / automatically -so in this case all the magnet link-)
2. else use the standard search

Consequence is:
if I search `magnet:?&dn=firefox.png`, it should search exactly the same thing than `firefox.png`

**Comment by maksis** [comment]
All results with the same TTH should be grouped under a single list item. Are you receiving results for files with different sizes/TTHs?

**Comment by Kcchouette** [comment]
Here the actual result I have for the hash above:
![Screenshot](https://user-images.githubusercontent.com/3000936/77793731-e049d200-706a-11ea-87b0-264891838b68.png)

None of the result:
1. has the hash I've searched
2. has the filename I've searched
3. has the size I've searched

**Comment by maksis** [comment]
Are those incorrect results received from FlylinkDC++ users? If yes, then it's related to https://www.airdcpp.net/forum/viewtopic.php?f=7&t=4846

**Comment by Kcchouette** [comment]
Let's take a real example:

### Debian iso 
![Screenshot](https://user-images.githubusercontent.com/3000936/77794039-767df800-706b-11ea-93e9-9386af532de3.png)


### Magnet link associated: 
`magnet:?xt=urn:tree:tiger:3G367JGTNSH6TY57DPQ3LGYJKOXNM6S47LRSG2A&xl=671088640&dn=debian-10.3.0-amd64-xfce-CD-1.iso`

### Search it

![Screenshot](https://user-images.githubusercontent.com/3000936/77794210-c066de00-706b-11ea-8754-ab313d4ebf9a.png)

### Result of the example

So the real link is at position 25 (I think even more, maybe 27)

**Comment by Kcchouette** [comment]
it seems so :(

**Comment by Kcchouette** [comment]
Related to https://github.com/pavel-pimenov/flylinkdc-r5xx/issues/1727
