### ISSUE TITLE
Saving of TCP and TLS/TCP ports (InPort and TLSPort) does not work

### ISSUE THREAD

**Issue by ambipur76** [airdcpp-web/airdcpp-webclient#349]
### Current UI and client versions:

Application version: AirDC++w 2.7.0 i686
Web UI version: 2.7.0

Browser: Mozilla Firefox 74.0.

### Operating system:

Debian 10 x86, kernel: 4.19.0-8-686-pae #1 SMP Debian 4.19.98-1 (2020-01-26) i686 GNU/Linux

### Steps to reproduce the issue:

When modifying the ports via web interface, it is not saved in config/DCPlusPlus.xml

After stopping the daemon and editing the ports in config/DCPlusPlus.xml (Inport and TLSPort) and restarting the daemon, than checking again on the web interface, the used ports are different from those ones in the xml.

Checking with the command
netstat -tulpn | grep airdc
the used tcp ports are the same as on the web interface.

When restarting the daemon the actually used tcp ports seems to be random generated.

The udp port in the xml is always the same as on the web interface, this works as expected..

**Comment by maksis** [comment]
This is probably related to https://github.com/airdcpp-web/airdcpp-webclient/issues/343 (that was just fixed). Could you try the [latest beta](https://web-builds.airdcpp.net/develop/)?

**Comment by ambipur76** [comment]
OK, after unchecking the box "Let AirDC++ determine the best IPv4 connectivity settings", saving, logout and restarting the daemon, the ports configured in the xml are used and also shown on the web interface. Thank you!
