### ISSUE TITLE
In Events on right panel, message about IPv6 connectivity even when it has been automatically disabled on prior startup 

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#35]
Upon starting airdcppd it seems to check for IPv6 network even when it has been disabled in 
Connectivity/Advanced/IPv6 

If it is disabled then do not run the check for IPv6 networking?

Events
Connectivity (IPv6): Determining the best connectivity settings...
Connectivity (IPv6): IPv6 connectivity has been disabled as no public IPv6 address was detected

**Comment by maksis** [comment]
This shouldn't happen. What are your current connectivity settings?

**Comment by bissa** [comment]
IPv4 connectivity: Active mode (manual configuration)
Update IP on startup
Don't allow hub/UPnP to override
Ports (manual):

**Comment by bissa** [comment]
These Events has magically disappeared, closing this issue.
