### ISSUE TITLE
disable webserver

### ISSUE THREAD

**Issue by tommyhome** [airdcpp-web/airdcpp-webclient#352]
Hi,
I don't use this feature but there is no way to disable it.
I can enter settings and press stop webserver each time I start the client but I'd rather have a disable webserver option.

So, this is a request for a feature for an option to disable the webserver.

**Comment by maksis** [comment]
I don't notice any problems with disabling the feature:

![image](https://user-images.githubusercontent.com/5640804/79104892-3495c700-7d78-11ea-9e4e-49e9d783721c.png)

**Comment by maksis** [comment]
The server was incorrectly shown as started after restart even when both ports were disabled (and the server wasn't really running), but this will be fixed in the next build
