### ISSUE TITLE
Alot of errors in log:

### ISSUE THREAD

**Issue by polhaghverdian** [airdcpp-web/airdcpp-webclient#353]
Hi,

airdcpp-webclient: Version 2.7.0

Have been using the airdccp-webclient for a while in a docker container with nginx, which has been working great. Yesterday i decided to activate ssl/https, and one problem arise.  

In the logs i can see alot of errors, and besides that when the connection breaks for example the LAN network, i cant reload the page from the webbrowser to make it re-establish the connection. I have to restart the container to enable login. This has never happened when using HTTP. 

Do you recognize any of the below errors?

`asio async_shutdown error: asio.misc:2 (End of file)`

`[error] handle_read_frame error: websocketpp.transport:7 (End of File)`

`[disconnect] Disconnect close local:[1006,End of File] remote:[1006]`

` asio async_shutdown error: asio.ssl.stream:1 (stream truncated)`

`[fatal] Websocket: Failed to send data: invalid state (7c4d8df1-d35c-4be3-9b13-08f13b1900e8)`

`[disconnect] Disconnect close local:[1011,PONG timed out] remote:[1006]`

`[info] asio async_read_at_least error: system:125 (Operation canceled)`

`[error] handle_read_frame error: websocketpp.transport:2 (Underlying Transport Error)`

**Comment by maksis** [comment]
Hmm no, I'm not sure that what's happening. Usually those errors are not fatal (there are also normal unclean disconnects/connection failures). 

Could you first try the latest beta from https://web-builds.airdcpp.net/develop/ ?

**Comment by polhaghverdian** [comment]
I will try, and let you know how it went. Thanks.

**Comment by maksis** [comment]
I've been now using the application via HTTPS for a few days and it has been working fine so far

**Comment by polhaghverdian** [comment]
It has been working a couple of days now. I dont know what was wrong. 

Thank you!
