### ISSUE TITLE
SOCKS5 stop after 10sec

### ISSUE THREAD

**Issue by Machin77** [airdcpp-web/airdcpp-webclient#354]
### Current UI and client versions:

AirDC++w 2.8.0b-59-gdab1 x86_64

### Operating system:

OMV5 Debian 64bits

### Steps to reproduce the issue:

When I try to connect to hubs via SOCKS5 proxy, the connection is good then after 10sec closes itself. Is this a known bug?

**Comment by maksis** [comment]
Probably inherited from DC++: https://bugs.launchpad.net/dcplusplus/+bug/1856087 / https://bugs.launchpad.net/dcplusplus/+bug/988891

There's no one maintaining the SOCKS5 feature really

**Comment by maksis** [comment]
I've now fixed various issues related to SOCKS5 functionality (see https://bugs.launchpad.net/dcplusplus/+bug/1856087/comments/1). However, I haven't experienced your case where the proxy would stop working after 10 seconds.

Could you test the latest build from https://web-builds.airdcpp.net/develop/ to see if it makes any difference?

**Comment by Machin77** [comment]
Hello Maksis i have same error
![image](https://user-images.githubusercontent.com/65110336/91632199-92514580-e9df-11ea-980e-8a7e5ddfc3d9.png)

**Comment by maksis** [comment]
Can it be an issue with the SOCKS5 server itself...?

**Comment by Machin77** [comment]
the problem seems to be fixed using another socks5 server thanks for the fix.
