### ISSUE TITLE
Back Porrt is wide open

### ISSUE THREAD

**Issue by I-Cat** [airdcpp-web/airdcpp-webclient#355]
<!--
If you are posting a question/feature requests, all prefilled information can be removed.

By submitting this report, I thereby confirm that I have read the guidelines for contributing (https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md) for this report type.

## Steps to reproduce the issue:

open your sever ip shows eniter tree

ip hidden for your protection\

Index of /
~*encdding=b64*A-Za-z0-9+/=*~
OTEuMTMyLjg2LjEyMg==

![1](https://user-images.githubusercontent.com/58572646/81956945-efb0ba80-95d9-11ea-8d6f-3c3f40fa139e.png)

**Comment by maksis** [comment]
What's back port?

**Comment by I-Cat** [comment]
thats odd it didnt up load my post

**Comment by I-Cat** [comment]
`![1](https://user-images.githubusercontent.com/58572646/81957934-3fdc4c80-95db-11ea-9356-85b86a7cf935.png)`

*encdding=b64*A-Za-z0-9+/=*
aHR0cHM6Ly85MS4xMzIuODYuMTIyOjQ0Mw==

**Comment by maksis** [comment]
I can open the image with a direct link, but I'm still not sure that what is the issue

**Comment by I-Cat** [comment]
Well simply put anyone can access the back server / files easily 
Now if they can delete them all its up to them do to so.

**Comment by peps1** [comment]
@maksis: In case you didn't notice, he posted an IP in base64 encoding, looks like a loveserver IP, but not the same where you host the web-builds. Maybe that server is not supposed to be public? Though, both IPs accessed directly through HTTP show the nginx, "**welcome to nginx**" default page, so they might be just 2 IPs on the same server.

@I-Cat: you should really be more clear in what you're talking about. Right now it looks like you're saying, it should **not** be possible to access those files directly from your browser, but that is exactly what maksis intended. Everyone can just browse those directories and download the build files they desire.
Also you seem to be mistaken about anyone just being able to delete those files from the server. **You can not.** 
**Unless** you found a security issue that allows you to actually delete files, then you should report this to maksis in a confidential way with exact steps how to reproduce this so he can investigate.

**Comment by I-Cat** [comment]
Ok it is up to you guys in the end so tnx for the reply.
