### ISSUE TITLE
ARMv6 binary file for Raspberry Pi ZeroW

### ISSUE THREAD

**Issue by amanjosan2008** [airdcpp-web/airdcpp-webclient#357]
Was someone successful in compiling the code for Raspberry Pi ZeroW having Armv6 CPU architecture.
I tried it many times, but due to the extremely slow speed, it would take month to compile the code.
Also tried to cross-comile:
https://blog.kitware.com/cross-compiling-for-the-raspberry-pi-evolved/

But this is also unsuccessful due to failure in resolving dependencies, different versions of libraries, etc.

Kindly share the binary file for ARMv6 as well.

**Comment by maksis** [comment]
Have you tried https://github.com/airdcpp-web/airdcpp-webclient/tree/master/buildroot ?

**Comment by amanjosan2008** [comment]
It worked like a charm. Thank you so much for sharing the link.
It was quite a simple process.
