### ISSUE TITLE
boost compilation errors

### ISSUE THREAD

**Issue by wiejakp** [airdcpp-web/airdcpp-webclient#358]
I'm having compilation issues.. sad, it fails at 100%.

### Current UI and client versions:

none

### Operating system:

Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 4.19.118-v7l+
Architecture: arm

### Steps to reproduce the issue:

Whatever's on: https://airdcpp-web.github.io/docs/installation/compiling.html

## Dependencies and installation:

sudo apt-get install gcc g++ git cmake npm python pkg-config

sudo apt install pkg-config libbz2-dev zlib1g-dev libssl-dev libstdc++6 libminiupnpc-dev libnatpmp-dev libtbb-dev libmaxminddb-dev libboost1.67-dev libboost-regex1.67 libboost-thread1.67 libboost-system1.67 libleveldb-dev libwebsocketpp-dev

pi@server0:~/Desktop/download/airdcpp-webclient $ cmake .
-- cotire 1.7.10 loaded.
-- Found libnatpmp: /usr/lib/arm-linux-gnueabihf/libnatpmp.so
-- Found LevelDB: /usr/lib/arm-linux-gnueabihf/libleveldb.so
-- Found Intel TBB
-- Building with UPNP support (miniupnpc)
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   regex
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Library directory: /usr/local/lib
-- Resource directory: /usr/local/share/airdcpp/
-- Startup config directory: /usr/local/etc/airdcpp/
-- Version file generated
-- No string changes detected, using old StringDefs.cpp
-- Stacktrace enabled
-- addr2line enabled
-- Build shared libraries: ON
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- CMAKE_SYSTEM: Linux-4.19.118-v7l+
-- CMAKE_SYSTEM_PROCESSOR: armv7l
-- CMAKE_CXX_COMPILER_ID: GNU
-- CMAKE_CXX_COMPILER_VERSION: 8.3.0
-- CMAKE_C_COMPILER_ID: GNU
-- CMAKE_INSTALL_RPATH: /usr/local/lib
-- CMAKE will use this libs (and headers) during build:
    miniupnpc (headers):/usr/lib/arm-linux-gnueabihf/libminiupnpc.so (/usr/include)
    boost (headers): /usr/lib/arm-linux-gnueabihf/libboost_regex.so;/usr/lib/arm-linux-gnueabihf/libboost_system.so;/usr/lib/arm-linux-gnueabihf/libboost_thread.so;-lpthread;/usr/lib/arm-linux-gnueabihf/libboost_chrono.so;/usr/lib/arm-linux-gnueabihf/libboost_date_time.so;/usr/lib/arm-linux-gnueabihf/libboost_atomic.so (/usr/include)
    bzip2 (headers): /usr/lib/arm-linux-gnueabihf/libbz2.so (/usr/include)
    zlib (headers): /usr/lib/arm-linux-gnueabihf/libz.so (/usr/include)
    openssl (headers): /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (/usr/include)
    iconv (headers): /usr/lib/arm-linux-gnueabihf/libc.so (/usr/include)
    maxminddb (headers): /usr/lib/arm-linux-gnueabihf/libmaxminddb.so (/usr/include/arm-linux-gnueabihf)
    leveldb (headers): /usr/lib/arm-linux-gnueabihf/libleveldb.so (/usr/include)
    websocketpp (headers): ()
    natpmp (headers): /usr/lib/arm-linux-gnueabihf/libnatpmp.so (/usr/include)
    tbb (headers): /usr/lib/arm-linux-gnueabihf/libtbb.so (/usr/include)
    
-- Installing Web UI
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
Wanted UI version 2.7.0 is installed already
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/download/airdcpp-webclient
pi@server0:~/Desktop/download/airdcpp-webclient $ make -j2
Scanning dependencies of target airdcpp
[  0%] Building CXX object airdcpp-core/CMakeFiles/airdcpp.dir/airdcpp/version.cpp.o
[  1%] Linking CXX shared library libairdcpp.so
[ 57%] Built target airdcpp
[ 57%] Building CXX precompiled header airdcpp-webapi/cotire/airdcpp-webapi_CXX_prefix.hxx.gch
Scanning dependencies of target airdcpp-webapi
[ 59%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ConnectivityApi.cpp.o
[ 59%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ApiSettingItem.cpp.o
[ 60%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/EventApi.cpp.o
[ 60%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ExtensionApi.cpp.o
[ 61%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ExtensionInfo.cpp.o
[ 61%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FavoriteDirectoryApi.cpp.o
[ 62%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FavoriteHubApi.cpp.o
[ 62%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FavoriteHubUtils.cpp.o
[ 63%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FilelistApi.cpp.o
[ 63%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FilelistInfo.cpp.o
[ 64%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FilelistItemInfo.cpp.o
[ 64%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FilelistUtils.cpp.o
[ 65%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/FilesystemApi.cpp.o
[ 65%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/HashApi.cpp.o
[ 67%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/HistoryApi.cpp.o
[ 67%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/HubApi.cpp.o
[ 68%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/HubInfo.cpp.o
[ 68%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/OnlineUserUtils.cpp.o
[ 69%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/PrivateChatApi.cpp.o
[ 69%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/PrivateChatInfo.cpp.o
[ 70%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/QueueApi.cpp.o
[ 70%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/QueueBundleUtils.cpp.o
[ 71%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/QueueFileUtils.cpp.o
[ 71%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/SearchApi.cpp.o
[ 72%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/SearchEntity.cpp.o
[ 72%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/SearchUtils.cpp.o
[ 73%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/SessionApi.cpp.o
[ 73%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/SettingApi.cpp.o
[ 75%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ShareApi.cpp.o
[ 75%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ShareProfileApi.cpp.o
[ 76%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ShareRootApi.cpp.o
[ 76%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ShareUtils.cpp.o
[ 77%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/SystemApi.cpp.o
[ 77%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/TransferApi.cpp.o
[ 78%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/TransferUtils.cpp.o
[ 78%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/UserApi.cpp.o
[ 79%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/ViewFileApi.cpp.o
[ 79%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/WebUserApi.cpp.o
[ 80%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/WebUserUtils.cpp.o
[ 80%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/base/ApiModule.cpp.o
[ 81%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/base/HookApiModule.cpp.o
[ 81%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/common/Deserializer.cpp.o
[ 82%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/common/FileSearchParser.cpp.o
[ 82%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/common/Format.cpp.o
[ 84%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/common/PropertyFilter.cpp.o
[ 84%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/common/Serializer.cpp.o
[ 85%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/api/common/SettingUtils.cpp.o
[ 85%] Building C object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/microtar/microtar.c.o
[ 86%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/stdinc.cpp.o
[ 86%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/ApiRequest.cpp.o
[ 87%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/ApiRouter.cpp.o
[ 87%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/Extension.cpp.o
[ 88%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/ExtensionManager.cpp.o
[ 88%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/FileServer.cpp.o
[ 89%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/FloodCounter.cpp.o
[ 89%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/HttpUtil.cpp.o
[ 90%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/JsonUtil.cpp.o
[ 90%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/Session.cpp.o
[ 92%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/SystemUtil.cpp.o
[ 92%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/TarFile.cpp.o
[ 93%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/WebServerManager.cpp.o
[ 93%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/WebServerSettings.cpp.o
[ 94%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/WebSocket.cpp.o
[ 94%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/WebUser.cpp.o
[ 95%] Building CXX object airdcpp-webapi/CMakeFiles/airdcpp-webapi.dir/web-server/WebUserManager.cpp.o
[ 95%] Linking CXX shared library libairdcpp-webapi.so
[ 96%] Built target airdcpp-webapi
Scanning dependencies of target airdcppd
[ 97%] Building CXX object airdcppd/CMakeFiles/airdcppd.dir/CDMDebug.cpp.o
[ 97%] Building CXX object airdcppd/CMakeFiles/airdcppd.dir/Client.cpp.o
[ 98%] Building CXX object airdcppd/CMakeFiles/airdcppd.dir/ConfigPrompt.cpp.o
[ 98%] Building CXX object airdcppd/CMakeFiles/airdcppd.dir/main.cpp.o
[100%] Building CXX object airdcppd/CMakeFiles/airdcppd.dir/stacktrace.cpp.o
[100%] Linking CXX executable airdcppd
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::is_combining_implementation(unsigned short)'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::raise_runtime_error(std::runtime_error const&)'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::put_mem_block(void*)'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::get_mem_block()'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::verify_options(unsigned int, boost::regex_constants::_match_flags)'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::get_default_error_string(boost::regex_constants::error_type)'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
/usr/bin/ld: ../airdcpp-core/libairdcpp.so.2.7.0: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
collect2: error: ld returned 1 exit status
make[2]: *** [airdcppd/CMakeFiles/airdcppd.dir/build.make:162: airdcppd/airdcppd] Error 1
make[1]: *** [CMakeFiles/Makefile2:467: airdcppd/CMakeFiles/airdcppd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by maksis** [comment]
It has something to do with boost regex, but I don't remember seeing that error before. Maybe there is something special with the libraries provided by raspbian.

Is there a reason why you need to compile it by yourself instead of using the precompiled version (https://airdcpp-web.github.io/docs/installation/linux-binaries.html)?

**Comment by maksis** [comment]
As there is no indication that this is happening on other operating systems, I'll close the issue for now. I recommend using the portable binaries on ARM systems (or using https://github.com/airdcpp-web/airdcpp-webclient/tree/master/buildroot to compile your own binaries).
