### ISSUE TITLE
Bad size in the "download - browse" pop up

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#362]
### Current UI and client versions:

> Application version: AirDC++w 2.8.0 x86_64
Web UI version: 2.8.0
Web UI build date: July 11, 2020 1:08 PM

### Operating system:

Debian 10 I guess

### Steps to reproduce the issue:

- Have a disk with white-space in name, do a download on it using the download browse
- Do the action again but this time choose "previous" and before clicking see the size of the HDD (/run/media/me/Name with whitespace/ (7.82 GiB free)
- here the "free" size is bad

**Comment by maksis** [comment]
After researching this a bit (as I couldn't reproduce the issue with my dev build), this actually seems to be related to the standard C library being used by the portable builds, so only the portable binaries are being affected. 

From https://www.man7.org/linux/man-pages/man3/getmntent.3.html 

```
       Since fields in the mtab and fstab files are separated by whitespace,
       octal escapes are used to represent the characters space (\040), tab
       (\011), newline (\012), and backslash (\\) in those files when they
       occur in one of the four strings in a mntent structure.  The routines
       addmntent() and getmntent() will convert from string representation
       to escaped representation and back.  When converting from escaped
       representation, the sequence \134 is also converted to a backslash.
```

However, the standard C library isn't doing any escaping. I need to check if they are willing to implement that.

**Comment by maksis** [comment]
I haven't received any reply from musl yet but the next version will implement a workaround for this
