### ISSUE TITLE
[Bug] Unable to upload file when using nginx proxy

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#364]
Relative to https://github.com/airdcpp-web/airdcpp-webclient/issues/330

### Current UI and client versions:

Application version: AirDC++w 2.8.1 x86_64
Web UI version: 2.8.1
Web UI build date: August 20, 2020 9:01 PM

Using Firefox latest release

### Operating system:

Debian 10

### Steps to reproduce the issue:

1. Using nginx proxy from https://github.com/airdcpp-web/airdcpp-webclient/wiki/nginx-proxy-configuration (I have uncommented proxy_set_header Authorization "";)
2. Uploading a file in private message
3. Have the error https://XXXXXXX/airdcpp/temp
```
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by maksis** [comment]
I actually managed to miss setting the new auth header for file uploads in the previous release
