### ISSUE TITLE
Skiplist only taken into account after hashing

### ISSUE THREAD

**Issue by doobnet** [airdcpp-web/airdcpp-webclient#366]
After a bundle has been downloaded and before it's been hashed. If I place an extra file in the same directory as bundle, like `.srt`. Then rescanning the share, there's an error message [1] showing up in the events view complaining about this extra `.srt` file. I have included `.srt` in the skiplist in Settings -> Sharing -> Sharing options. After hashing has been completed for that bundle and then rescanning the share, I instead get the expected info message in the events view about the `.srt` file being excluded from the share.

It looks like the skiplist is only taken into account after hashing has been completed. Would it be possible to look at the skiplist before hashing is completed?

I'm running AirDC++w 2.8.1 x86_64 and airdcpp-release-validator 1.0.0-beta.4.

[1] I have the https://github.com/maksis/airdcpp-release-validator extension installed. I'm not sure if the error message comes from the extension or from AirDC++ proper

**Comment by maksis** [comment]
This sounds weird. Downloaded bundles should be added in share right after they have finished downloading without hashing (the extension should perform the scan before that though). With rescanning, do you mean scan with the release validator extension or a regular share refresh? The release validator won't currently check the skiplist (or other excludes): https://github.com/maksis/airdcpp-release-validator/issues/10

Could you post the event log output?

**Comment by doobnet** [comment]
> This sounds weird. Downloaded bundles should be added in share right after they have finished downloading without hashing (the extension should perform the scan before that though

I have configured AirDC++ to download to a separate directory from the directories containing the share. Not sure if that's related. I do see log messages like this as well:

```
The directory <DIR> has been refreshed (NNN MiB of files have been added for hashing; they won't be visible in the file list until they have finished hashing)
```

Which indicates that it needs to be hashed before being added to the share. Also, if I browse my own share, they won't show up until it has been hashed.

> With rescanning, do you mean scan with the release validator extension or a regular share refresh?

I mean share refresh.

> The release validator won't currently check the skiplist (or other excludes)

Ok, I see.

> Could you post the event log output?

I see now that those messages are prefixed with `airdcpp-release-validator`, so it's the extension. Here's an example:

```
[airdcpp-release-validator] <DIR> : Extra files in release directory (1 file(s): foo.srt)
[airdcpp-release-validator] Following problems were found while scanning the share directory <DIR> : extra files in release directory (count: 1)
```

The first entry is a warning, the second one is an error. 

Then after hashing is complete, when refreshing the share, it would instead say:

```
Some of the files from directory <DIR> won't be shared: File matches the share skiplist (affected file(s): foo.srt)
```

This entry is an info message.

Looks like it's the same issue as maksis/airdcpp-release-validator#10.

**Comment by maksis** [comment]
See https://github.com/maksis/airdcpp-release-validator/issues/10 for information about the new version of the extension that will handle excluded files/directories. If there is something else that is not working as intended, feel free to open an issue at https://github.com/maksis/airdcpp-release-validator/issues
