### ISSUE TITLE
UI crashes when viewing bundle sources

### ISSUE THREAD

**Issue by bobo-j** [airdcpp-web/airdcpp-webclient#367]
### Current UI and client versions:

AirDC++w 2.9.0b-80-gcfbe x86_64
2.9.0-beta.15

Firefox Browser 81.0 (64-bit)

### Operating system:

Linux Mint 19.3 

### Steps to reproduce the issue:

The problem appears a later after starting the application. When I open the queue tab and want to see the bundle sources, this message appears:
Web UI has crashed with the following error: "Invariant Violation: Invalid user object in UserMenuDecorator: id and hub_url missing"

**Comment by maksis** [comment]
I'm not able to figure out how to reproduce this. Are you able to reproduce it?

What do you exactly mean with "want to see the bundle sources", do you click the sources column? At which point does the crash happen?

**Comment by bobo-j** [comment]
Yes, i mean clicking on the sources column
When the application starts, everything is fine. It happens at times after working for about 15 minutes. Then it fixes without me restarting the application. Then it is repeated again and so on.

**Comment by maksis** [comment]
@bobo-j  @c0r4ir Do you remember that how the bundles causing those crashes were queued (e.g. from filelist or search)? Could you also check from the bundle XML file whether all bundle sources have the `HubHint` attribute set? By default, the bundle XML file is located at ```~/.airdc++/Bundles/BundleXXX.xml``` where XXX is the bundle ID (e.g. 4265847760) that you can get from the browser URL when viewing bundle sources.

**Comment by maksis** [comment]
@bobo-j @c0r4ir please confirm that it's working with the latest beta build (http://web-builds.airdcpp.net/develop/). It will now prevent you from adding sources without a hub hint. It's still not clear to me that how such sources were added for you, so keep an eye on errors about adding sources (or if you notice that sources can't be added even if there is no error).

**Comment by bobo-j** [comment]
Yes, i confirm that for now is working! I use AirDC++w 2.10.0b-78-ge65f x86_64 on Linux Mint 19.3
