### ISSUE TITLE
 Strip leading and trailing whitespaces/tabs/ other non-printable chars from the search

### ISSUE THREAD

**Issue by peps1** [airdcpp-web/airdcpp-webclient#368]
Currently in the search window when trailing whitespaces/tabs/ other non-printable are added in the search query, these are not stripped and can affect search results.

**Comment by maksis** [comment]
Whitespaces shouldn't affect the search, or can you confirm that it's happening?

**Comment by Fossegrimen** [comment]
It works with spaces but it doesn't work with tabs (ALT+09). I wasn't able to replicate any other non-printable char.
