### ISSUE TITLE
"*.ldb: No such device" on boot

### ISSUE THREAD

**Issue by riptide981** [airdcpp-web/airdcpp-webclient#370]
```
$ ./airdcppd -p="/home/p2p/.config/AirDC++/airdcppd.pid" -c="/home/p2p/.config/AirDC++/" -web-resources="/home/p2p/airdcpp-webclient/web-resources"
Starting.
.Loading Hash database
Failed to open hash data: IO error: /home/p2p/.config/AirDC++/HashData//000017.ldb: No such device

Make sure that there isn't another instance of AirDC++w using the same settings directory and that the directory /home/p2p/.config/AirDC++/HashData/ is accessible. AirDC++w will now exit.

FATAL: Can't start AirDC++ Web Client:
```
I am getting this error when starting airdcppd, any idea what may be failing? Can the double / in HashData//000017.ldb be a hint?

I create the file with `touch 000017.ldb` and give it 777 permissions, but when I launch airdcppd it disappears.

**Comment by maksis** [comment]
> Can the double / in HashData//000017.ldb be a hint?

I doubt that. 

Could you provide the version information that should have been requested in the issue template? Are you using a portable version downloaded from the home page or something else? Have you been able to start the app successfully before?

**Comment by riptide981** [comment]
> > Can the double / in HashData//000017.ldb be a hint?
> 
> I doubt that.
> 
> Could you provide the version information that should have been requested in the issue template? Are you using a portable version downloaded from the home page or something else? Have you been able to start the app successfully before?

Sorry, here is

### Current UI and client versions:

airdcpp_2.9.0_webui-2.9.0_64-bit_portable.tar.gz downloaded from here.

### Operating system:

OpenMediaVault 5.5.12 (Debian buster 10.6)

### Steps to reproduce the issue:

The issue appears on every launch and the app doesn't start.

Yes, the app started successfully before. The first time i saw the problem was in the webui during a hash. Then I restarted the application and it gave the problem as soon as it started.

**Comment by maksis** [comment]
Is `/home/p2p/.config/AirDC++/` a symlink to `/srv/f5aa9bfd-bbb8-4f73-a1fa-03a772e19973/home/p2p/.config/AirDC++/`? What happens if you try to use the latter as your config directory?

**Comment by riptide981** [comment]
> Is `/home/p2p/.config/AirDC++/` a symlink to `/srv/f5aa9bfd-bbb8-4f73-a1fa-03a772e19973/home/p2p/.config/AirDC++/`? What happens if you try to use the latter as your config directory?

The `/srv/f5aa9bfd-bbb8-4f73-a1fa-03a772e19973/` part is a copy&paste mistake. I correct the first post.

**Comment by maksis** [comment]
> I had a similar problem months ago on another temporary install, I think I just deleted all the files from the HashData directory and it worked again.

It might be worth of trying. I'd also suggest creating an empty `REPAIR` file inside the HashData folder and starting the app after that to see whether it's able to repair the database.

The database obviously thinks that such file exists even though it doesn't (which is something that I haven't seen before). I'd guess that this is an issue with the [leveldb](https://github.com/google/leveldb/) library.

**Comment by riptide981** [comment]
> > I had a similar problem months ago on another temporary install, I think I just deleted all the files from the HashData directory and it worked again.
> 
> It might be worth of trying. I'd also suggest creating an empty `REPAIR` file inside the HashData folder and starting the app after that to see whether it's able to repair the database.
> 
> The database obviously thinks that such file exists even though it doesn't (which is something that I haven't seen before). I'd guess that this is an issue with the [leveldb](https://github.com/google/leveldb/) library.

```
$ touch .config/AirDC++/HashData/REPAIR
$ ./airdcppd -p="/home/p2p/.config/AirDC++/airdcppd.pid" -c="/home/p2p/.config/AirDC++/" -web-resources="/home/p2p/airdcpp-webclient/web-resources"
Starting.
.Loading Hash database
Loading Repairing hash data
Failed to open file index: IO error: /home/p2p/.config/AirDC++/FileIndex//000017.ldb: No such device

Make sure that there isn't another instance of AirDC++w using the same settings directory and that the directory /home/p2p/.config/AirDC++/FileIndex/ is accessible. AirDC++w will now exit.

FATAL: Can't start AirDC++ Web Client:
```

Similar result :/

**Comment by riptide981** [comment]
After further investigation I was able to reproduce the issue by closing the client during the hashing process.
The error is the same, but with a different * .ldb. Like 000024.ldb or other 0000**.ldb

**Comment by maksis** [comment]
Did you also test it with a different (clean) config directory? Do you have any special system config that could affect it? Maybe you could also test an older application version.

**Comment by riptide981** [comment]
Tested with the 2.7.0 and 2.6.0 with an empty config directory, same issue with the first share hash.

I use SnapRAID, can this be the cause?

There is any log file that I can send?

**Comment by maksis** [comment]
> I use SnapRAID, can this be the cause?

Yeah I guess that's possible (if it's also being used for the config location). ```No such device``` is a rather strange error in such case as generally it should just say that the file doesn't exist. Do you find anything strange from the system logs, or are you able to test the application on a volume that doesn't have SnapRAID?

**Comment by riptide981** [comment]
`Hashing finished: 69299 files (136.50 GiB) in 4 directories have been hashed in 29 minutes 54 seconds (77.89 MiB/s)`

It seems the problem was in SnapRAID/mergerfs.

Solution: run the client directly from the "real" filesystem instead of mergerfs mount.
