### ISSUE TITLE
Fix "websocketpp (headers)" message in CMakeLists.txt

### ISSUE THREAD

**Issue by Fossegrimen** [airdcpp-web/airdcpp-webclient#376]
Should be "websocketpp_INCLUDE_DIR" in the main CMakeLists.txt instead of "WEBSOCKETPP_INCLUDE_DIR". This caused me to believe that websocketpp wasn't found even though it was.

https://github.com/airdcpp-web/airdcpp-webclient/blob/0a49ecf1722f0bc8097e3600fd95d12e6b2361d7/CMakeLists.txt#L312

**Comment by Fossegrimen** [comment]
I guess it should be changed in Findwebsocketpp.cmake instead of in CMakeLists.txt.

**Comment by maksis** [comment]
Fixed in the develop branch
