### ISSUE TITLE
Stopping airdcpp clears out config/ADLSearch.xml

### ISSUE THREAD

**Issue by doobnet** [airdcpp-web/airdcpp-webclient#381]
### Current UI and client versions:

Application version: AirDC++w 2.11.0 x86_64
Web UI version: 2.11.0

### Operating system:

Linux QTS (Linux dist from QNAP).

### Steps to reproduce the issue:

1. Place a `ADLSearch.xml` file in the airdcpp config directory
2. Start airdcpp
3. Stop airdcpp

The `config/ADLSearch.xml` file has now been cleared an only contains:

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<ADLSearch>
	<SearchGroup/>
</ADLSearch>
```

**Comment by maksis** [comment]
Could loading of the ADL search file fail (did you check the event log)? The ADL search feature isn't maintained on non-Windows platforms, but if someone wants to locate and fix this specific issue, pull requests are welcome.

**Comment by maksis** [comment]
Actually I'd like to move the ADL search code to the `modules` directory so that it won't even be compiled for the Web Client (which would also fix this issue, as no file modifications will happen after that)

**Comment by doobnet** [comment]
That was quick. Thanks.
