### ISSUE TITLE
Add support of search links in chats

### ISSUE THREAD

**Issue by tehnick** [airdcpp-web/airdcpp-webclient#383]
Currently search magnet link in AirDC++ WebUI 2.11.0 looks like:
![Screenshot_20210129_154231+mod1](https://user-images.githubusercontent.com/441190/106278408-ba252d80-624b-11eb-90b1-de9edc78979b.png)
As you see, such link is not parsed as magnet link and after click on it web browser asks user which application should be used to open link.

For comparing the same magnet links in EiskaltDC++ 2.4.1 look like:
![Screenshot_20210129_130019+mod-1](https://user-images.githubusercontent.com/441190/106279134-04f37500-624d-11eb-8cf5-ccb3928b9324.png)

Please add support of search magnet links in chats. They are described in [magnet URI scheme](https://en.wikipedia.org/wiki/Magnet_URI_scheme#Parameters) in details, but on practice such links often don't contain size part and look like:
```
magnet:?kt=EiskaltDC%2B%2B+2.4.1&dn=EiskaltDC%2B%2B+2.4.1
```
After click on such link DC client starts search for keywords (from kt=) with search type "Any".

Currently search magnet links are supported at least in EiskaltDC++ and FlylinkDC++. I have not checked GreylinkDC++ and other dead projects. Also displaying of search links in FlylinkDC++ currently has tiny issue: 
https://github.com/pavel-pimenov/flylinkdc-r6xx/issues/5

Yes, these links are used rarely now, but it would be nice to spread their usage more widely.

**Comment by maksis** [comment]
Added in version 2.11.1. It will also allow you to create such links for directories (search results/filelists).

You can try the changes at https://webdemo.airdcpp.net

**Comment by tehnick** [comment]
Thanks!
