### ISSUE TITLE
Change order of the custom items in context menu

### ISSUE THREAD

**Issue by peps1** [airdcpp-web/airdcpp-webclient#385]
![image](https://user-images.githubusercontent.com/7737205/107318132-ea8d7880-6a50-11eb-82e0-52a8e72c679d.png)

Currently the custom items get put in between "Search" and "Reload", it might be nicer to have those added always at the bottom? There was probably some good thought put into that, but couldn't figure it out. 

For my own use-case at least, I'm using the "Reload" and "Refresh in share" buttons a lot, but pretty often, probably when the server is under some load, the custom context menu items just load long enough that I click on the reload or refresh in share button before they even load, and then again almost as many times they load in right the moment I click and I accidentally click one of those.

**Comment by maksis** [comment]
Yeah, delays with loading of extension context menu items should have been considered
