### ISSUE TITLE
The --configure option with the set up wizard was not able to create and modify a file called web-server.json

### ISSUE THREAD

**Issue by Horuyuki** [airdcpp-web/airdcpp-webclient#391]
### Current UI and client versions:
Application version
AirDC++w 2.11.0 x86_64
Web UI version
2.11.0
Web UI build date
January 8, 2021 9:30 AM
API version
1
API feature level
7

### Operating system:

Arch linux with lts kernel
Compiled with AUR package

### Steps to reproduce the issue:

If you run `airdcppd --configure`, and choose the port in the wizard. It does not create the web-server.json file in the designated directory. So if I start the session, it will just keep to default, 5600 and 5601. Though the user settings file is created and logs me in alright.

Then I had to go into the web UI, change the ports there, restart and then the file is created and ports changed.

### Screenshots

I don't think that is really necessary here.

**Comment by maksis** [comment]
I can confirm this

**Comment by maksis** [comment]
This will be fixed in the next version
