### ISSUE TITLE
[LINUX] Multiple Selection

### ISSUE THREAD

**Issue by KERNEL59** [airdcpp-web/airdcpp-webclient#393]
Hi Dev , 

Possible add option : multiple selection for linux version 

Thank you very much for your work

**Comment by maksis** [comment]
Is this the same as https://github.com/airdcpp-web/airdcpp-webclient/issues/90 ?

**Comment by KERNEL59** [comment]
> 
> 
> Is this the same as #90 ?

YES  ;) it's for when ? , Thank you so much ! :)

**Comment by maksis** [comment]
> it's for when

I can't promise anything. I'm closing the issue in favor of https://github.com/airdcpp-web/airdcpp-webclient/issues/90
