### ISSUE TITLE
Proxy Connection Problems

### ISSUE THREAD

**Issue by Horuyuki** [airdcpp-web/airdcpp-webclient#394]
I always set up a proxy connection to my VPS with a command like this:
```
ssh -D 5050 -f -C -q -N user@ip.address
```
But then if I bind airdc to the local address and port, things don't work right and this pops up:
https://i.imgur.com/rssbcGW.png

Browsing with the proxy and doing other things work alright, but it cannot load the file list of any person I try to connect to. On different hubs too. Any idea what problem / fix this could be or get?

Thanks for looking!

**Comment by maksis** [comment]
SOCKS5 functionality has been tested with [Brook proxy server](https://txthinking.github.io/brook/) as it's one of the few ones that also support UDP traffic. It's rather easy to set up so you could check whether it changes anything.

**Comment by Horuyuki** [comment]
But the problem still pertains, the file list won't load for some reason.

**Comment by maksis** [comment]
Could you test in the dev hub? adcs://web-dev.airdcpp.net:1511

**Comment by Horuyuki** [comment]
Yes I did connect and tested it there. The file lists are always stuck in pending when I am using the brook proxy or just any proxy.

**Comment by Horuyuki** [comment]
Alright problem is solved.

For anyone who is experiencing the same thing when using a proxy. Remember to also set up a port forwarding from the ports used by airdc to the port of the local proxy. That way stuff can go through.

**Comment by Horuyuki** [comment]
Alright problem is solved.

For anyone who is experiencing the same thing when using a proxy. Remember to also set up a port forwarding from the ports used by airdc to the port of the local proxy. That way stuff can go through.
