### ISSUE TITLE
Search field only accepts RETURN key but not ENTER

### ISSUE THREAD

**Issue by Bonilla** [airdcpp-web/airdcpp-webclient#408]
### Current UI and client versions:

Application version: AirDC++w 2.11.0 x86_64
Web UI version: 2.11.0
Web UI build date: January 8, 2021 3:30 PM
Chromium version: 93.0.4577.63

### Operating system:

Ubuntu 18.04.5 LTS

### Steps to reproduce the issue:

Click on search and enter a search string. When hitting the RETURN key, the application starts searching. However, when hitting the ENTER key, nothing happens.

**Comment by maksis** [comment]
This should be fixed already in the latest version: http://airdcpp-web.github.io/2021/07/27/version-2.11.1.html

**Comment by Bonilla** [comment]
Thanks a lot!
