### ISSUE TITLE
Web UI has crashed with the following error: "TypeError: t is undefined"

### ISSUE THREAD

**Issue by gmipf** [airdcpp-web/airdcpp-webclient#411]
### Current UI and client versions:
Application version
AirDC++w 2.11.0 x86_64
Web UI version
2.11.0
Web UI build date
January 8, 2021 3:30 PM
API version
1
API feature level
7

Copy from *Settings* -> *About*

UI related issues should also include the browser version. Please ensure that you are using the latest application and UI versions that are available (visit https://airdcpp-web.github.io/blog/).

### Operating system:
Kubuntu 20.04 kernel 5.13.0-1014-oem

Name and version of the operating system on which the application is installed on

### Steps to reproduce the issue:

If you are unable to reproduce the issue, you can explain that what was happening before the crash/issue occurred. If it is a recurring issue, please mention how often does it occur.

**Comment by maksis** [comment]
Probably related to https://github.com/airdcpp-web/airdcpp-webclient/issues/412

Closing as there is no stack trace (and it's not from the latest UI version)
