### ISSUE TITLE
Abillity to change user name?

### ISSUE THREAD

**Issue by Horuyuki** [airdcpp-web/airdcpp-webclient#414]
I want to keep the current user and its content but change its login name.

Clicking edit has the name field grayed out unable to be edited.

Could this feature be added or is there another way to change the name?

**Comment by maksis** [comment]
What's the content that you want to keep? You can just create a new user with the same password and permissions.

**Comment by Horuyuki** [comment]
> What's the content that you want to keep? You can just create a new user with the same password and permissions.

Like hashed info, hubs, share and settings.

**Comment by maksis** [comment]
> Like hashed info, hubs, share and settings.

Those are not user-specific so creating a new user should work just fine

**Comment by Horuyuki** [comment]
> > Like hashed info, hubs, share and settings.
> 
> Those are not user-specific so creating a new user should work just fine

Oh thank you! I should have tried it before posting here. Sorry about this.
