### ISSUE TITLE
Ubuntu 21.10 Active mode issue

### ISSUE THREAD

**Issue by dr-soysause** [airdcpp-web/airdcpp-webclient#418]
Hi, since i started to use AirDC++ Webclient on Ubuntu. i've faced some issues in Active mode.
I've forward used ports in my router config, turned off the firewall via "ufw disable" command, and when iam connected to the server in Active mode i cant download filelists or shared stuff, but still able to search (somehow). In passive mode everything is fine.
In connectivity IPv4 options i have 0.0.0.0 as a bind adress, Connectivity - Active mode (no router or manual router...), Empty string in External/WAN IP and unchecked two last options. I've tried to varying with this options but nothing is helped.
Сan't figure out where the problem might be.

Application version
AirDC++2.11.2 x64
Web UI version
2.11.2

**Comment by tokenwizard** [comment]
Well, I guess all I had to do was post an issue and now it magically works...
This can be closed.
