### ISSUE TITLE
ConfigPrompt.h: No such file or directory

### ISSUE THREAD

**Issue by perlaxe** [airdcpp-web/airdcpp-webclient#42]
Building CXX object airdcppd/CMakeFiles/airdcppd.dir/main.cpp.o
/home/airdcpp-webclient/airdcppd/ConfigPrompt.cpp:19:26: fatal error: ConfigPrompt.h: No such file or directory
 #include "ConfigPrompt.h"
                          ^
compilation terminated.
make[2]: *** [airdcppd/CMakeFiles/airdcppd.dir/ConfigPrompt.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/airdcpp-webclient/airdcppd/main.cpp:28:26: fatal error: ConfigPrompt.h: No such file or directory
 #include "ConfigPrompt.h"
                          ^
compilation terminated.
make[2]: *** [airdcppd/CMakeFiles/airdcppd.dir/main.cpp.o] Error 1
make[1]: *** [airdcppd/CMakeFiles/airdcppd.dir/all] Error 2
make: *** [all] Error 2

**Comment by maksis** [comment]
I don't get that because ConfigPrompt.h exists in the repository. Are you missing files?

**Comment by perlaxe** [comment]
I did a git pull, maybe I start over again.

**Comment by maksis** [comment]
Is this still a valid bug?
