### ISSUE TITLE
Linux Debian 11 (Stable) - AirDC++w 2.11.2  - Aborted (core dumped)

### ISSUE THREAD

**Issue by slrslr** [airdcpp-web/airdcpp-webclient#421]
### Current UI and client versions:

Application version AirDC++w 2.11.2 x86_64
Web UI version 2.11.2
installed [like this](https://internetlifeforum.com/showthread.php?21283-How-to-install-AirDC-on-Linux-web-UI).

### Operating system:

Stable version of the Debian, KDE latest desktop interface from main repository of the OS

### Steps to reproduce the issue:

$ $HOME/airdcpp-webclient/airdcppd
```
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files
Loading Country information
Loading Connectivity
Loading Web server
/usr/bin/nodejs
.

AirDC++w 2.11.2 running, press ctrl-c to exit...

HTTP port: 5600, HTTPS port: 5601
Config path: /home/user/airdcpp-webclient/config/
Web resources path: /home/user/airdcpp-webclient/web-resources/
[2022-05-11 14:21:00] [connect] WebSocket Connection [::1]:12345 v13 "" /api/v1/ 101

Signal: Aborted (core dumped)
```

$ coredumpctl info

```
       Message: Process 49583 (airdcppd) of user 1000 dumped core.
                
                Stack trace of thread 51030:
                #0  0x00000000008d7e47 n/a (/home/user/airdcpp-webclient/airdcppd + 0x4d7e47)
```

Is there anyone who have experience debugging these crashes? I have managed to get some 200MB large dump file (sudo coredumpctl dump --output a) but i am not willing to share it publicly for privacy reason, any private contact?

I can see it is dumping core very often for me and eiskaltdc, linuxdc crashing right away after start.

**Comment by maksis** [comment]
Did you follow https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#application-crashes ?

Are you using a portable build or did you compile the app by yourself?

**Comment by slrslr** [comment]
I have not found exceptioninfo.txt , [i see this](https://bin.disroot.org/?2f6922b75b3fcc07#B2VGRp6z6bPRapmoaVrxcjR2fy5om5qJAnMX4XCqAnaA).
Not sure which build or portable. I am using what is described under link that i have already posted in the initial post..

**Comment by maksis** [comment]
Do you have any idea of how you installed the application?

**Comment by maksis** [comment]
So looks like you are using a portable version. Try following https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#application-freezesdeadlocks and download the symbols...

**Comment by maksis** [comment]
It may even produce a better log even if you only download the debugging symbols

**Comment by slrslr** [comment]
It is starting OK now. no crash.

> It may even produce a better log ... download the debugging symbols

maybe you mean "coredumpctl info". It is 100MB debugsymbols file. Maybe this can be closed since it no longer crash after start and so if it will crash later, i will try to rember to install debugsymbols and then do "coredumpctl info" to supply more info you need.

**Comment by slrslr** [comment]
Btw. this may not be related but i was requested by your software to submit this here:

Web UI has crashed

Please submit a bug report with the requested information (and the crash details below) at the [issue tracker](https://github.com/airdcpp-web/airdcpp-webclient/issues).
Crash details
[
detail.. here](https://bin.disroot.org/?167888c2a419e02c#HuAQc6aeYEeN8zxSKgSKD5qUwYCkyZFadsCG3w4mmxfn)
