### ISSUE TITLE
Transfers: Unable to send file PATH-HERE: Bytes were requested beyond the end of the file (DownloderNameHere)

### ISSUE THREAD

**Issue by slrslr** [airdcpp-web/airdcpp-webclient#428]
AirDC++w 2.11.2 x86_64
Web UI version 2.11.2
Browser Firefox-ESR
Linux Debian

It is the message that bothers me every couple of minutes for single file:
`Transfers: Unable to send file PATH-HERE: Bytes were requested beyond the end of the file (DownloderNameHere)`

When i move that txt file away, then it continue showing the warning even for this non existing file.

When i "cat" the content of that text file, it is [here](https://bin.disroot.org/?2ae14f5f52c89b3b#BYFcgzq2fJPyhNqU42AiPoKFwGLWUiWpUKny8PHRUEgf).

After i kill the process (you do not make it possibly to quit from GUI) and start again, it continue showing the warning (even file is not there anymore).

**Comment by maksis** [comment]
There's something wrong with the downloader's client if he tries to download data beyond the end of the file. Unless he's using AirDC++, there's nothing wrong with this app. It might be a better idea to inform the other user about the issue (or block him from the firewall).

> When i move that txt file away, then it continue showing the warning even for this non existing file.

Did you refresh your share...?

**Comment by slrslr** [comment]
@maksis 

> There's something wrong with the downloader's client if he tries to download data beyond the end of the file

I was rather expecting (as a layman) that the file was modified on my end or corrupted.

> Did you refresh your share...?

Likely no, as a layman i would expect i add folders for sharing and AirDC will do the rest including keeping share up to date - maybe using operating system folder monitoring function - for example https://github.com/zlatinb/muwire/#readme utilize it including file re-scan if it finds difference (IIRC).

After some time I no longer see the error, maybe i did refresh after all.

**Comment by maksis** [comment]
> Likely no, as a layman i would expect i add folders for sharing and AirDC will do the rest including keeping share up to date - maybe using operating system folder monitoring function - for example https://github.com/zlatinb/muwire/#readme utilize it including file re-scan if it finds difference (IIRC).

You need to install the share monitoring extension if you want to monitor files for changes in real time....

**Comment by slrslr** [comment]
> You need to install the share monitoring extension if you want to monitor files for changes in real time....

Does not seem to be available at https://www.airdcpp.net/download
And at https://github.com/airdcpp-web/airdcpp-share-monitor/releases are no releases
But inside app, Settings / Extensions / Extensions catalog i have enabled it. Thank you for this workaround.

**Comment by maksis** [comment]
Yes, it should be installed from the app
