### ISSUE TITLE
Unable to access file list

### ISSUE THREAD

**Issue by pnicto** [airdcpp-web/airdcpp-webclient#429]
### Current UI and client versions:

![About](https://i.imgur.com/QCc53Kz.png)

### Operating system:

OS: EndeavourOS Linux x86_64 
Kernel: 6.0.2-arch1-g14-1 

### Steps to reproduce the issue:

Happens every time I try to access file list. Tried on [adcs://web-dev.airdcpp.net:1511](adcs://web-dev.airdcpp.net:1511) still the same issue.

### Screenshots

![Screenshot](https://i.imgur.com/YKoWtMz.png)

Output of `airdcppd --no-autoconnect --cdm-hub --cdm-client --cdm-web > output.txt`

http://0x0.st/o3-I.txt

**Comment by maksis** [comment]
Did you check the instructions for investigating connectivity issues under _Settings_ -> _Connectivity_?

**Comment by pnicto** [comment]
Yes I tried. It cannot be a firewall issue because my friend is able to connect and download. I tried the port checker it says port is closed and when I open the port on firewall-cmd it shows some error saying wrong port and I cannot connect to the hub. And the port changes frequently.

![Connectivity](https://i.imgur.com/YPynjxe.png)

I set these to active mode after reading the sourceforge FAQ as I am directly connected.

**Comment by maksis** [comment]
> It cannot be a firewall issue because my friend is able to connect and download

It only means that his connectivity settings are configured correctly

> And the port changes frequently.

What do you mean? You can configure the ports manually from _settings/connectivity/ports_ and those shouldn't change.

**Comment by pnicto** [comment]
> It only means that his connectivity settings are configured correctly

Oh. I assumed since he is able to connect to me and download from me. I thought firewall is not the problem.

> What do you mean? You can configure the ports manually from settings/connectivity/ports and those shouldn't change.

When I open some port in my firewall and restart airdcpp it's changing the ports there again. I figured out the issue. It was indeed with firewall. Resetting it fixed it. 

Thank you and sorry for wasting your time.

**Comment by maksis** [comment]
> I assumed since he is able to connect to me and download from me.

When a user who's in active mode tries to download from you, he's actually telling your client to connect to _him_
