### ISSUE TITLE
Colour coded files/folders from share

### ISSUE THREAD

**Issue by bluboyo** [airdcpp-web/airdcpp-webclient#431]
I would like to have the same colour coded lines that the windows client have.
In pms and main chats shared folders and files are shown in a different colour. Very nice when checking differents list. To know what i have.

**Comment by maksis** [comment]
Shared/queued files/directories are already marked with a different color. Is that not working for you?

**Comment by bluboyo** [comment]
in search yes. But not in pm or main. So i cant see which requests i got for example.

**Comment by maksis** [comment]
> in search yes. But not in pm or main. So i cant see which requests i got for example.

That's a bug
