### ISSUE TITLE
Cant Login in Webinterface

### ISSUE THREAD

**Issue by GoTo1518** [airdcpp-web/airdcpp-webclient#435]
Hello im setting up the AirDC++ WebClient on a TrueNAS 13.1 release.

I followed this Guide https://gist.github.com/Zamana/4b8021d79f626d5cf656926aa465a652

When i try to Login comes the Error "Authentification failed. Invalid username or password."

I tested a lot of user/password combination with "airdcppd --add-user"

Dont work.

**Comment by maksis** [comment]
@Zamana any ideas?

**Comment by Zamana** [comment]
Hi!

Did you execute step 7?

su <the_user>
airdcppd --configure
exit

You set username AND password in this step.

**Comment by maksis** [comment]
@GoTo1518 were you able to solve the problem?
