### ISSUE TITLE
gui client

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#44]
Was wondering if there is any gui client that can connect to airdcpp-webclient core?

Sort of like transmission-qt (windows) that can run on you machine and connect to a remote daemon?

**Comment by maksis** [comment]
There are none available (this is a young project)

**Comment by KipourosV** [comment]
Can't the windows version connect to a remote core? I'm installing just to check it out...

**Comment by maksis** [comment]
No, it can only be used locally. There nothing else available that can utilize the API.
