### ISSUE TITLE
handle_transport_init received error: TLS handshake failed

### ISSUE THREAD

**Issue by gmipf** [airdcpp-web/airdcpp-webclient#441]
### Current UI and client versions:

AirDC++w 2.11.3 x86_64

UI related issues should also include the browser version. Please ensure that you are using the latest application and UI versions that are available (visit https://airdcpp-web.github.io/blog/).

### Operating system:

Fedora 36 KDE Spin (6.0.18-200.fc36.x86_64)

### Steps to reproduce the issue:

I haven't done anything (I think?), yesterday it was working fine. Already happened while on v2.11.2, upgrade didn't fixed the problem. Connecting to the webapp via port 5600 without TLS is working.

### Screenshots

```
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: Loading Web server
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: .
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: AirDC++w 2.11.3 running, press ctrl-c to exit...
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: HTTP port: 5600, HTTPS port: 5601
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: Config path: /home/gmipf/.airdc++/
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: Web resources path: /usr/local/share/airdcpp/web-resources/
Jan 20 17:20:01 [REMOVED] airdcppd[5520]: [2023-01-20 17:20:01] [connect] WebSocket Connection [::1]:55976 v13 "" /api/v1/ 101
Jan 20 17:20:04 [REMOVED] airdcppd[5520]: [2023-01-20 17:20:04] [error] handle_transport_init received error: TLS handshake failed
Jan 20 17:20:04 [REMOVED] airdcppd[5520]: [2023-01-20 17:20:04] [fail] WebSocket Connection [fe80::[REMOVED]%eno1]:47126 - "" - 0 websocketpp.transport.asio.socket:8 TLS handshake failed
Jan 20 17:20:04 [REMOVED] airdcppd[5520]: [2023-01-20 17:20:04] [info] asio async_shutdown error: asio.ssl:167772567 (shutdown while in init)
```

**Comment by maksis** [comment]
Looks identical to https://github.com/airdcpp-web/airdcpp-webclient/issues/440...

**Comment by maksis** [comment]
This is also missing the most important information requested in the issue reporting instructions for this issue type. The link to the instructions was also in the issue template: https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#communication-issues-between-the-ui-and-the-application

Based on the information provided, your browser is simply just rejecting the daemon certificate (it's a config issue)

**Comment by gmipf** [comment]
You are right. Fixed the problem after removing the cert from the exception in Firefox.

**Comment by mark-4dollar** [comment]
@gmipf Can you elaborate on what you did to resolve this?  I am having the same issue on Fedora 38 in Brave (tried Firefox with the same result).  Certificate is rejected/untrusted by the browser.

**Comment by gmipf** [comment]
> @gmipf Can you elaborate on what you did to resolve this? I am having the same issue on Fedora 38 in Brave (tried Firefox with the same result). Certificate is rejected/untrusted by the browser.

Can't quite remember anymore but I think you need to remove the old airdc certificate from your web browser.
