### ISSUE TITLE
Not automatically download a file in the queue when deleted and put again

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#447]
### Current UI and client versions:

**Application version AirDC++w** 2.11.3 x86_64  
**Web UI version** 2.11.4

### Operating system:

Debian 11

### Steps to reproduce the issue:

Let's say you have user A and user B:
1. A has a file "XXXX" (and only A has it)
2. B refresh the filelist of A, and see "XXXX" in the filelist
3. A move the file to a subfolder "YYYY"
4. B try to download the file "XXXX"
5. A has the message "Unable to send file [....]"
6. A refresh his share
7. A see in the events window "The file XXX has finished hashing"
8. B go do the file in queue, see it show "No Source"
9. B push on "Search for alternates"
10. B see "1/1 online" in sources in the queue windows
but the file does not download (and is in "waiting 0.0%" mode)
and that, will I have a transfer (even completed) with A
(for eg refreshing the filelist of A)

**Comment by maksis** [comment]
I couldn't reproduce this. What's listed in the transfer view when you do step 9?

**Comment by maksis** [comment]
@Kcchouette are you interested in trying to reproduce it with the demo instance?

**Comment by Kcchouette** [comment]
> I couldn't reproduce this. What's listed in the transfer view when you do step 9?

![Screenshot 2023-05-16 at 13-43-54 - AirDC Web Client](https://github.com/airdcpp-web/airdcpp-webclient/assets/3000936/7aee1484-ba54-4657-b8e6-82009a67c3bc)

**Comment by Kcchouette** [comment]
And so, here screen of 10
![Screenshot 2023-05-16 at 13-44-16 - AirDC Web Client](https://github.com/airdcpp-web/airdcpp-webclient/assets/3000936/d2be21b7-9029-44b3-a565-cd87f50db01d)

And then the transfert above "expire" but the file stay in the queue
![Screenshot 2023-05-16 at 13-44-11 - AirDC Web Client](https://github.com/airdcpp-web/airdcpp-webclient/assets/3000936/f1b446ea-9310-4428-b864-c942f0da08eb)

**Comment by Kcchouette** [comment]
> @Kcchouette are you interested in trying to reproduce it with the demo instance?

Yes, you need to be present :)
