### ISSUE TITLE
Download to... function no error is found in logs or Events when trying to download to an directory with no write permission

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#45]
When using the "Download to..." function no error is found in logs or Events when trying to download to an directory with no write permission for the airdcppd user.

Also an Event is logged every 60 minutes, can I some how acknowledge this so it does not continue?
Searching the bundle Ubuntu.iso for alternatives, 1 search(es) queued. Next search in 60 minutes

I think a Event with information just that destination for Download to... is not writable would be enough and don't try with the same search next hour at all?

Application version: AirDC++w 0.13.1 x86_64 / 0.850
Web UI version: 0.13.4

**Comment by bissa** [comment]
Application version: AirDC++w 0.13.1 x86_64 / 0.850
Web UI version: 0.13.4

**Comment by maksis** [comment]
Please post a single issue/feature request per report.

I get a "permission denied" status for bundles when there is no write permission (a notification could be added too).

**Comment by maksis** [comment]
Fixed in https://github.com/airdcpp-web/airdcpp-webui/commit/7cadd79a6584b9e6d6d3aaddbd6331b46d38326c
