### ISSUE TITLE
Different share profiles for different hubs from the same single client?

### ISSUE THREAD

**Issue by newyokohama** [airdcpp-web/airdcpp-webclient#451]
Good morning,

I have a single instance of the web client (no windows client, no other instances of AirDC++). What I'd like to do is this:

Be a member of two hubs: "hub1" and "hub2", and then make two share profiles: "apples" and "oranges" with different items in them. From this single client instance, I'd like to share both apples and oranges with hub1, but only apples with hub2.

Is this possible? Thanks you for all your continued great work. :-)
-NY

**Comment by maksis** [comment]
Yes, you can customize the share profile for each favorite hub (given that the feature is supported by the hub)

**Comment by newyokohama** [comment]
> Yes, you can customize the share profile for each favorite hub (given that the feature is supported by the hub)

Thank you so much - maybe I'm not seeing where to do it. Making an "apples" profile and an "orange" profile is just fine, but when I move shares into profiles, it changes on each hub. Under the share profile options, I was looking for a method to say "this should be shared only in *this* hub. Would you mind sharing where the option is to set that in the Profiles menu?

Thanks again
