### ISSUE TITLE
AirDC++ systematically crashes when exited, after scanning my library

### ISSUE THREAD

**Issue by awsms** [airdcpp-web/airdcpp-webclient#454]
### Current UI and client versions:

Application version: AirDC++w 2.12.1 x86_64
Web UI version: 2.12.0

### Operating system:

Ubuntu 22.04

### Steps to reproduce the issue:

Launch the scan of my library
When done, exit the program with Ctrl+C in my terminal
```
Shutdown requested...
Saving hash data
Saving the share cache
fish: Job 1, './airdcppd --verbose' terminated by signal SIGKILL (Forced quit)
```

I can see in htop AirDC++ is progressively filling all my RAM, then crashes with a SIGKILL.

**Comment by maksis** [comment]
If the issue is caused by a certain path, it would be useful to locate that. Could you try refreshing each of your share roots individually to see if the exit happens with all of them?

Do you have the option `Follow symbolic links` enabled under `Settings` -> `Sharing` -> `Sharing options`? If yes, you could try disabling the option to see if it makes any difference.

**Comment by awsms** [comment]
I do have the follow symlinks option enabled since my library is organized in two folders on airdcpp: one contains mostly symlinks, the other one doesn't have any. The second one is making airdcpp crash.

**Comment by maksis** [comment]
Could there be symlinks created in a way that they cause an infinite loop? You can also refresh individual subdirectories from own filelist if you need to investigate it further.

**Comment by maksis** [comment]
@awsms were you able to solve this?

**Comment by awsms** [comment]
> @awsms were you able to solve this?

I wasn't unfortunately. Is it possible to enable debug flags in the program?

**Comment by maksis** [comment]
Debug build won't probably help in this case as it won't list the files that are being refreshed.

You could try running the following command in terminal before you perform the refresh:

`sudo strace -f -t -e trace=file -p PID` (replace PID at the end with the airdcppd process ID)

You can then see the files that are being scanned from the output and where it stops

**Comment by maksis** [comment]
Closing as there is no response
