### ISSUE TITLE
Ability to use a schedule for the refresh of the share

### ISSUE THREAD

**Issue by EcceGratum** [airdcpp-web/airdcpp-webclient#468]
**Is your feature request related to a problem? Please describe.**
We should be able to set a schedule for the refresh of the share. For example :
Once daily at 7am, once weekly on sunday at 3:30pm or monthly in addition to the auto refresh time

**Describe the solution you'd like**
Replace the "Auto refresh time" in the settings by an option to choose either "On interval" which let us specify an amount of time in minutes or a Daily or Weekly trigger which let us choose the day and the time (hour : minute)

**Describe alternatives you've considered**
There is no alternative that would consistently respect a schedule

**Additional context**
![image](https://github.com/airdcpp-web/airdcpp-webclient/assets/13237633/41931bc3-4504-4bc9-8d1d-d5085cbdb30e)

**Comment by maksis** [comment]
You can disable the scheduled refresh and use the API to trigger the refresh whenever you want: https://airdcpp.docs.apiary.io/#reference/share/refresh-methods/refresh-whole-share (see the beginning of the docs if you haven't used the API before)
