### ISSUE TITLE
Can someone walk me through installing a legit SSL cert?

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#47]

**Comment by KipourosV** [comment]
I have two crt files, one is the intermediate CA....
Which one goes where?

**Comment by maksis** [comment]
Are you attempting to make the client use another certificate? Certificates are used by the client are located in ``~/.airdc++/Certificates``. I don't know if anyone has attempted to use custom certificates though.

**Comment by KipourosV** [comment]
I'm not sure if I have to merge my two cert files into one (CA+cert)

I'm gonna give it a go later on. I'll try it and tell you what I find...

**Comment by maksis** [comment]
It didn't make much sense to use a custom certificate without the Web UI so I'm not sure that how well those are being handled in the core. Note that currently the client will replace the certificate files three months before they expire.

**Comment by maksis** [comment]
Were you able to solve this?
