### ISSUE TITLE
"Add search types" goes to a blank screen

### ISSUE THREAD

**Issue by chowbok** [airdcpp-web/airdcpp-webclient#473]
Running application version AirDC++w 2.12.2 x86_64, webui version 2.12.1 on Arch Linux. When I go to Downloads → Search types and click "Add type", I just get the background screen and menu bars with no window.

**Comment by maksis** [comment]
This will be fixed in the next version. As a workaround, you can access the dialog with a direct URL: `/settings/downloads/search-types/types`
