### ISSUE TITLE
Search always returns no results

### ISSUE THREAD

**Issue by tokenwizard** [airdcpp-web/airdcpp-webclient#475]
### Current UI and client versions:

Application version: AirDC++w 2.12.2 x86_64
Web UI version: 2.12.1
Firefox 128

UI related issues should also include the browser version. Please ensure that you are using the latest application and UI versions that are available (visit https://airdcpp-web.github.io/blog/).

### Operating system:

Arch Linux (Manjaro 24 XFCE)

### Steps to reproduce the issue:
Open the WebUI and search for anything. No matter what, it says no results found. 

I can browse user lists and download directly from users, but I cannot find anything with the Search function. It seems to be related to the UDP port for the Search. I have manually specified the ports as shown below: 
![image](https://github.com/user-attachments/assets/b476d177-5472-4b9b-bb42-ce4fc3487a75)

The application itself runs on ports 5600/5601. 

I added port forwarding to my router for the three ports above, TCP/UDP for 5700 and 5701 as well as UDP for 5702.

When I use nmap to scan my public IP, it shows 5700 and 5701 open but not 5702 for some reason. It seems like the application may not be properly initializing the search port? 

![image](https://github.com/user-attachments/assets/f0db902c-a07b-4514-8141-08d3c55a7553)

**Comment by maksis** [comment]
@tokenwizard did you mean that this issue can be closed?

**Comment by tokenwizard** [comment]
Yes, it is working now. No idea why it wasn't or what fixed it.

Sent with [Proton Mail](https://pr.tn/ref/VRWE11731E0G) secure email.
