### ISSUE TITLE
Migrating Client from Win to Linux

### ISSUE THREAD

**Issue by ray-bloody-purchase** [airdcpp-web/airdcpp-webclient#476]
Apologies ahead of time if this isn't the correct spot for this question.

I'm setting up a new box, with it I also want to finally ditch Windows for Linux (Linux beginner here). Can the 'Settings' folder simply be copied over or will I have to start from scratch to setup the new Linux based client? Not looking forward to re-hashing the db if the latter is the case.

Thank you.

**Comment by maksis** [comment]
I recommend that you only copy the favorites file and do everything else from scratch. The biggest issue is that the path format is different on Linux.

**Comment by ray-bloody-purchase** [comment]
Well, at least the favorites will transfer, so that's good. It'll just take a bit longer to migrate the rest than anticipated. Thanks again!
