### ISSUE TITLE
Documentation Link is no good

### ISSUE THREAD

**Issue by tokenwizard** [airdcpp-web/airdcpp-webclient#477]
When I click any links to Docs from within the Web Client (and even some referenced here) I just get this:
 
![image](https://github.com/user-attachments/assets/5f1ce1b7-7157-4458-a319-2308f1309d30)

This is an example link that give this error. 
https://www.airdcpp.net/component/k2/25-setting-parameters

Can someone please point me to the list of available path variables?

**Comment by maksis** [comment]
> Can someone please point me to the list of available path variables?

The variables are listed at https://dcplusplus.sourceforge.io/webhelp/settings_logs.html

Download directory paths accept all time format variables and an _username_ variable that will be replaced with the current system user.

**Comment by tokenwizard** [comment]
So if I put the Username variable in the Download Path like this:
![image](https://github.com/user-attachments/assets/e810cb46-aabb-4357-9d7e-5c55ad6dd3b8)

Should i expect it to download all files into subdirectories of the user I'm downloading from? It seems to still be placing them in the DCPP folder, not a subfolder of the user's name.

**Comment by maksis** [comment]
No, download paths only accept time variables and %[username] that is your system username. The other variables are only for logging. If there's a variable that you'd like to be added, you can request new ones.

**Comment by maksis** [comment]
New docs: https://airdcpp.net/docs/usage/setting-variables.html
