### ISSUE TITLE
Unable to launch on FreeBSD 13.3

### ISSUE THREAD

**Issue by Freeben666** [airdcpp-web/airdcpp-webclient#478]
Hello,

I've ran Airdc++-webclient on my TrueNAS server for years. I updated to 13.3 and decided to update my Airdc++ jail.

Problem is, even though no problem arises during while compiling, there is a hardcrash when trying to launch Airdc++

### Current UI and client versions:

Trying to install 2.12.2

### Operating system:

TrueNAS 13.3 (FreeBSD 13.3-RELEASE-p4 (amd64))

### Steps to reproduce the issue:

Try compiling the webclient on FreeBSD

### Screenshots

```
$ /usr/local/bin/airdcppd -c=/home/airdcpp/.airdc++ -p=/var/run/airdcppd/airdcppd.pid
Starting.
.

Signal: 11
Process ID: 42452
Time: 17:38:39
OS version: FreeBSD 13.3-RELEASE-p4 (amd64)
Client version: AirDC++w 2.12.2

Collecting crash information, please wait...
0x220f00 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x21eda0 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x822f4a4af in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x822f49a6b in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x7ffffffff2d3 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x8223eec8b in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x8223e6120 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x822550035 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x82254ff2b in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x822480761 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x2173a0 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]
0x217067 in function [unknown] in file /usr/include/c++/v1/vector:963 [0x0000000]

Exception info to be posted on the bug tracker has also been saved in /home/airdcpp/.airdc++/exceptioninfo.txt

Press enter to exit
```

**Comment by Freeben666** [comment]
> There's another user with the same operating system and he hasn't reported any crashes: #472
> 
> Have you tried removing the old cached build files before compiling? `git clean -fdx` if you are using git

Since I've been building in a brand new jail, there were no cached files.


> I just tested it and actually got a crash as well on the latest FreeBSD v14.1 but it's now fixed with [airdcpp/airdcpp-windows@a2b8353](https://github.com/airdcpp/airdcpp-windows/commit/a2b8353c5af5ba86d7f14c8614b573bfe9df0a39)
> 
> You can try the fix by switching to the develop brach (`git checkout develop`), pulling the latest changes and recompiling the code

I'll give it a try and get back to you. Thank you :-)

**Comment by Freeben666** [comment]
@maksis THANK YOU !

I grabbed the latest `develop` branch, compiled, and it launched without a problem 👍

![image](https://github.com/user-attachments/assets/a70d70ba-a1f6-4a3d-b71e-3fbdee1eeb6a)

**Comment by Freeben666** [comment]
Since I'm running a "beta" version, should I be on the look-out for specific potential bugs ?

Do you need more information from me, or should I close this ticket ?

**Comment by maksis** [comment]
No specific things to look for, it's not even in a beta stage yet. Knowing that the crash is gone is the main thing.
