### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Zamana** [airdcpp-web/airdcpp-webclient#479]
Hi!

The link for "compiling instructions" is broken:

https://airdcpp-web.github.io/docs/installation/compiling.html

Regards.

**Comment by maksis** [comment]
Where is that link?

**Comment by Zamana** [comment]
Hi!

I'm sorry. Here it is:

https://github.com/airdcpp-web/airdcpp-webclient/wiki/Dependencies-for-compiling-on-Ubuntu

> Compiling
> You should follow the generic [compiling instructions](https://airdcpp-web.github.io/docs/installation/compiling.html).

**Comment by maksis** [comment]
Maybe the wiki page should be deleted as it's not being maintained by anyone

**Comment by maksis** [comment]
I deleted the page
