### ISSUE TITLE
[Beta version] UPnP does not work on the latest beta version

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#484]
### Current UI and client versions:

**Application version** AirDC++w 2.13.0b x86_64
**Web UI version**2.13.0-beta.1

### Operating system:

Manjaro

### Steps to reproduce the issue:

1. Having an existing folder of airdcpp stable version (AirDC++w 2.12.2 x86_64)
1. 
```
Connectivity (IPv6): Determining the best connectivity settings...
Connectivity (IPv6): Public IP address detected, selecting active mode with direct connection
Connectivity (IPv4): Port mapping: Successfully created port mappings (Transfers: 26092, Search: 23785, Encrypted transfers: 31770) on the "Generic" device with the MiniUPnP interface
```
3. Stop airdcpp if it's working, download latest beta (client version above)
4. copy the `config` folder

Message has changed to
```
Connectivity (IPv6): Determining the best connectivity settings...
Connectivity (IPv6): IPv6 connectivity has been disabled as no public IPv6 address was detected
Connectivity (IPv4): Port mapping: Failed to map the Transfer port (26092 TCP) with the MiniUPnP interface
Connectivity (IPv4): Port mapping: Failed to create port mappings
```

Workaround: going back to the stable version fix the problem

**Comment by maksis** [comment]
Seems like it's only happening with the portable build

**Comment by maksis** [comment]
Please see whether this is now working correctly with the latest beta

**Comment by Kcchouette** [comment]
On latest beta it is working correctly, thanks
