### ISSUE TITLE
Application crashes - FreeBSD jail on Truenas (13.3)

### ISSUE THREAD

**Issue by 35gh** [airdcpp-web/airdcpp-webclient#486]
### Current UI and client versions:

Application version: AirDC++w 2.13.0b-d amd64
Web UI version: 2.13.0-beta.1

### Operating system:

FreeBSD 13.3-RELEASE-p4 n257491-41f6a830f8e TRUENAS amd64

FreeBSD clang version 17.0.6 (https://github.com/llvm/llvm-project.git llvmorg-17.0.6-0-g6009708b4367)
Target: x86_64-unknown-freebsd13.3
Thread model: posix
InstalledDir: /usr/bin

### Steps to reproduce the issue:

This is the continuation of https://github.com/airdcpp-web/airdcpp-webclient/issues/481

Application crashes when opening the "Queue" tab or when downloading a file. With gbd it crashes randomly.

([debug 2024-11-07_0954.txt](https://github.com/user-attachments/files/17658830/debug.2024-11-07_0954.txt))

**Comment by maksis** [comment]
It would be better to create an issue only for a single crash (and only for the latest application version). From which version is the log, 2.13.0 or 2.12.2? Which crash is this, the startup crash or the queue crash?

**Comment by maksis** [comment]
I can reproduce the queue crash on FreeBSD 14

**Comment by 35gh** [comment]
Actually it seems  the debugger is causing extra crashes. Without it I can only reproduce in the "Queue" tab or when I start a download.

**Comment by maksis** [comment]
That's a really annoying crash to find but seems like it's somehow related to the TBB library. Disabling TBB with `cmake -DENABLE_TBB=OFF .` before `make` seems to be a valid workaround for avoiding the crashes before I figure out the exact reason.

**Comment by 35gh** [comment]
Does the last commit you made fully resolve the issue? I can now compile without warnings (nice), but linking fails.

```
[100%] Linking CXX executable airdcppd
ld: error: undefined reference due to --no-allow-shlib-undefined: libiconv_open
>>> referenced by ../airdcpp-core/libairdcpp.so.2.13.0b

ld: error: undefined reference due to --no-allow-shlib-undefined: libiconv
>>> referenced by ../airdcpp-core/libairdcpp.so.2.13.0b

ld: error: undefined reference due to --no-allow-shlib-undefined: libiconv_close
>>> referenced by ../airdcpp-core/libairdcpp.so.2.13.0b
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- airdcppd/airdcppd ---
*** [airdcppd/airdcppd] Error code 1

make[2]: stopped in /root/airdcpp-webclient
1 error

make[2]: stopped in /root/airdcpp-webclient
--- airdcppd/CMakeFiles/airdcppd.dir/all ---
*** [airdcppd/CMakeFiles/airdcppd.dir/all] Error code 2

make[1]: stopped in /root/airdcpp-webclient
1 error

make[1]: stopped in /root/airdcpp-webclient
*** [all] Error code 2

make: stopped in /root/airdcpp-webclient
1 error

make: stopped in /root/airdcpp-webclient

```

**Comment by maksis** [comment]
That's because of conflicting libraries in FreeBSD, which happens after you install gdb. The error should disappear after you uninstall the conflicting package: `pkg delete libiconv` (re-run the cmake command after that)

**Comment by 35gh** [comment]
OK thank you, it compiles now, looking forward for the full fix then as I'm still seeing the crash without the workaround.

**Comment by maksis** [comment]
Please try latest commit with TBB enabled, it no longer crashes for me

**Comment by 35gh** [comment]
It works for me as well, thank you!
