### ISSUE TITLE
Option to force download even if exists in share

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#49]

**Comment by maksis** [comment]
Can you explain that when is such option needed?

**Comment by KipourosV** [comment]
If I have an incomplete or failing bundle,
I have to locate it, delete it, and rehash the share
in order to be able to redownload.

Forcing the download and replaceing is faster, and more usefull imho.

**Comment by maksis** [comment]
Adding new items to a bundle shouldn't be an issue (because it's not shared). What do you have to replace?

**Comment by maksis** [comment]
Any updates for this?
