### ISSUE TITLE
Download speed indicator is missing in latest webui

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#56]
Application version: AirDC++w 0.13.3-37-g80c3 x86_64 / 0.850
Web UI version: 0.14.0

Seems to be missing download/hash indicator on right pane with latest webui.

**Comment by KipourosV** [comment]
Yeap, just noticed it too...

**Comment by maksis** [comment]
Fixed in https://github.com/airdcpp-web/airdcpp-webui/commit/f144de69f6fa2c3a5dca372732d614db1e503721
