### ISSUE TITLE
Problem to downloading file

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#62]
When I click on the ```download``` button from a file when I see the filelist, it does nothing.

No log in console.

This work in airdcnano, but don't with the webui.

Thanks

system config
```
Application version
AirDC++ w 0.13.3-46-g2698 x86_64 / 0.850
Web UI version 0.14.1
Web UI build date January 26, 2016 3:02 PM
```
I build the last version from github

**Comment by YamashitaRen** [comment]
I think that I have this bug too with latest webui... Unfortunately, I don't know how to revert to a former one...

**Comment by maksis** [comment]
There's a new UI version available

**Comment by Kcchouette** [comment]
Thanks.

**Comment by Kcchouette** [comment]
It's fixed, yes. Thanks, @maksis!
