### ISSUE TITLE
Can't build releases.

### ISSUE THREAD

**Issue by YamashitaRen** [airdcpp-web/airdcpp-webclient#64]
Git code builds fine but releases (tested with 12.7 and 13.3) error out during the cmake :
https://zerobin.net/?492cf315abf832bb#oX84HRyVNOBIkALRaQLWTtNbf5A4V8AFrKdKemQprZw=
https://zerobin.net/?6c4a459e3af905c6#COhS5vUhhMUY1akilwqlzrfM/qUgX3cvPgEHKA+3Fxg=
http://sprunge.us/IUQE

It should be noted that the same CMakeError.log is silently generated when I builds the git code.
CMakeOutput.log seems to be the same too...

**Comment by maksis** [comment]
Currently you can only build releases from Git, but some improvements could possibly be made
