### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by synaomen** [airdcpp-web/airdcpp-webclient#71]
Now i will make the update for 0.16.0 and after `cmake .`, they print this error:
```
-- Installing Web UI
npm ERR! missing: deep-equal@^1.0.0, required by history@1.13.0
npm ERR! missing: invariant@^2.0.0, required by history@1.13.0
npm ERR! missing: qs@^4.0.0, required by history@1.13.0
npm ERR! missing: warning@^2.0.0, required by history@1.13.0
npm ERR! not ok code 0
```

This is a normal compile on a Debian 8 KDE on my pc.

[Complete cmake output](http://pastebin.com/kXQazc8f)

**Comment by maksis** [comment]
Those error are irrelevant but it's still not good to show them to the user

**Comment by maksis** [comment]
This error should be visible anymore in the next version (possibly due to https://github.com/mjackson/history/commit/4579afe77b31c1ddfadfe6d68c0992bf12756698)
