### ISSUE TITLE
Crash  

### ISSUE THREAD

**Issue by bissa** [airdcpp-web/airdcpp-webclient#76]
Application version: AirDC++w 0.16.1 x86_64 / 0.850
Web UI version: 0.16.0

Console message
11
pid: 885
Collecting crash information, please wait...
*** Error in `airdcppd': malloc(): smallbin double linked list corrupted: 0x00007f7830038f40 ***
Aborted

No other info is available in expeptions file.

**Comment by maksis** [comment]
That kind of crashes don't provide any useful information that would enable tracking them down. What was happening in the client before it crashed?

**Comment by bissa** [comment]
It was a lot in queue for download and had been doing it for a couple of hours, i can really remember doing any thing special.

**Comment by maksis** [comment]
If those crashes start to occur more often, there are things that could be tried. If not, this is very much impossible to solve.

**Comment by bissa** [comment]
Let's close it and see if it happens again.

**Comment by maksis** [comment]
I got a bit similar crash after I had accessed the client via HTTPS so this may be also related to https://github.com/airdcpp-web/airdcpp-webclient/issues/33
