### ISSUE TITLE
Question because ADL Search

### ISSUE THREAD

**Issue by synaomen** [airdcpp-web/airdcpp-webclient#82]
On ~/.airdc++/ i found a ADLSearch.xml, but i can find no "window" for this on the webui. Is this a future function?

**Comment by maksis** [comment]
I'm not planning to add that feature. ADL search is meant for full filelists while the client only uses partial lists.

**Comment by synaomen** [comment]
Ohhh...it is a pity to hear that. That he does now only list partial I've seen.

**Comment by doobnet** [comment]
@maksis Is there any way you could reconsider this decision. I would really like to have this feature. For me it's enough to use on my own list, a command line tool would be enough.

**Comment by maksis** [comment]
Unfortunately I still have no interest in maintaining that feature. 

However, I see no reason why a similar feature couldn't be implemented by using the [API](https://airdcpp.docs.apiary.io/#), possibly as an extension. Read the config file, go through each directory in own filelist, report the results somewhere... you could even schedule the check to be performed at regular intervals.

**Comment by doobnet** [comment]
If the API has everything that's needed that I'm satisfied with giving that a try.

**Comment by maksis** [comment]
Since you are only planning to scan the own filelist, it might actually be easier to scan the content from local filesystem instead (and skipping the filelist API altogether). That's what the [airdcpp-release-validator](https://github.com/maksis/airdcpp-release-validator) is doing at the moment.

**Comment by doobnet** [comment]
Yeah, I was thinking that as well. I'll try out simple first with a completely self-contained command line utility. Thanks for the input.
