### ISSUE TITLE
Transfer Statistics not showing up

### ISSUE THREAD

**Issue by Dhalkar** [airdcpp-web/airdcpp-webclient#84]
Looks like the statistics are not working in the latest version, all I get is:

Total downloaded
NaN kB
Total uploaded
NaN kB
Session
Session downloaded
NaN kB
Session uploaded
NaN kB

AirDC++w 0.16.3 x86_64 / 0.850
Web UI version 0.15.0

**Comment by maksis** [comment]
That's not the latest UI version. Have you followed the updating instructions from https://github.com/airdcpp-web/airdcpp-webclient/blob/master/INSTALL.md ? If yes, try updating once again in case you were affected by the issue in the UI installation script.

**Comment by Dhalkar** [comment]
Silly me, updating it solved the issue. Next time I'll be sure to doublecheck the versionnumber of both components. Thanks!
