### ISSUE TITLE
[Documentation] Have a example of nginx conf

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#86]
I see your demo and I was wondering if you can share with us all your nginx(?) configuration.

I have try to use `proxy_pass http://127.0.0.1:PORT_I_SET_FOR_HTTPS;` but main.entry.js send me a 404 error and so I can't access to `http://myip/myfoldertoaccessairdcpp/`

Thanks

**Comment by maksis** [comment]
The demo is running on express, not nginx and the script can be found from the Web UI repository: https://github.com/airdcpp-web/airdcpp-webui/blob/master/server.js

However, the issue is probably caused by having absolute paths in the UI. Possibly I could check if it can be avoided in future releases.

**Comment by Kcchouette** [comment]
> However, the issue is probably caused by having absolute paths in the UI. Possibly I could check if it can be avoided in future releases.

Thanks if you can do that :+1:

**Comment by maksis** [comment]
Are you able to get your nginx proxy working if you compile the latest UI? See https://github.com/airdcpp-web/airdcpp-webui for compiling instructions. Note that your base path must start with ``airdcpp-`` as routing wouldn't work with random path names.

**Comment by maksis** [comment]
Actually the base path may be irrelevant in that context...

**Comment by infectormp** [comment]
@Kcchouette you can try this config
```
upstream airdcpp
{
        server 12.0.0.1:5600 fail_timeout=0;
        keepalive 16;
}

server
{
        listen 80;
        server_name xxx.xxx;

        return 301 https://$server_name$request_uri;  # enforce https
}

server
{
        listen 443 ssl http2;
        server_name xxx.xxx;

        access_log /var/log/nginx/xxx.access.ssl_log;
        error_log /var/log/nginx/xxx.error.ssl_log;

        include /etc/nginx/default.d/ssl.conf;

        location /
        {
                proxy_set_header Host $http_host; # set the parameter for fine granned header
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_store off;
                proxy_redirect off;
                proxy_buffering off;

                proxy_pass  http://airdcpp;

                proxy_hide_header                               X-Frame-Options;
                proxy_set_header        X-Forwarded-Proto   https;
                gzip                    off;
                proxy_read_timeout      300;
                proxy_connect_timeout   300;

                add_header Cache-Control "no-store";
        }
}
```

**Comment by Kcchouette** [comment]
With 0.16.5 (and UI 0.16.2), it seems I have the same problem.

Here my conf:

```
        location ^~ /foo {
                proxy_pass https://127.0.0.1:5601;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
                proxy_store off;
                proxy_redirect off;
                proxy_buffering off;
        }
```

Thanks

**Comment by infectormp** [comment]
@Kcchouette **do not use** https port for proxy_pass

**Comment by maksis** [comment]
This is now possible in version 1.0.4 of Web UI.

The config I've tested it with:

```
        #
        # AirDC++ Web Client
        #
        # You may change the location path but it must always start with "airdcpp".
        # This is because the UI uses URLs for routing so it must be able to determine
        # the base directory from the URL.
        #
        location /airdcpp/ {
                # Client URL (no need for HTTPS when using localhost)
                proxy_pass  http://localhost:5600/;

                # Gzipping javascript will reduce the transferred data significantly
                # This has no effect if gzip compression is disabled from nginx
                gzip_types      text/plain application/javascript;

                # Proxy websockets
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```

**Comment by maksis** [comment]
https://airdcpp-web.github.io/docs/advanced/nginx-setup.html

**Comment by maksis** [comment]
The guide can now be found from the wiki: https://github.com/airdcpp-web/airdcpp-webclient/wiki (there have been no changes though)

**Comment by Raph521** [comment]
Thanks for the updated link!

I still can't seem to connect through nginx with a base url of "/airdcpp", but I'll try poking around.

**Comment by sbraz** [comment]
@Raph521 try with `rewrite ^/airdcpp/(.*) /$1 break;`, it should work.

**Comment by Raph521** [comment]
Thanks @sbraz!  That worked for me!

For anyone else that stumbles on this, my nginx config looks like the following:

```
    location /airdcpp/ {

        rewrite ^/airdcpp/(.*) /$1 break;

        proxy_pass http://localhost:5600;

        # Gzipping javascript will reduce the transferred data significantly
        # This has no effect if gzip compression is disabled from nginx
        gzip_types      text/plain application/javascript;

        # Proxy websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

```

**Comment by maksis** [comment]
@sbraz is that something that the newer nginx versions require? The example in the wiki should be updated

**Comment by sbraz** [comment]
@maksis I don't really remember (4 years already, wow!) but I think it was always required, otherwise airdc would have received requests for URLs starting with /airdcpp and it wouldn't have accepted those. The Apache config does have the URL rewriting logic, so I don't really know why it wasn't part of the example nginx config before.
