### ISSUE TITLE
When doing a Reload on full file list, nothing happens...

### ISSUE THREAD

**Issue by Sopor-** [airdcpp-web/airdcpp-webclient#88]
If i have a full file list open and i do a 'Reload' on the file list, nothing will happen. Even if the WebUI can't open full file lists it could at least Reload them?

Sorry, i forgot to mention that this was in Windows and that i already have open the full file list from the AirDC client and i then move over to the WebUI to do a reload.

**Comment by maksis** [comment]
I've removed the reload option from full filelists as it's only meant for individual directories
