### ISSUE TITLE
Docker container clean exit airdcpp

### ISSUE THREAD

**Issue by KipourosV** [airdcpp-web/airdcpp-webclient#89]
Running the client in a docker container, having mounted ~/.airdc++ on a host dir for configuration persistence. The problem is that every time I restart my container I lose the share statistics, last share scan time and any user I might have added to the web-interface.

Is there another location that airdc uses to store configurations that I need to mount outside my container?

**Comment by maksis** [comment]
Various settings are saved only on clean exit. I'm not totally sure that what do you mean with losing share statistics as they are calculated from the currently shared files.

**Comment by KipourosV** [comment]
It's seems to me like my stats are stuck, maybe my bad but I definitely lose some settings...

How can I have a clean exit inside a container when airdc is run as daemon? (-d option)

**Comment by maksis** [comment]
``pkill -SIGINT airdcppd`` should work

**Comment by KipourosV** [comment]
-SIGTERM won't do it? cause docker stop sends -SIGTERM by default...
If not, then I'll have to docker kill ----signal=SIGINT foo...

**Comment by maksis** [comment]
Maybe it could be added as well

**Comment by KipourosV** [comment]
docker kill --signal=SIGINT does not work...

What do you mean "it could be added"?

**Comment by KipourosV** [comment]
Last refreshed says 15 days ago on all my folders everytime I run the container...

**Comment by KipourosV** [comment]
Executing pkill -SIGINT airdcppd inside the container seems to work right.
And my settings are all saved.

THANX!
